/**
 * Wire a Hyperframes project up with everything it needs, locally.
 *
 * Nothing a composition needs may be fetched at render time, so every asset is
 * COPIED into the project directory and every data blob is written as a plain
 * `.js` file that assigns a global. The composition then references only
 * sibling files.
 *
 * Usage:
 *   node pipeline/scaffold.mjs <project-dir> --vo <videoId> --img a.png,b.png
 *   node pipeline/scaffold.mjs a-hero-16x9 --vo hero-95 --img hi-overview.png
 *
 * --vo   copies assets/vo/<id>.wav          → <project>/assets/vo.wav
 *        writes  caption-data.js            → window.__CAPTIONS
 *        copies  pipeline/kit/captions.js   → <project>/captions.js
 * --img  copies from assets/capture/ or assets/art/ → <project>/assets/
 */
import { readFileSync, writeFileSync, copyFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");

const argv = process.argv.slice(2);
const projectArg = argv.find((a) => !a.startsWith("--"));
if (!projectArg) {
  console.error("usage: node pipeline/scaffold.mjs <project-dir> [--vo <id>] [--img a.png,b.png]");
  process.exit(2);
}

function flag(name) {
  const i = argv.indexOf(`--${name}`);
  return i === -1 ? null : argv[i + 1];
}

const projDir = projectArg.startsWith("projects/")
  ? join(ROOT, projectArg)
  : join(ROOT, "projects", projectArg);
if (!existsSync(projDir)) {
  console.error(`no such project: ${projDir}`);
  process.exit(2);
}
const projAssets = join(projDir, "assets");
mkdirSync(projAssets, { recursive: true });

const voId = flag("vo");
if (voId) {
  const wav = join(ROOT, "assets", "vo", `${voId}.wav`);
  const caps = join(ROOT, "assets", "vo", `${voId}.captions.json`);
  if (!existsSync(wav)) {
    console.error(`missing VO track: ${wav} — run pipeline/tts.mjs ${voId}`);
    process.exit(1);
  }
  copyFileSync(wav, join(projAssets, "vo.wav"));

  if (existsSync(caps)) {
    const data = JSON.parse(readFileSync(caps, "utf8"));
    writeFileSync(
      join(projDir, "caption-data.js"),
      "/* GENERATED by pipeline/scaffold.mjs from assets/vo/" +
        voId +
        ".captions.json — do not edit. */\n" +
        "window.__CAPTIONS = " +
        JSON.stringify({ cues: data.cues, words: data.words }) +
        ";\n"
    );
  }
  copyFileSync(join(HERE, "kit", "captions.js"), join(projDir, "captions.js"));
  console.log(`  vo      ${voId}.wav + caption-data.js + captions.js`);
}

const imgs = flag("img");
if (imgs) {
  for (const name of imgs.split(",").map((s) => s.trim()).filter(Boolean)) {
    const candidates = [
      join(ROOT, "assets", "capture", name),
      join(ROOT, "assets", "art", name),
      join(ROOT, "..", "assets", name),
    ];
    const src = candidates.find(existsSync);
    if (!src) {
      console.error(`  img     MISSING ${name} (looked in capture/, art/, repo assets/)`);
      process.exitCode = 1;
      continue;
    }
    copyFileSync(src, join(projAssets, basename(name)));
    console.log(`  img     ${name}`);
  }
}

console.log(`  → ${projDir}`);
