#!/usr/bin/env node
/**
 * answer — the operator's sitting: one sheet of every open question, one fold
 * back into the journals.
 *
 * An ask is a `gate` whose `kind` IS its id (`Q-<n>`), raised by
 * `journal.mjs ask`. `render` writes every open one across every initiative
 * into `.tyran/state/ANSWERS.md`; the operator types under the `answer:`
 * lines; `apply` folds each answer back as a `decision` + a closing
 * `gate result: answered`, decision first, and re-renders the projections and
 * the board.
 *
 * Three properties this file exists to hold:
 *
 *  - **Every value written comes out of the JOURNAL, never out of the sheet.**
 *    The sheet is an inbox. A tampered one can change WHICH asks close and
 *    WHAT the operator said, and nothing else — it cannot forge a question, a
 *    default, a ticket or an id.
 *  - **Parsing is all-or-nothing.** One unreadable block and nothing at all is
 *    appended. A per-block skip would record eleven answers and silently drop
 *    the twelfth, and the operator would never learn which.
 *  - **Decision before gate.** A crash between the two leaves a visible orphan
 *    decision, which is re-appliable; the reverse leaves a closed question
 *    whose answer was never written down, which is silent loss.
 *
 * It discovers nothing of its own: initiatives come from `board.mjs`, appends
 * go through `journal.mjs`, re-rendering through `project.mjs` and
 * `board.mjs`, liveness and the resume argv from `overnight.mjs`.
 *
 * `ANSWERS.md` is GENERATED and then HAND-EDITED, so it is deliberately NOT in
 * the byte-exact `--check` set: byte-equality is not a property a file the
 * operator types into can have.
 *
 * CLI:
 *   node answer.mjs render [--dir <.tyran>]
 *   node answer.mjs apply  [--dir <.tyran>] [--dry-run] [--resume]
 * Exit: 0 ok · 1 nothing is waiting on you · 2 usage, IO, or a sheet that did
 *       not parse
 */
import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, realpathSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { readInitiativeBoards, renderAll } from './board.mjs';
import { append, CAPPED_DATA_KEYS } from './journal.mjs';
import { formatCodePoint, invisibleProblem } from './invisible.mjs';
import { pidAlive, resumeArgv, SESSION_ID_RE } from './overnight.mjs';
import { inlinePlain, naturalCompare, projectFile, writeAllAtomic, writeAtomic } from './project.mjs';

/** The sheet, and the session record `apply --resume` reads. Both under
 * `state/`, which is already the AUTO policy class on every install. */
export const ANSWERS_FILE = 'ANSWERS.md';
export const CONDUCTOR_FILE = 'conductor.json';

/** The answer's ceiling is the journal's, imported rather than restated: a
 * pre-flight that disagreed with `append` would refuse the 9th answer of a
 * sitting after writing the 8th. */
export const MAX_ANSWER = CAPPED_DATA_KEYS.answer;

/** Longest answer excerpt in the report line. */
const REPORT_EXCERPT = 60;

/**
 * A block opens on this and nothing else. `$1` is the ask id (the gate kind),
 * `$2` is the initiative directory; the rest of the line is decoration.
 */
export const BLOCK_RE = /^## (Q-\d+) · (\S+)/;

/**
 * An ask's identity across initiatives. Ask ids are minted per journal, so
 * `Q-1` in `payments` and `Q-1` in `docs-site` are two different questions and
 * both must be answerable in one sitting.
 */
const keyOf = (init, kind) => `${init} :: ${kind}`;

const GENERATED_HEADER = `<!-- GENERATED by tyran scripts/answer.mjs — the \`answer:\` lines are the only thing you edit.
     When you are done:  node scripts/answer.mjs apply --dir .tyran

       blank    accept the recorded default, verbatim, as the decision
       -        leave it open; ask me again next time
       text     your answer, in your own words — everything down to the next \`## \` is it

     Questions with NO recorded default come first: those are the only ones where
     saying nothing has no safe outcome. Everything below is read back out of the
     journal when you apply, so editing anything except an answer changes nothing. -->
`;

class UsageError extends Error {}
class IOError extends Error {}

// ------------------------------------------------------------- discovery

/**
 * Every open ask, across every initiative, with the journal that owns it.
 *
 * The queue is `boardOf`'s, not a second derivation: an ask is an open gate
 * whose result matches the board's waiting rule, and this file must close
 * exactly what the board shows.
 */
export function openAsks(tyranDir) {
  const { initiatives, errors } = readInitiativeBoards(tyranDir);
  const asks = [];
  for (const { name, journal, board } of initiatives) {
    for (const ask of board.asks) asks.push({ ...ask, init: name, journal });
  }
  // `inits` is every initiative that EXISTS, not every one that still has a
  // question open: "payments has no open ask any more" and "there is no
  // payments" send the operator to opposite fixes, and the second sitting on
  // an already-applied sheet hits exactly that fork.
  return { asks: sortAsks(asks), inits: initiatives.map((i) => i.name), errors };
}

/**
 * No recorded default FIRST — those are the only questions where saying
 * nothing has no safe outcome. Then oldest first: a question that has stood
 * for four days is the one costing an initiative its progress. The last two
 * keys make the order total, so the sheet is stable across renders.
 */
export function sortAsks(asks) {
  return [...asks].sort(
    (a, b) =>
      Number(a.default != null) - Number(b.default != null) ||
      String(a.since ?? '').localeCompare(String(b.since ?? '')) ||
      naturalCompare(a.init, b.init) ||
      naturalCompare(a.kind, b.kind),
  );
}

// --------------------------------------------------------------- render

/**
 * The sheet. Every journal-derived value goes through `inlinePlain`, which is
 * the repo's one answer to "is this safe to show a human": it escapes
 * invisibles and folds the value onto ONE line. The folding is load-bearing
 * here and not merely cosmetic — a question carrying a newline plus
 * `## Q-99 · other` would otherwise open a second parseable block inside its
 * own sheet, and an agent would be writing the operator's ballot.
 */
export function renderSheet(asks) {
  const parts = [GENERATED_HEADER, '\n', `# ${asks.length} question${asks.length === 1 ? '' : 's'} waiting on you\n`];
  for (const a of asks) {
    parts.push(`\n## ${a.kind} · ${inlinePlain(a.init)}${a.default == null ? ' · no default recorded' : ''}\n`);
    parts.push(`${inlinePlain(a.question ?? '(no question recorded)')}\n`);
    if (a.recommendation != null) parts.push(`- recommendation: ${inlinePlain(a.recommendation)}\n`);
    if (a.default != null) parts.push(`- default: ${inlinePlain(a.default)}\n`);
    if (a.ticket != null) parts.push(`- ticket: ${inlinePlain(a.ticket)}\n`);
    parts.push(`- since: ${inlinePlain(a.since)}\n`);
    parts.push('answer:\n');
  }
  return parts.join('');
}

// ---------------------------------------------------------------- parse

/**
 * The grammar, deliberately dumber than YAML: one heading regex, one
 * `answer:` line, everything else ignored.
 *
 * Returns `{ blocks, errors }`. A non-empty `errors` means NOTHING is
 * appended — the caller must not apply a subset. A `## ` line that does not
 * parse is an error rather than ignored context: a mistyped heading is exactly
 * how a sitting would half-apply, and the operator would have no way to see
 * which answer went missing.
 */
export function parseSheet(text) {
  const lines = String(text).split('\n');
  const blocks = [];
  const errors = [];
  const seen = new Map();
  let current = null;

  const close = () => {
    if (current === null) return;
    if (current.answerLine === null) {
      errors.push(
        `line ${current.line}: block "${current.kind} · ${current.init}" has no \`answer:\` line — ` +
          'every block needs one, even when the answer is blank',
      );
    } else {
      blocks.push({
        kind: current.kind,
        init: current.init,
        line: current.line,
        answerLine: current.answerLine,
        answer: current.parts.join('\n').trim(),
      });
    }
    current = null;
  };

  lines.forEach((line, i) => {
    const number = i + 1;
    if (line.startsWith('## ')) {
      close();
      const m = BLOCK_RE.exec(line);
      if (m === null) {
        errors.push(
          `line ${number}: heading is not \`## Q-<n> · <initiative>\` — ` +
            'regenerate the sheet with: node scripts/answer.mjs render',
        );
        return;
      }
      const key = keyOf(m[2], m[1]);
      const first = seen.get(key);
      if (first !== undefined) {
        errors.push(`line ${number}: ${m[1]} · ${m[2]} appears twice (first at line ${first}) — which one is your answer?`);
        return;
      }
      seen.set(key, number);
      current = { kind: m[1], init: m[2], line: number, answerLine: null, parts: [] };
      return;
    }
    if (current === null) return; // everything before the first block is context
    if (current.answerLine === null) {
      if (/^answer:/.test(line)) {
        current.answerLine = number;
        current.parts.push(line.slice('answer:'.length));
      }
      return; // any other line inside a block is context
    }
    current.parts.push(line);
  });
  close();
  return { blocks, errors };
}

/**
 * What one answer means. `-` is the sentinel for "ask me again"; blank takes
 * the recorded default; blank with no default recorded leaves the question
 * open, because there is nothing to record.
 */
export function classify(answer, ask) {
  if (answer === '-') return { mode: 'open', why: 'you typed "-"' };
  if (answer === '') {
    if (ask.default == null) return { mode: 'open', why: 'blank, and no default is recorded' };
    return { mode: 'default', text: String(ask.default) };
  }
  return { mode: 'answered', text: answer };
}

/** An answer that `append` would refuse, checked BEFORE the first append so a
 * sitting cannot half-apply. LF is fine; bidi and zero-width are not. */
export function answerProblem(answer) {
  const cps = Array.from(answer);
  if (cps.length > MAX_ANSWER) {
    return `is ${cps.length} codepoints (cap ${MAX_ANSWER}) — shorten it, or put the long form in NOTES.md and reference it`;
  }
  let offset = 0;
  for (const ch of cps) {
    const cp = ch.codePointAt(0);
    const problem = invisibleProblem(cp);
    if (problem !== null) return `carries ${formatCodePoint(cp)} at codepoint offset ${offset} (${problem})`;
    offset += 1;
  }
  return null;
}

// ---------------------------------------------------------------- apply

/**
 * The two events one answered ask produces, in the order they must be
 * written. Pure, so the ordering guarantee is testable without a filesystem.
 *
 * `decision.text` carries the `Q-<n>: ` prefix because `STATE.md`'s decisions
 * table has no ask column — without the prefix the decision is unfindable
 * from the question. `answer_mode` records whether the operator typed it or
 * accepted the recorded default: a default accepted is still a decision.
 *
 * `ticket` comes from the ASK, which came from the journal. Nothing here may
 * come from the sheet.
 */
export function eventsFor(ask, verdict, decisionId = null) {
  const decision = {
    ev: 'decision',
    init: ask.init,
    actor: 'operator',
    data: {
      text: `${ask.kind}: ${verdict.mode === 'default' ? '(default accepted) ' : ''}${verdict.text}`,
      ask: ask.kind,
      ...(ask.ticket != null ? { ticket: String(ask.ticket) } : {}),
    },
  };
  const gate = {
    ev: 'gate',
    init: ask.init,
    actor: 'operator',
    data: {
      kind: ask.kind,
      result: 'answered',
      ...(ask.ticket != null ? { ticket: String(ask.ticket) } : {}),
      answer: verdict.text,
      answer_mode: verdict.mode === 'default' ? 'default' : 'operator',
      decision: decisionId,
      via: ANSWERS_FILE,
    },
  };
  return { decision, gate };
}

/** The sheet's blocks, matched against the journal's open asks. Every
 * mismatch is collected, so one run names every problem at once. */
function resolveBlocks(blocks, asks, initNames) {
  const index = new Map(asks.map((a) => [keyOf(a.init, a.kind), a]));
  const inits = new Set(initNames);
  const errors = [];
  const resolved = [];
  for (const block of blocks) {
    const ask = index.get(keyOf(block.init, block.kind));
    if (ask === undefined) {
      errors.push(
        inits.has(block.init)
          ? `line ${block.line}: ${block.kind} is not an open ask in "${inlinePlain(block.init)}" — it was answered ` +
            'or never existed. Re-render the sheet: node scripts/answer.mjs render'
          : `line ${block.line}: "${inlinePlain(block.init)}" is not an initiative with an open ask under .tyran/state/`,
      );
      continue;
    }
    const problem = answerProblem(block.answer);
    if (problem !== null) {
      errors.push(`line ${block.answerLine}: the answer to ${block.kind} ${problem}`);
      continue;
    }
    resolved.push({ ask, block, verdict: classify(block.answer, ask) });
  }
  return { resolved, errors };
}

/**
 * Fold the sheet back into the journals. Appends nothing when anything at all
 * is wrong, and nothing at all when `dryRun` is set.
 */
export function applySheet(tyranDir, sheetText, { dryRun = false } = {}) {
  const { asks, inits, errors: readErrors } = openAsks(tyranDir);
  if (asks.length === 0) return { ok: false, empty: true, errors: [], results: [], readErrors };

  const parsed = parseSheet(sheetText);
  if (parsed.blocks.length === 0 && parsed.errors.length === 0) {
    return {
      ok: false,
      errors: ['no `## Q-<n> · <initiative>` block in the sheet — regenerate it: node scripts/answer.mjs render'],
      results: [],
      open: asks.length,
      readErrors,
    };
  }
  const matched = resolveBlocks(parsed.blocks, asks, inits);
  const errors = [...parsed.errors, ...matched.errors];
  if (errors.length > 0) return { ok: false, errors, results: [], open: asks.length, readErrors };

  const results = [];
  const touched = new Map();
  for (const { ask, verdict } of matched.resolved) {
    if (verdict.mode === 'open' || dryRun) {
      results.push({ ask, verdict, decision: null });
      continue;
    }
    // Decision FIRST, and its id is issued by `append` under the journal's own
    // write lock — computing one out here would be the race that lock closes.
    const written = append(ask.journal, eventsFor(ask, verdict).decision);
    const id = written.data.id;
    append(ask.journal, eventsFor(ask, verdict, id).gate);
    touched.set(ask.init, ask.journal);
    results.push({ ask, verdict, decision: id });
  }
  return { ok: true, errors: [], results, touched, open: asks.length, dryRun, readErrors };
}

/** Re-render every touched initiative AND the cross board. A board left stale
 * is a board that still shows a question that has been answered. */
export function reRender(tyranDir, touched) {
  const written = [];
  for (const [name, journal] of [...touched].sort((a, b) => naturalCompare(a[0], b[0]))) {
    const { files } = projectFile(journal);
    const dir = dirname(journal);
    writeAllAtomic(Object.entries(files).map(([file, content]) => [join(dir, file), content]));
    written.push({ dir, files: Object.keys(files), init: name });
  }
  const cross = renderAll(tyranDir);
  const stateDir = join(tyranDir, 'state');
  writeAllAtomic(Object.entries(cross.files).map(([file, content]) => [join(stateDir, file), content]));
  written.push({ dir: stateDir, files: Object.keys(cross.files), init: null });
  return written;
}

// ----------------------------------------------------------- the conductor

/** The session record the SessionStart probe writes. Garbage reads as absent. */
export function readConductor(tyranDir) {
  try {
    const path = join(tyranDir, 'state', CONDUCTOR_FILE);
    if (!existsSync(path) || statSync(path).size > 64 * 1024) return null;
    const doc = JSON.parse(readFileSync(path, 'utf8'));
    return doc !== null && typeof doc === 'object' && !Array.isArray(doc) ? doc : null;
  } catch {
    return null;
  }
}

/**
 * What to say — and whether to spawn — about the session that will act on
 * these answers. A LIVE conductor is never resumed: two conductors on one
 * journal is a hazard this repo has already paid for once, and the live one
 * picks the answers up on its next loop anyway.
 */
export function resumePlan(conductor, { resume = false } = {}) {
  const sessionId = typeof conductor?.session_id === 'string' ? conductor.session_id : null;
  if (conductor !== null && pidAlive(conductor.pid)) return { action: 'live', pid: conductor.pid };
  if (sessionId === null || !SESSION_ID_RE.test(sessionId)) return { action: 'none' };
  return { action: resume ? 'spawn' : 'offer', sessionId };
}

// --------------------------------------------------------------- reporting

function excerpt(text) {
  const s = inlinePlain(text);
  const cps = Array.from(s);
  return cps.length > REPORT_EXCERPT ? cps.slice(0, REPORT_EXCERPT - 1).join('') + '…' : s;
}

export function reportLines(result) {
  const counts = { answered: 0, default: 0, open: 0 };
  for (const r of result.results) counts[r.verdict.mode] += 1;
  const lines = [
    `answer: ${result.open} open · ${counts.answered} answered · ${counts.default} defaulted · ${counts.open} left open` +
      (result.dryRun ? '  (--dry-run: nothing was appended)' : ''),
    '',
  ];
  const width = (pick) => Math.max(0, ...result.results.map((r) => inlinePlain(pick(r)).length));
  const kindWidth = width((r) => r.ask.kind);
  const initWidth = width((r) => r.ask.init);
  for (const r of result.results) {
    const verdict = r.verdict.mode === 'open' ? 'left open' : r.verdict.mode === 'default' ? 'default  ' : 'answered ';
    const tail =
      r.verdict.mode === 'open'
        ? `(${r.verdict.why})`
        : `"${excerpt(r.verdict.text)}"${r.decision === null ? '' : `   ${r.decision}`}`;
    lines.push(
      `  ${inlinePlain(r.ask.kind).padEnd(kindWidth)}  ${inlinePlain(r.ask.init).padEnd(initWidth)}  ${verdict}  ${tail}`,
    );
  }
  return lines;
}

function conductorLines(plan, answered) {
  if (plan.action === 'live') {
    return [`your conductor session is live (pid ${plan.pid}) — it will pick these up on its next loop.`];
  }
  if (plan.action === 'none') {
    return [
      'no conductor session id is recorded in .tyran/state/conductor.json.',
      '  Start one and it will read the answers out of the journal: /tyran',
    ];
  }
  return [
    'your conductor session is not running. To put the swarm back on it:',
    `  claude --resume ${plan.sessionId} "Answers landed for ${answered.join(', ')}"`,
    '  (or re-run apply with --resume and this command will do it)',
  ];
}

// ------------------------------------------------------------------- CLI

const BOOLEAN_FLAGS = ['dry-run', 'resume'];
const VALUE_FLAGS = ['dir'];

export function parseArgs(argv) {
  const flags = { dir: '.tyran' };
  const rest = [];
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (!arg.startsWith('--')) {
      rest.push(arg);
      continue;
    }
    const name = arg.slice(2);
    if (BOOLEAN_FLAGS.includes(name)) flags[name] = true;
    else if (VALUE_FLAGS.includes(name)) {
      const value = argv[i + 1];
      if (value === undefined || value.startsWith('--')) throw new UsageError(`flag --${name} needs a value`);
      flags[name] = value;
      i += 1;
    } else throw new UsageError(`unknown flag --${name}`);
  }
  if (rest.length > 1) throw new UsageError(`unexpected extra argument "${rest[1]}"`);
  return { verb: rest[0] ?? null, flags };
}

const USAGE =
  'usage: answer.mjs render [--dir <.tyran>]\n' +
  '       answer.mjs apply  [--dir <.tyran>] [--dry-run] [--resume]';

function doRender(tyranDir, sheetPath) {
  const { asks, errors } = openAsks(tyranDir);
  for (const e of errors) console.error(`answer: unreadable initiative ${inlinePlain(e.name)}: ${inlinePlain(e.error)}`);
  if (asks.length === 0) {
    console.error('answer: nothing is waiting on you');
    process.exit(1);
  }
  mkdirSync(dirname(sheetPath), { recursive: true });
  writeAtomic(sheetPath, renderSheet(asks));
  console.log(`answer: wrote ${sheetPath} — ${asks.length} question(s) waiting on you`);
  console.log(`  fill the \`answer:\` lines, then: node scripts/answer.mjs apply --dir ${tyranDir}`);
  const noDefault = asks.filter((a) => a.default == null).length;
  if (noDefault > 0) {
    console.log(`  ${noDefault} of them have no recorded default and come first — blank leaves those open.`);
  }
}

function doApply(tyranDir, sheetPath, flags) {
  if (!existsSync(sheetPath)) {
    throw new IOError(`no sheet at ${sheetPath} — write one first: node scripts/answer.mjs render --dir ${tyranDir}`);
  }
  const result = applySheet(tyranDir, readFileSync(sheetPath, 'utf8'), { dryRun: flags['dry-run'] === true });
  for (const e of result.readErrors ?? []) {
    console.error(`answer: unreadable initiative ${inlinePlain(e.name)}: ${inlinePlain(e.error)}`);
  }
  if (result.empty) {
    console.error('answer: nothing is waiting on you');
    process.exit(1);
  }
  if (!result.ok) {
    for (const e of result.errors) console.error(`answer: ${sheetPath}: ${e}`);
    console.error(
      `answer: nothing was appended — the sheet is applied whole or not at all (${result.errors.length} problem(s))`,
    );
    process.exit(2);
  }

  const lines = reportLines(result);
  const closed = result.results.filter((r) => r.verdict.mode !== 'open');
  const acted = !result.dryRun && closed.length > 0;
  if (acted) {
    lines.push('', 're-rendered');
    for (const { dir, files } of reRender(tyranDir, result.touched)) lines.push(`  ${dir}/{${files.join(',')}}`);
  }
  const plan = resumePlan(readConductor(tyranDir), { resume: flags.resume === true });
  const answered = closed.map((r) => r.ask.kind);
  if (acted) lines.push('', ...conductorLines(plan, answered));
  console.log(lines.join('\n'));

  if (acted && plan.action === 'spawn') {
    // Never through a shell: the argv is the whole command, and the session id
    // was shape-checked before it became one of its elements.
    const argv = resumeArgv(plan.sessionId, `Answers landed for ${answered.join(', ')} — read the journal tail and continue.`);
    const child = spawn(argv[0], argv.slice(1), {
      cwd: dirname(resolve(tyranDir)),
      detached: true,
      stdio: 'ignore',
      shell: false,
    });
    child.on('error', (err) => console.error(`answer: could not resume the session: ${err.message}`));
    child.unref();
    console.log(`answer: resumed session ${plan.sessionId} (pid ${child.pid ?? '?'})`);
  }
}

function main() {
  let parsed;
  try {
    parsed = parseArgs(process.argv.slice(2));
  } catch (err) {
    console.error(`answer: ${err.message}`);
    console.error(USAGE);
    process.exit(2);
  }
  const tyranDir = resolve(parsed.flags.dir);
  const sheetPath = join(tyranDir, 'state', ANSWERS_FILE);
  try {
    if (!existsSync(tyranDir)) throw new IOError(`no such directory ${tyranDir}`);
    if (parsed.verb === 'render') return doRender(tyranDir, sheetPath);
    if (parsed.verb === 'apply') return doApply(tyranDir, sheetPath, parsed.flags);
    // A verb-less invocation NEVER guesses. This command writes to the ledger,
    // and an invocation that sometimes writes and sometimes does not is what a
    // tired operator gets wrong at 23:00.
    console.error(USAGE);
    console.error(`answer: ${openAsks(tyranDir).asks.length} question(s) waiting on you — say \`render\` or \`apply\``);
    process.exit(2);
  } catch (err) {
    console.error(`answer: ${err.message}`);
    if (err instanceof UsageError) console.error(USAGE);
    process.exit(2);
  }
}

/** See journal.mjs — both sides canonicalized, or a symlinked path no-ops. */
function canonicalPath(path) {
  const abs = resolve(path);
  try {
    return realpathSync(abs);
  } catch {
    return abs;
  }
}

function isMainModule(moduleUrl) {
  if (!process.argv[1]) return false;
  return canonicalPath(process.argv[1]) === canonicalPath(fileURLToPath(moduleUrl));
}

if (isMainModule(import.meta.url)) main();
