#!/usr/bin/env node
/**
 * board — the cross-initiative kanban view.
 *
 * `project.mjs` renders one initiative's BOARD.md/board.json next to its
 * journal; this tool folds EVERY journal under `.tyran/state/` into one
 * board — the answer to "what is going on" that previously required opening
 * one file per initiative (measured install: 31). Three artefacts, all
 * GENERATED, all under `state/` where the AUTO policy class already covers
 * them:
 *
 *   .tyran/state/BOARD.md     the agent/git surface
 *   .tyran/state/board.json   schema 1, for tooling
 *   .tyran/state/board.html   the page an operator stares at (board-html.mjs)
 *
 * Determinism carries over from the projection layer: no clock (the page
 * shows the newest event ts as "as of"), byte-identical reruns, invisibles
 * escaped never removed, `--check` compares bytes. An unreadable journal is a
 * visible error entry, never a crash — a board that omits a broken
 * initiative reads as "all is well" exactly when it is not.
 *
 * CLI:
 *   node board.mjs [--dir <.tyran>] [--check]
 *                  [--serve|--detach [--port <n>] [--write] [--open] [--transcripts <dir>]...]
 *                  [--status] [--stop]
 * Exit: 0 ok · 1 drift (--check), or no server (--status/--stop) · 2 usage/IO
 *
 * `--serve` holds the terminal; `--detach` starts the same server, waits only
 * until it answers, and returns. Anything that is not a human with a spare
 * terminal wants the second one — see board-daemon.mjs.
 */
import { existsSync, readdirSync, statSync, readFileSync } from 'node:fs';
import { createServer } from 'node:http';
import { spawn as spawnProcess } from 'node:child_process';
import { basename, join, resolve } from 'node:path';
import { realpathSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { isClosingPhase, readJournal } from './journal.mjs';
import {
  BOARD_FILE,
  BOARD_JSON_FILE,
  LANES,
  boardOf,
  checkFile,
  fold,
  inline,
  warnings,
  writeAllAtomic,
  writeAtomic,
} from './project.mjs';
import { escapeInvisible, jsonEscapeInvisible } from './invisible.mjs';
import { renderBoardError, renderBoardHtml } from './board-html.mjs';
import { COST_SCHEMA, WINDOWS, costJson, costReport } from './cost.mjs';
import { SettingsError, applyPolicyClass, applySetting, readSettings } from './settings.mjs';
import { checkStopAt } from './stop-check.mjs';
import { runState } from './overnight.mjs';
import { answerOne, answerProblem, classify, openAsks, partitionAsks, reRender, sortAsks } from './answer.mjs';
import { wantsHelp } from './cli-args.mjs';
import {
  HEALTH_ROUTE,
  PORT_SEARCH_SPAN,
  findLiveServer,
  removeServerRecord,
  startDetached,
  stopServer,
  urlFor,
  writeServerRecord,
} from './board-daemon.mjs';

export const BOARD_HTML_FILE = 'board.html';

/** How often a served board checks that it still has a directory to serve. */
export const DIR_WATCHDOG_MS = 60_000;

/**
 * Open the served board in the operator's browser.
 *
 * The board was a URL printed to a terminal that nothing ever opened, and for
 * the people this matters most to that is several steps — keep this window
 * running, now type that address somewhere else — each one a place to stop.
 * The dashboard is where Tyran becomes legible, and it was the one thing
 * installation never actually reached.
 *
 * Best-effort and never fatal: a failure here leaves the server running and
 * the URL printed, which is exactly where things were before. Headless
 * machines, SSH sessions and locked-down desktops all land in that branch and
 * none of them is an error worth taking a working server down for.
 *
 * The argument vector is fixed and the URL is the only variable — it is built
 * from a port this process is already listening on, never from user text —
 * and `shell: false` (the default) means nothing here reaches a shell.
 */
export function openInBrowser(url, { platform = process.platform, spawn = spawnProcess } = {}) {
  const [command, args] =
    platform === 'darwin' ? ['open', [url]]
      : platform === 'win32' ? ['cmd', ['/c', 'start', '', url]]
        : ['xdg-open', [url]];
  try {
    const child = spawn(command, args, { stdio: 'ignore', detached: true });
    // A missing `open`/`xdg-open` arrives as an async error event, not a
    // throw, so the catch below would never see it — and an unhandled one
    // would take the server down, which is the opposite of best-effort.
    child.on?.('error', () => { /* no browser here; the printed URL still works */ });
    child.unref?.();
    return true;
  } catch {
    return false;
  }
}

/** Same ceiling as the evidence gate's journal locator — a deliberate
 * duplicate: scripts must not import from hook files (direction is
 * hooks -> scripts), and the constant is one number with one meaning. */
export const MAX_INITIATIVES = 64;

const GENERATED_MD_HEADER =
  '<!-- GENERATED by tyran scripts/board.mjs - DO NOT EDIT. Source of truth: the journals under .tyran/state/ -->\n' +
  '<!-- Regenerate: node scripts/board.mjs --dir <.tyran> -->\n';

class UsageError extends Error {}

/** Every initiative folded to its board; failures become visible entries. */
export function readInitiativeBoards(tyranDir) {
  const stateDir = join(tyranDir, 'state');
  let names;
  try {
    names = readdirSync(stateDir).sort();
  } catch (err) {
    // ENOENT is the legitimate fresh-repo case: setup has run, no initiative
    // exists yet, and an empty board is the right answer. Anything else —
    // EACCES, ENOTDIR, EIO — means we cannot TELL whether there is work here,
    // and returning "no initiatives" for that is the board saying all is well
    // about a directory it could not open. It is also what `--dir` pointed at
    // the repo root instead of at `.tyran` looks like.
    if (err?.code === 'ENOENT') return { initiatives: [], errors: [] };
    return { initiatives: [], errors: [{ name: 'state', error: `${err?.code ?? 'unreadable'} reading ${join(basename(resolve(tyranDir)), 'state')}` }] };
  }
  const dirs = names.filter((name) => {
    try {
      return statSync(join(stateDir, name)).isDirectory();
    } catch {
      return false;
    }
  });
  if (dirs.length > MAX_INITIATIVES) {
    throw new UsageError(
      `${dirs.length} initiative directories under ${stateDir} — the ceiling is ${MAX_INITIATIVES}. ` +
        'Archive closed initiatives out of state/ before rendering a board over them.',
    );
  }
  const initiatives = [];
  const errors = [];
  const warned = [];
  for (const name of dirs) {
    const journal = join(stateDir, name, 'journal.jsonl');
    // "there is no journal here" and "I cannot tell whether there is a journal
    // here" are different facts, and `existsSync` returns false for both. An
    // initiative in an unreadable directory used to vanish from the board with
    // nothing said — the totals simply went down by one.
    try {
      statSync(journal);
    } catch (err) {
      if (err?.code === 'ENOENT') continue;
      errors.push({ name, error: `${err?.code ?? 'unreadable'} reading ${join('state', name, 'journal.jsonl')}` });
      continue;
    }
    try {
      const state = fold(readJournal(journal));
      // PARTIAL damage, which the guard below cannot see. That guard fires only
      // when NOTHING was readable; three good tickets plus one unparseable line
      // folds to a board with no errors on it and renders as an initiative in
      // perfect health. `warnings()` has produced exactly the right sentences
      // for this since the projection layer existed — the board simply never
      // asked for them. A page whose stated reason to exist is not saying "all
      // is well" when it is not cannot be silent about the damaged half.
      const flaws = warnings(state);
      if (flaws.length > 0) warned.push({ name, warnings: flaws });
      // `readJournal` does NOT throw on unparseable content — it returns zero
      // events and counts the damage — so the catch below never sees a corrupt
      // journal. Without this guard a damaged file renders as an initiative
      // with nothing wrong, which is the one output this board must never
      // produce. Same condition the CLI and the refresh probe refuse on.
      if (state.total === 0 && (state.corruptLines + state.malformed > 0 || state.truncatedTail)) {
        const damage = [
          state.corruptLines > 0 ? `${state.corruptLines} corrupt line(s)` : null,
          state.malformed > 0 ? `${state.malformed} non-object line(s)` : null,
          state.truncatedTail ? 'a truncated final line' : null,
        ].filter(Boolean).join(', ');
        errors.push({ name, error: `0 readable events and ${damage} — the journal is damaged` });
        continue;
      }
      // `journal` is returned, not re-derived by consumers: answer.mjs writes
      // to the file this function already located, so there is one rule for
      // where an initiative's journal lives (ADR-21).
      initiatives.push({ name, journal, state, board: boardOf(state), files: initiativeFiles(tyranDir, name) });
    } catch (err) {
      // The CODE and a repo-relative path, never the raw message. A Node fs
      // error carries the absolute path, which means a home directory and a
      // username — and this string is written into `board.json`, a committed
      // artefact compared byte for byte, so it also made `--check` fail on any
      // other machine.
      errors.push({
        name,
        error: err?.code
          ? `${err.code} reading ${join('state', name, 'journal.jsonl')}`
          : String(err?.message ?? err),
      });
    }
  }
  return { initiatives, errors, warned };
}

/**
 * The files an initiative ACTUALLY has beside its journal.
 *
 * Named set, `existsSync`, no creation and no guessing: the operator asked to
 * reach an agent's plan from the board and asked in the same breath that
 * nothing be created to satisfy the link. A listed file that is not there is
 * the same lie as a missing one, in the other direction.
 *
 * The recorded path is REPO-RELATIVE, and that is not cosmetic: `board.json`
 * is a committed, byte-compared artefact, so an absolute path would make two
 * clones of one journal disagree and fail `--check` on a machine whose home
 * directory is spelled differently. It is the same reason spend is served
 * rather than embedded. Relative is also the more useful form — it is what
 * the reader pastes, from the repo root, into an editor.
 *
 * These five ARE served, since 0.1.42, by `readInitiativeDoc` below — and the
 * promise this comment has always made survives it intact: `--serve` still
 * derives a filesystem path from no URL at all. The route takes a NAME and
 * matches it against the list above, exactly as the one route that writes —
 * Settings, behind `--write` — reaches two fixed files named in `settings.mjs`
 * by taking a KEY from the request and never a path.
 */
export const INITIATIVE_FILES = Object.freeze(['PLAN.md', 'NOTES.md', 'RETRO.md', 'STATE.md', 'PROGRESS.md']);

export function initiativeFiles(tyranDir, name) {
  const dir = join(tyranDir, 'state', name);
  const shown = join(basename(resolve(tyranDir)), 'state', name);
  return INITIATIVE_FILES.filter((file) => existsSync(join(dir, file))).map((file) => ({
    name: file,
    path: join(shown, file),
  }));
}

/**
 * How much of one document travels to the page, in CODEPOINTS.
 *
 * Codepoints and not bytes because the cut is applied to a decoded string:
 * slicing a UTF-8 buffer at a fixed offset lands inside a character often
 * enough, and hands the reader a replacement mark that was never in the file.
 *
 * A cap at all because this route reads whatever grew beside a journal, and a
 * NOTES.md three weeks into an initiative is not a thing to push through one
 * response. The panel says it was cut and names the path holding the rest.
 */
export const MAX_DOC_CHARS = 200_000;

/**
 * One initiative document, for the page's file viewer.
 *
 * TWO CLOSED SETS AND NO PATH ARITHMETIC — that is the whole security story,
 * and it is why the comment on `initiativeFiles` above ("nothing is served
 * from here") could be revisited rather than merely broken. `name` must equal
 * a member of `INITIATIVE_FILES`, and `init` must equal a directory that
 * `state/` actually contains, compared against the very listing the board
 * folds. Nothing from the request is joined into a path until it has matched
 * one of those two lists, so `..`, an absolute path, a NUL and a name that
 * differs only by case are all rejected by never becoming candidates — not by
 * a filter someone has to keep ahead of the next trick.
 *
 * The text is invisible-ESCAPED, like every other journal-side value that
 * reaches a human (invisible.mjs): these documents are written by agents out
 * of reports about foreign repositories, and the reader is looking at them on
 * a page instead of in the editor that would have shown the same bytes.
 *
 * Nothing is echoed back on a refusal. A message naming what was asked for is
 * a message carrying attacker-chosen text into the operator's browser, and
 * naming the five files it DOES serve is more useful anyway.
 */
export function readInitiativeDoc(tyranDir, init, name) {
  if (!INITIATIVE_FILES.includes(name)) {
    return { ok: false, status: 400, error: `this board serves only: ${INITIATIVE_FILES.join(', ')}` };
  }
  const stateDir = join(tyranDir, 'state');
  let names;
  try {
    names = readdirSync(stateDir);
  } catch (err) {
    return { ok: false, status: 503, error: `${err?.code ?? 'unreadable'} reading the state directory` };
  }
  if (!names.includes(init)) {
    return { ok: false, status: 404, error: 'no initiative by that name in this board' };
  }
  const file = join(stateDir, init, name);
  let raw;
  try {
    raw = readFileSync(file, 'utf8');
  } catch (err) {
    // ENOENT here is ordinary: `initiativeFiles` listed what existed when the
    // page was rendered, and an initiative that has since been archived is a
    // fact to report rather than a failure.
    return {
      ok: false,
      status: err?.code === 'ENOENT' ? 404 : 503,
      error: err?.code === 'ENOENT'
        ? `${name} is not beside that journal — the board lists what exists when it renders, so reload it`
        : `${err?.code ?? 'unreadable'} reading ${name}`,
    };
  }
  const chars = [...raw];
  const truncated = chars.length > MAX_DOC_CHARS;
  return {
    ok: true,
    status: 200,
    schema: 1,
    init,
    name,
    // Repo-relative, the same form `initiativeFiles` records and for the same
    // reason: it is what the reader pastes into an editor, and it names no
    // home directory.
    path: join(basename(resolve(tyranDir)), 'state', init, name),
    truncated,
    chars: truncated ? MAX_DOC_CHARS : chars.length,
    text: escapeInvisible(truncated ? chars.slice(0, MAX_DOC_CHARS).join('') : raw),
  };
}

/** Pure merge of per-initiative boards into the one payload. */
/**
 * How many logged errors travel in the payload.
 *
 * `board.json` is committed and compared byte for byte, so an unbounded list
 * would grow the artefact with every bad night. Newest first and a count for
 * the rest: the board's job is to say something is wrong, not to be the log.
 */
export const MAX_LOGGED_ERRORS = 20;

export function crossBoard({ initiatives, errors, warned = [], stop = null }) {
  const asks = [];
  const summaries = [];
  const agents = [];
  const paused = [];
  const logged = [];
  const files = {};
  const lanes = Object.fromEntries(LANES.map((lane) => [lane, []]));
  let merged = 0;
  let tickets = 0;
  let asOf = null;

  for (const { name, state, board, files: docs } of initiatives) {
    merged += state.merged;
    tickets += state.ticketList.length;
    // Per-initiative, because one blended percentage over every initiative is
    // not a fact about any of them: an operator reading "50%" across four
    // slugs cannot tell which is nearly done from which has not started.
    //
    // The TITLE is the point of the row. `init.created` has carried a written
    // sentence all along — "Settings on the board: edit config and the
    // autonomy policy from the page" — and the board showed the directory
    // slug. `waiting` and `last_ts` are here rather than a computed idle time
    // because this payload is byte-compared under `--check` and reads no
    // clock; the page ages them, exactly as it already ages agents.
    summaries.push({
      name,
      title: typeof state.created?.data?.title === 'string' ? state.created.data.title : null,
      tickets: state.ticketList.length,
      merged: state.merged,
      percent: state.percent,
      waiting: board.asks.length,
      // A COUNT, and deliberately not the findings themselves. Measured across
      // 63 distinct real journals: 3 carry any finding at all, 49 in total,
      // and NOT ONE names a ticket — so they cannot enrich a card, which is
      // where a richer board would have put them. Their median claim is 429
      // characters, a paragraph rather than a label, and STATE.md already
      // renders the full seven-column table.
      //
      // So this is a pointer, not a copy: the research exists and the reader
      // is told where. Duplicating the prose here would be ADR-21's defect
      // and would cost ~600 B per finding in a byte-compared payload.
      // Guarded: `crossBoard` is exported and takes any folded state, and a
      // caller assembling one by hand need not have every collection. A
      // missing array must read as "none", never take the board down.
      findings: (state.findings ?? []).length,
      // FINISHED and ABANDONED read identically on a percentage bar, and they
      // are the opposite situation: one is work that ended, the other is work
      // that stopped. The board had no way to tell them apart — measured, it
      // is the same 63 journals where 43 sat on an unanswered question and 6
      // were genuinely done.
      //
      // A checkpoint whose phase is the reserved word `closed` is the ONLY
      // event that declares an initiative over (journal.mjs), which is already
      // what closes its still-open spawns — so this hangs on that same fact
      // rather than inventing a second rule for "finished" (ADR-21). The
      // TIMESTAMP, not a boolean: "closed 9 days ago" is the reading, and the
      // page ages it in the reader's browser like every other time here.
      //
      // `phase` travels beside it because an initiative that is NOT closed
      // still has its own word for where it is, and the per-initiative
      // board.json has carried that word all along while the cross board
      // showed a percentage and nothing else.
      //
      // NOT deployment: nothing in the closed event set records a deploy, so
      // the board must not imply one. This says the initiative was wound up.
      phase: state.checkpoint?.phase ?? null,
      closed: isClosingPhase(state.checkpoint?.phase) ? state.checkpoint.ts : null,
      last_ts: state.lastTs,
    });
    if (state.lastTs !== null && (asOf === null || state.lastTs > asOf)) asOf = state.lastTs;
    for (const a of board.asks) asks.push({ ...a, init: name });
    for (const a of board.agents) agents.push({ ...a, init: name });
    if (board.paused !== null) paused.push({ ...board.paused, init: name });
    if (docs !== undefined && docs.length > 0) files[name] = docs;
    // An `error` event with no ticket landed in STATE.md's Errors table and
    // nowhere else: the fold collects it, and the board that exists to say
    // "not all is well" carried neither `state.errors` nor the tickets an
    // error named that the journal has never seen. A whole class of agent
    // failure was invisible on the one screen meant to show it.
    for (const e of state.errors) {
      logged.push({
        init: name,
        class: e.class,
        detail: e.detail,
        ticket: e.ticket ?? null,
        ticket_unknown: e.ticket_unknown === true,
        ts: e.ts,
        actor: e.actor,
      });
    }
    for (const lane of LANES) {
      for (const card of board.lanes.get(lane)) lanes[lane].push({ ...card, init: name });
    }
  }
  // The SAME rule the answer sheet uses, imported rather than restated: the
  // sheet and the page are two renderings of one queue, and two orderings
  // would make an operator answer them in different sequences depending on
  // which surface they happened to open (ADR-21).
  const ordered = sortAsks(asks);
  asks.length = 0;
  asks.push(...ordered);
  // Stalest FIRST. Rendering agents in the order the journals happened to spawn
  // them puts the one that has said nothing for six hours anywhere at all,
  // including last — and the whole reason the strip carries a last-signal time
  // is that the silent agent is the one worth looking at. `last_signal` is an
  // ISO string from the journal, so ascending string order IS ascending time;
  // an agent with no signal at all sorts to the front, where it belongs.
  // Sorted on EVIDENCE where there is any, falling back to the signal. An
  // agent that has shown nothing for three hours belongs at the top even if it
  // has been saying "working" every four minutes the whole time — which is
  // exactly the case the old signal-only sort put last.
  agents.sort((a, b) =>
    String(a.last_evidence ?? a.since ?? '').localeCompare(String(b.last_evidence ?? b.since ?? '')));
  // Newest first: an error from four days ago is history, the one from ten
  // minutes ago is the reason you opened this page.
  logged.sort((a, b) => String(b.ts ?? '').localeCompare(String(a.ts ?? '')));

  return {
    schema: 1,
    as_of: asOf,
    totals: {
      initiatives: initiatives.length,
      agents: agents.length,
      // Of those, how many the journal has moved on without. `agents` counts
      // OPEN spawns, which is what it has always counted and what the strip
      // lists — but presenting that number as "running" made a week-old ghost
      // indistinguishable from an agent working right now, and an overnight
      // operator reads this tile before anything else on the page.
      agents_stale: agents.filter((a) => a.stale === true).length,
      merged,
      tickets,
      percent: tickets === 0 ? 0 : Math.round((merged / tickets) * 100),
      // Counted here rather than on the page, from BOTH sources of "a human is
      // needed": the lanes, and the agents. A ticket parked by a `ticket.status`
      // override leaves no card in `blocked` — the override is resolved before
      // the blockage in `boardOf` — so an agent could sit blocked on it while a
      // tile counting lanes alone read zero. It did.
      blocked: lanes.blocked.length + lanes['changes-requested'].length
        + agents.filter((a) => a.state === 'blocked').length,
    },
    // Committed repo state, so it belongs in the artefact rather than behind a
    // route: `.tyran/STOP` is identical in every clone, and `--check` stays
    // byte-exact. The machine-local half of "is this run supposed to be
    // running" — the pause marker, the resume watcher — is served instead,
    // for the same reason spend is.
    // `{stopped, reason}` and NOT the path `checkStopAt` also returns: an
    // absolute path in a committed, byte-compared artefact makes two clones of
    // one journal disagree on a machine whose home directory is spelled
    // differently. The same trap the initiative file list was caught in.
    stop: stop === null ? null : { stopped: stop.stopped, reason: stop.reason },
    paused,
    asks,
    // Ordered by directory name, like everything else here, so two renders of
    // one journal set are byte-identical. `totals.percent` blends these; the
    // rows are what let a reader see WHICH initiative it blends.
    initiatives: summaries,
    agents,
    files,
    lanes,
    // The key is `errors_logged`, NOT `errors`: `errors` on this payload
    // already means "this initiative's journal could not be read at all", and
    // one key with two meanings is the defect ADR-21 is named after.
    errors_logged: logged.slice(0, MAX_LOGGED_ERRORS),
    errors_logged_total: logged.length,
    errors,
    warned,
  };
}

export function crossJson(payload) {
  return jsonEscapeInvisible(JSON.stringify(payload, null, 2)) + '\n';
}

export function renderCrossMd(payload) {
  const parts = [GENERATED_MD_HEADER, '# BOARD — all initiatives\n\n'];
  const t = payload.totals;
  // "open", not "running": the headline used to assert that every open spawn
  // was live work, and the stale ones are named right after it rather than
  // being quietly dropped from the count (ADR-19 correction 1).
  parts.push(
    `**${t.agents} agent(s) open across ${t.initiatives} initiative(s)` +
      `${t.agents_stale > 0 ? `, ${t.agents_stale} stale` : ''} · ` +
      `${t.merged}/${t.tickets} tickets merged (${t.percent}%) · as of ${inline(payload.as_of)}**\n`,
  );
  // First, and above the pause: a STOP outranks everything. It is the one
  // state where a strip of silent agents is the system doing as it was told.
  if (payload.stop?.stopped === true) {
    parts.push(`\n**STOPPED** — an operator halted this repo: ${inline(payload.stop.reason)}\n`);
  }
  for (const p of payload.paused) {
    parts.push(`\n**PAUSED** — ${inline(p.init)}: gate ${inline(p.kind)} (${inline(p.result)}) since ${inline(p.since)}\n`);
  }
  for (const e of payload.errors) {
    parts.push(`\n**UNREADABLE** — ${inline(e.name)}: ${inline(e.error)}\n`);
  }
  for (const d of payload.warned ?? []) {
    for (const w of d.warnings) parts.push(`\n**WARNING** — ${inline(d.name)}: ${inline(w)}\n`);
  }
  for (const e of payload.errors_logged ?? []) {
    const what = `${inline(e.class ?? 'error')}${e.detail != null ? `: ${inline(e.detail)}` : ''}` +
      (e.ticket_unknown ? ` — it names ticket ${inline(e.ticket)}, which this journal has never declared` : '');
    parts.push(`\n**ERROR** — ${inline(e.init)}: ${what} (${inline(e.ts)})\n`);
  }
  const hidden = (payload.errors_logged_total ?? 0) - (payload.errors_logged ?? []).length;
  if (hidden > 0) parts.push(`\n**ERROR** — and ${hidden} older error(s); read the journals for the rest\n`);

  parts.push('\n## Waiting on you\n\n');
  if (payload.asks.length === 0) parts.push('_none — the agents have what they need_\n');
  for (const a of payload.asks) {
    parts.push(`- **${inline(a.question ?? `(no question recorded — gate ${a.kind})`)}**\n`);
    if (a.recommendation != null) parts.push(`  - recommendation: ${inline(a.recommendation)}\n`);
    if (a.default != null) parts.push(`  - default: ${inline(a.default)}\n`);
    if (a.blocks != null && a.blocks.count > 0) {
      parts.push(`  - blocks ${a.blocks.count} ticket(s): ${a.blocks.ids.map((id) => inline(id)).join(', ')}\n`);
    }
    parts.push(`  - ${inline(a.init)}${a.ticket != null ? ` · \`${inline(a.ticket)}\`` : ''} · since ${inline(a.since)}\n`);
  }

  parts.push('\n## Agents\n\n');
  if (payload.agents.length === 0) parts.push('_none running_\n');
  for (const a of payload.agents) {
    parts.push(
      `- \`${inline(a.agent)}\` (${inline(a.role)}) — ${inline(a.init)}` +
        `${a.ticket != null ? ` · \`${inline(a.ticket)}\`` : ''} · ${inline(a.state)}` +
        `${a.detail != null ? ` — ${inline(a.detail)}` : ''} · started ${inline(a.since)}` +
        `${a.last_signal != null ? ` · last signal ${inline(a.last_signal)}` : ''}` +
        `${a.next != null ? ` · next: ${inline(a.next)}` : ''}\n`,
    );
  }

  const withFiles = Object.keys(payload.files ?? {}).sort();
  if (withFiles.length > 0) {
    parts.push('\n## Files\n\n');
    for (const name of withFiles) {
      parts.push(`- ${inline(name)}: ${payload.files[name].map((f) => `\`${inline(f.name)}\``).join(', ')}\n`);
    }
  }

  for (const lane of LANES) {
    const cards = payload.lanes[lane];
    parts.push(`\n## ${lane} (${cards.length})\n\n`);
    if (cards.length === 0) {
      parts.push('_none_\n');
      continue;
    }
    for (const c of cards) {
      parts.push(
        `- \`${inline(c.id)}\`${c.title ? ` — ${inline(c.title)}` : ''} _(${inline(c.init)})_` +
          `${c.agents.length > 0 ? ` — ${inline(c.agents)}` : ''}` +
          `${c.annotation ? ` — ${inline(c.annotation)}` : ''}\n`,
      );
    }
  }
  return parts.join('');
}

export function renderAll(tyranDir) {
  const payload = crossBoard({
    ...readInitiativeBoards(tyranDir),
    // Named from the board's own directory rather than reconstructed from a
    // repo root: `--dir` need not be spelled `.tyran`.
    stop: checkStopAt(join(tyranDir, 'STOP')),
  });
  const json = crossJson(payload);
  return {
    payload,
    files: {
      [BOARD_FILE]: renderCrossMd(payload),
      [BOARD_JSON_FILE]: json,
      [BOARD_HTML_FILE]: renderBoardHtml(json.trimEnd()),
    },
  };
}

// ------------------------------------------------------- the write channel

/** A request body big enough for any setting and small enough to ignore. */
const MAX_BODY_BYTES = 64 * 1024;

/**
 * Read a JSON request body, or reject it.
 *
 * Three refusals, all deliberate. A body over the cap is dropped rather than
 * buffered, because this server has no reason to hold a megabyte of anything.
 * A body that is not `application/json` is refused BEFORE it is read — that
 * content type is what forces a browser to preflight a cross-origin POST, and
 * accepting `text/plain` here would hand back the exact hole the preflight
 * closes. And anything that is not a JSON object is refused, so a handler
 * never reasons about a string that happens to have a `.value`.
 */
function readJsonBody(req) {
  return new Promise((resolve_, reject) => {
    const type = String(req.headers['content-type'] ?? '').split(';')[0].trim().toLowerCase();
    if (type !== 'application/json') {
      reject(new SettingsError('this route takes application/json'));
      return;
    }
    let size = 0;
    const chunks = [];
    req.on('data', (chunk) => {
      size += chunk.length;
      if (size > MAX_BODY_BYTES) {
        // Reject, but do NOT destroy the socket: the route's 400 is written on
        // the next tick, and tearing the connection down first meant the
        // client saw a network error instead of the sentence explaining what
        // was wrong. Pausing stops us reading the rest without discarding the
        // channel the answer goes out on.
        req.pause();
        reject(new SettingsError(`request body is larger than ${MAX_BODY_BYTES} bytes`));
        return;
      }
      chunks.push(chunk);
    });
    req.on('error', (err) => reject(err));
    req.on('end', () => {
      let parsed;
      try {
        parsed = JSON.parse(Buffer.concat(chunks).toString('utf8'));
      } catch {
        reject(new SettingsError('request body is not JSON'));
        return;
      }
      if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
        reject(new SettingsError('request body must be a JSON object'));
        return;
      }
      resolve_(parsed);
    });
  });
}

/**
 * `Origin`, on top of the `Host` pin the whole server already carries.
 *
 * The two answer different questions and neither covers the other. `Host` says
 * which name the client dialled, which stops DNS rebinding. `Origin` says
 * which page is asking, which is the only thing that distinguishes the board's
 * own fetch from a POST issued by some other tab the operator has open. A
 * request with no `Origin` at all is allowed: that is `curl`, and a local
 * process that can reach loopback needs no browser's help — see the honest
 * statement of what this does and does not defend in `docs/board.md`.
 */
function originAllowed(req) {
  const origin = req.headers.origin;
  if (origin === undefined || origin === 'null') return true;
  try {
    const { hostname } = new URL(String(origin));
    return hostname === '127.0.0.1' || hostname === 'localhost' || hostname === '[::1]' || hostname === '::1';
  } catch {
    return false;
  }
}

const sendJson = (res, status, body) => {
  res.writeHead(status, { 'content-type': 'application/json; charset=utf-8' });
  res.end(JSON.stringify(body) + '\n');
};

/**
 * Answer one open question, from the page instead of from a terminal.
 *
 * The request supplies exactly two things: WHICH ask, and the operator's own
 * words. Everything else — the question, the recorded default, the ticket, the
 * gate id — is read back out of the journal, which is the same guarantee
 * `answer apply` makes about its sheet: nothing you type can change what was
 * asked. The append itself is `answerOne`, unchanged and unwrapped, so the
 * lock, the re-check and the decision-before-gate ordering are the ones the
 * CLI already uses.
 */
function handleAnswer(dir, body) {
  const kind = String(body.kind ?? '');
  const init = String(body.init ?? '');
  const text = typeof body.answer === 'string' ? body.answer : '';

  const { asks } = openAsks(dir);
  const { answerable } = partitionAsks(asks);
  const ask = answerable.find((a) => a.kind === kind && a.init === init);
  if (ask === undefined) {
    throw new SettingsError(
      `no open question "${kind}" in "${init}" — it may have been answered in a terminal since this page loaded. Reload.`,
    );
  }
  const trimmed = text.trim();
  const problem = answerProblem(trimmed);
  if (problem !== null) throw new SettingsError(`that answer ${problem}`);

  const verdict = classify(trimmed, ask);
  if (verdict.mode === 'open') throw new SettingsError(verdict.why ?? 'nothing to record');
  const outcome = answerOne(ask, verdict);
  if (outcome.skipped !== undefined) throw new SettingsError(outcome.skipped);

  // A board still showing an answered question is worse than one that never
  // showed it. Re-render before replying, so the reload the page does next is
  // already correct.
  reRender(dir, new Map([[ask.init, ask.journal]]));
  console.log(`board: answered ${ask.init}/${ask.kind} (${verdict.mode}) -> decision ${outcome.decision}`);
  return { ok: true, kind: ask.kind, init: ask.init, mode: verdict.mode, decision: outcome.decision, recorded: verdict.text };
}

/**
 * Apply one edit and write it, or change nothing and say why.
 *
 * The write itself is `writeAtomic` — the same rename-into-place the
 * projections use — so a config file can never be found half-written, however
 * the process dies.
 */
function handleSettingsWrite(dir, route, body) {
  // `confirm` is only ever compared for equality against the value the server
  // itself computed, so a caller cannot widen anything by sending a truthy
  // flag — it has to name the exact change it is making.
  const confirm = typeof body.confirm === 'string' ? body.confirm : null;
  const applied =
    route === 'config'
      ? applySetting(dir, String(body.id ?? ''), body.value, confirm)
      : applyPolicyClass(dir, body.path === null || body.path === undefined ? null : String(body.path), String(body.class ?? ''), confirm);
  // Compare-and-swap. `applySetting` reads the whole file and computes a whole
  // replacement, so a second writer between the read and the write would have
  // its change silently discarded — and both writers would report success.
  // In-process that cannot interleave (this handler is one synchronous block),
  // but two boards on one directory, or a board and a terminal, are ordinary.
  if (readFileSync(applied.file, 'utf8') !== applied.before_text) {
    throw new SettingsError(
      `${applied.file} changed underneath this edit — something else wrote it while the page was open. Nothing was written; reload and try again.`,
    );
  }
  writeAtomic(applied.file, applied.text);
  // The operator's terminal is the audit trail. A change made from a web page
  // that left no trace anywhere a person looks is how a settings screen turns
  // into a thing nobody trusts.
  console.log(`board: wrote ${applied.file} — ${applied.path.join('.')}: ${JSON.stringify(applied.before)} -> ${JSON.stringify(applied.after)}`);
  return { ok: true, file: applied.file, path: applied.path, before: applied.before, after: applied.after };
}

// ------------------------------------------------------------------- CLI

const BOOLEAN_FLAGS = ['check', 'serve', 'write', 'open', 'detach', 'stop', 'status'];
const VALUE_FLAGS = ['dir', 'port'];
// Repeatable, unlike VALUE_FLAGS: sources are the union over every directory
// given, exactly like cost.mjs's own `--transcripts`.
const REPEATABLE_FLAGS = ['transcripts'];

function parseArgs(argv) {
  const flags = {
    dir: '.tyran', port: 4173, check: false, serve: false, write: false, open: false,
    detach: false, stop: false, status: false, transcripts: [],
  };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (!arg.startsWith('--')) throw new UsageError(`unexpected argument "${arg}"`);
    const name = arg.slice(2);
    if (BOOLEAN_FLAGS.includes(name)) flags[name] = true;
    else if (VALUE_FLAGS.includes(name)) {
      const value = argv[i + 1];
      if (value === undefined) throw new UsageError(`flag --${name} needs a value`);
      flags[name] = name === 'port' ? Number(value) : value;
      i += 1;
    } else if (REPEATABLE_FLAGS.includes(name)) {
      const value = argv[i + 1];
      if (value === undefined) throw new UsageError(`flag --${name} needs a value`);
      flags[name].push(value);
      i += 1;
    } else throw new UsageError(`unknown flag --${name}`);
  }
  if (!Number.isInteger(flags.port) || flags.port <= 0 || flags.port > 65535) {
    throw new UsageError('--port must be an integer in (0, 65535]');
  }
  return flags;
}

export const BOARD_USAGE =
  'usage: board.mjs [--dir <.tyran>] [--check]\n' +
  '                 [--serve|--detach [--port <n>] [--write] [--open] [--transcripts <dir>]...]\n' +
  '                 [--status] [--stop]';

function main() {
  // Answered before parsing, because the parser's job is to refuse what it
  // does not know and `--help` is exactly that to every parser here.
  if (wantsHelp(process.argv.slice(2))) {
    console.log(BOARD_USAGE);
    return;
  }
  let flags;
  try {
    flags = parseArgs(process.argv.slice(2));
  } catch (err) {
    if (!(err instanceof UsageError)) throw err;
    console.error(`board: ${err.message}`);
    console.error(BOARD_USAGE);
    process.exit(2);
  }
  // `--detach` is `--serve` that returns. Every flag describing HOW to serve
  // therefore has to accept either, or the detached form would refuse exactly
  // the arguments it exists to be given.
  const serving = flags.serve || flags.detach;
  if (flags.serve && flags.detach) {
    console.error('board: --serve and --detach are the same server, one holding the terminal and one not — pass one');
    process.exit(2);
  }
  if (flags.write && !serving) {
    console.error('board: --write only means anything with --serve or --detach (it is what the served page may edit)');
    process.exit(2);
  }
  if (flags.open && !serving) {
    // Same refusal as --write and --transcripts, for the same reason: there is
    // no URL to open without a server, and a flag that silently does nothing
    // reads as configuration.
    console.error('board: --open only means anything with --serve or --detach (there is no URL to open without it)');
    process.exit(2);
  }
  if (flags.transcripts.length > 0 && !serving) {
    console.error(
      'board: --transcripts only means anything with --serve or --detach (it is what /cost.json reads instead of ' +
        'the derived transcript directory)'
    );
    process.exit(2);
  }
  const dir = resolve(flags.dir);
  if (!existsSync(dir)) {
    console.error(`board: no such directory ${dir}`);
    process.exit(2);
  }
  // `--dir` wants the `.tyran` directory, and pointing it at the repo root
  // instead is the obvious typo. Since the renderer creates `state/` where it
  // is told to, that typo used to succeed silently: a `state/` directory
  // appearing in the project root, and an empty board reporting that all is
  // well about a repo whose real journals sit one level down. Any ONE of these
  // three is enough to recognise a Tyran directory, including a freshly set up
  // one that has no initiative yet.
  const looksLikeTyran = ['state', 'config.yaml', 'policies'].some((name) => existsSync(join(dir, name)));
  if (!looksLikeTyran) {
    console.error(
      `board: ${dir} does not look like a .tyran directory — it has no state/, config.yaml or policies/. ` +
        'Point --dir at .tyran itself (run /tyran:setup first if this repo has not adopted Tyran).',
    );
    process.exit(2);
  }
  const outDir = join(dir, 'state');

  // ---- the three routes that talk ABOUT a server rather than being one ----
  //
  // All three are async, and `main` stays sync for everything else on
  // purpose: the rendering path is the one every test and every hook drives,
  // and making it return a promise would change the shape of a contract that
  // has nothing to do with servers.
  if (flags.status) {
    findLiveServer(dir, flags.port).then((live) => {
      if (live === null) {
        console.log(
          `board: no server is answering for ${dir} ` +
            `(tried the recorded port, if any, then ${flags.port}-${flags.port + PORT_SEARCH_SPAN - 1}) — ` +
            `start one with: node scripts/board.mjs --dir ${dir} --detach --write`,
        );
        process.exitCode = 1;
        return;
      }
      console.log(
        `board: serving ${urlFor(live.port)} (pid ${live.health.pid ?? '?'}; ` +
          `${live.health.write ? 'Settings can edit config.yaml and autonomy.yaml' : 'read-only'})`,
      );
    });
    return;
  }
  if (flags.stop) {
    stopServer(dir).then((result) => {
      if (result.stopped) {
        console.log(`board: stopped the server on port ${result.port} (pid ${result.pid})`);
        return;
      }
      console.error(`board: ${result.reason}`);
      process.exitCode = 1;
    });
    return;
  }
  if (flags.detach) {
    startDetached(dir, { port: flags.port, write: flags.write, open: flags.open, transcripts: flags.transcripts })
      .then((result) => {
        if (result.error) {
          console.error(`board: ${result.error}`);
          process.exitCode = 2;
          return;
        }
        // "Already running" is a SUCCESS, and saying which one it is matters:
        // this command is meant to be safe to run on every session start, so
        // its ordinary outcome is that there was nothing to do.
        if (result.reused) {
          console.log(`board: already serving ${result.url} (pid ${result.pid ?? '?'})`);
          // Start-time flags do not reach a server that is already up. Saying
          // so is the whole fix: the command reported success, the operator
          // reloaded the tab, and nothing had changed — with `--transcripts`
          // that is the remedy the Spend tab itself recommends.
          const inert = [];
          if (flags.transcripts.length > 0) inert.push('--transcripts');
          if (flags.write && !result.write) inert.push('--write');
          if (inert.length > 0) {
            console.log(
              `board: ${inert.join(' and ')} had NO effect — that server was started separately. ` +
                `To change how it runs: node scripts/board.mjs --dir ${dir} --stop, then start it again.`,
            );
          }
          return;
        }
        console.log(
          `board: serving ${result.url} (pid ${result.pid ?? '?'}; ` +
            `${flags.write ? 'Settings can edit config.yaml and autonomy.yaml' : 'read-only'}; ` +
            `stop it with: node scripts/board.mjs --dir ${dir} --stop)`,
        );
      });
    return;
  }

  if (flags.serve) {
    // Loopback-only, re-rendered per request so it is always fresh. No
    // filesystem path is ever derived from the URL.
    //
    // Not quite read-only, and the exception is worth stating rather than
    // discovering: `/cost.json` refreshes the machine-local spend cache at
    // `state/cost.json`. Nothing else is written, and that file is a
    // gitignored runtime artefact — no journal, no projection, nothing
    // committed.
    const server = createServer((req, res) => {
      try {
        // Binding to loopback is not enough on its own: any web page the
        // operator visits can resolve its own hostname to 127.0.0.1 and read
        // this board — which carries journal content from foreign
        // repositories — straight out of the browser (DNS rebinding). A
        // browser cannot forge the Host header, so pinning it to the literal
        // loopback names closes that path.
        const host = String(req.headers.host ?? '').replace(/:\d+$/, '');
        if (host !== '127.0.0.1' && host !== 'localhost' && host !== '[::1]') {
          res.writeHead(403, { 'content-type': 'text/plain' });
          res.end('forbidden: this board answers to 127.0.0.1 only\n');
          return;
        }
        // ---- settings: the routes that read and write config -----------
        //
        // Config is served rather than embedded for the same reason spend is:
        // it is not journal state, it is not a projection, and writing it into
        // `board.json` would break the byte-exact `--check` contract. Over
        // `file://` the fetch fails and the tab says how to open the board
        // with a server, which is the honest answer.
        // The MACHINE-LOCAL half of "is this run supposed to be running".
        // `.tyran/STOP` is committed and travels in the artefact; the pause
        // marker, the resume watcher and the usage sidecar are gitignored and
        // different on every machine, so they are served — the same split, and
        // the same argument, spend already makes.
        // The liveness answer, and the ONLY reliable one. A caller asking
        // "is a board already up for this repo" cannot use the recorded pid —
        // see board-daemon.mjs for why — so it asks the server itself, and
        // `dir` is what stops ANOTHER repository's board (same program, same
        // route) from answering yes on this one's behalf.
        if (req.url === HEALTH_ROUTE) {
          sendJson(res, 200, { tyran_board: true, schema: 1, dir, pid: process.pid, port: flags.port, write: flags.write });
          return;
        }
        if (req.url === '/run.json') {
          try {
            sendJson(res, 200, { schema: 1, ...runState(resolve(dir, '..')) });
          } catch (err) {
            // A run-state failure must never take the board down with it.
            sendJson(res, 503, { schema: 1, error: String(err?.message ?? err) });
          }
          return;
        }
        if (req.url === '/settings.json') {
          sendJson(res, 200, { ...readSettings(dir), writable: flags.write });
          return;
        }
        // An initiative's own documents, which the board could name and not
        // open. A GET behind the same Host pin as everything else, and NOT
        // behind `--write`: reading a PLAN.md is what this whole page does,
        // and the flag draws its line at changing the repository.
        //
        // The route takes an initiative and a FILE NAME. It takes no path,
        // because a route that takes a path is a route whose safety is a
        // filter — see readInitiativeDoc for the two closed sets that replace
        // one. The old comment on `initiativeFiles` said this board derives a
        // filesystem path from no URL at all; it still does not.
        if (req.url.startsWith('/doc.json?') || req.url === '/doc.json') {
          const q = new URLSearchParams(req.url.slice(req.url.indexOf('?') + 1));
          const doc = readInitiativeDoc(dir, String(q.get('init') ?? ''), String(q.get('name') ?? ''));
          if (doc.ok !== true) {
            sendJson(res, doc.status, { ok: false, error: doc.error });
            return;
          }
          const { ok, status, ...payload } = doc;
          sendJson(res, 200, payload);
          return;
        }
        if (req.url === '/settings/config' || req.url === '/settings/policy' || req.url === '/answer') {
          const route = req.url === '/answer' ? 'answer' : req.url.slice('/settings/'.length);
          if (req.method !== 'POST') {
            sendJson(res, 405, { ok: false, error: 'this route takes POST' });
            return;
          }
          // Writes are OFF unless the operator asked for them on the command
          // line. A board someone left running is a board that can be reached
          // by anything on this machine, and the difference between reading
          // that and editing the autonomy policy through it is the difference
          // this flag exists to make. The refusal names the flag, because a
          // 403 an operator cannot act on is just a bug report.
          // One flag for every route that writes. Answering a question and
          // editing the autonomy policy are different acts, but they are the
          // same decision for the operator: whether this board may change the
          // repository at all.
          if (!flags.write) {
            sendJson(res, 403, {
              ok: false,
              error: 'this board is read-only. Restart it with: npx @jjanczur/tyran board --serve --write',
            });
            return;
          }
          if (!originAllowed(req)) {
            sendJson(res, 403, { ok: false, error: 'forbidden: this board answers its own pages only' });
            return;
          }
          readJsonBody(req)
            .then((body) => sendJson(res, 200, route === 'answer' ? handleAnswer(dir, body) : handleSettingsWrite(dir, route, body)))
            .catch((err) => {
              const known = err instanceof SettingsError;
              if (!known) console.error(`board: settings write failed: ${String(err?.message ?? err)}`);
              sendJson(res, known ? 400 : 500, {
                ok: false,
                error: String(err?.message ?? err),
                // Present only on a refusal the operator can answer, and it
                // carries the exact token that answers it.
                ...(err?.widens === true ? { widens: true, confirm_with: err.confirm_with } : {}),
              });
            });
          return;
        }
        // Spend is served, never rendered into the artefacts. It is derived
        // from transcripts under the operator's home directory — machine-local
        // by nature — so putting it in board.json would make two clones of one
        // journal disagree and break the byte-exact `--check` contract. The
        // page fetches this route and simply omits the section when the fetch
        // fails, which is what happens over file://.
        if (req.url === '/cost.json' || req.url.startsWith('/cost.json?')) {
          let body;
          try {
            // The window is the ONLY query parameter, and it is validated
            // against a closed list rather than passed through — an unknown
            // value falls back to `all` instead of reaching the report, so a
            // hand-typed URL cannot produce a window nobody defined.
            const asked = new URLSearchParams(req.url.slice(req.url.indexOf('?') + 1)).get('window');
            const window = WINDOWS.includes(asked) ? asked : 'all';
            // `flags.transcripts` is [] unless the operator started this
            // server with `--transcripts`; costReport falls through to
            // `spend.transcript_dirs` and then the derived directory on its
            // own, so an empty array here changes nothing for the common case.
            body = costJson(costReport({ tyranDir: dir, transcriptDirs: flags.transcripts, window }));
          } catch (err) {
            // A cost failure must never take the board down with it: the
            // board answers "what is going on", and that answer does not
            // depend on knowing what it cost.
            res.writeHead(503, { 'content-type': 'application/json; charset=utf-8' });
            res.end(JSON.stringify({ schema: COST_SCHEMA, error: String(err?.message ?? err) }) + '\n');
            return;
          }
          res.writeHead(200, { 'content-type': 'application/json; charset=utf-8' });
          res.end(body);
          return;
        }
        const { files } = renderAll(dir);
        if (req.url === '/' || req.url === '/index.html') {
          res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' });
          res.end(files[BOARD_HTML_FILE]);
        } else if (req.url === '/board.json') {
          res.writeHead(200, { 'content-type': 'application/json; charset=utf-8' });
          res.end(files[BOARD_JSON_FILE]);
        } else {
          res.writeHead(404, { 'content-type': 'text/plain' });
          res.end('not found\n');
        }
      } catch (err) {
        // Readable, and 200 on purpose. The page refreshes itself every 30
        // seconds, so a plain-text 500 becomes a browser tab re-fetching an
        // error nobody can act on twice a minute. The state that reaches here
        // is real and fixable — over the initiative ceiling, an unreadable
        // state directory — and the operator needs the sentence, not a status
        // code they will never see.
        res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' });
        res.end(renderBoardError(String(err?.message ?? err)));
      }
    });
    // A busy port is an ordinary operator mistake, not a crash worth a stack
    // trace over.
    server.on('error', (err) => {
      console.error(
        err?.code === 'EADDRINUSE'
          ? `board: port ${flags.port} is already in use — pass --port <n> for another`
          : `board: could not serve: ${String(err?.message ?? err)}`,
      );
      process.exitCode = 2;
    });
    server.listen(flags.port, '127.0.0.1', () => {
      const url = urlFor(flags.port);
      // Written from INSIDE the listen callback, so the record only ever
      // describes a server that actually bound a port — a record written
      // before this point would be an intention, and `--stop` would signal
      // whatever inherited the pid of a board that never started.
      writeServerRecord(dir, { pid: process.pid, port: flags.port, url, write: flags.write, started_at: new Date().toISOString() });
      console.log(
        `board: serving ${url} ` +
          `(${flags.write ? 'Settings can edit config.yaml and autonomy.yaml' : 'read-only'}; Ctrl-C to stop)`,
      );
      if (flags.open) openInBrowser(url);
    });
    // Clear the record on the way out, so the next caller does not have to
    // probe a port to learn that this one is gone. Best-effort: a killed
    // process runs none of this, which is exactly why the reader treats the
    // record as a hint and the health probe as the answer.
    const clear = () => { removeServerRecord(dir); };
    process.on('exit', clear);
    for (const signal of ['SIGINT', 'SIGTERM', 'SIGHUP']) {
      process.on(signal, () => {
        clear();
        process.exit(0);
      });
    }
    // A board whose directory is gone is serving nothing, and nothing will
    // ever ask it to stop: `--stop` needs a `.tyran` to find the record in,
    // and the operator who deleted the checkout is not going to hunt a pid.
    // Detached servers are started automatically now, so "nobody ever stops
    // it" is the DEFAULT case rather than an unlucky one — a deleted worktree
    // otherwise leaves a process holding a port until the machine reboots.
    const watchdog = setInterval(() => {
      if (!existsSync(dir)) {
        clear();
        process.exit(0);
      }
    }, DIR_WATCHDOG_MS);
    // Unref'd so it is the SERVER that keeps this process alive, never the
    // timer: a watchdog that held the loop open would turn every exit path
    // above into a hang.
    watchdog.unref?.();
    return;
  }

  let rendered;
  try {
    rendered = renderAll(dir);
  } catch (err) {
    console.error(`board: ${err.message}`);
    process.exit(2);
  }

  if (flags.check) {
    let drift = 0;
    for (const [name, content] of Object.entries(rendered.files)) {
      const verdict = checkFile(join(outDir, name), content);
      if (!verdict.ok) {
        drift++;
        console.error(`board: drift: ${join(outDir, name)} — ${verdict.reason}`);
      }
    }
    if (drift > 0) {
      console.error(`board: regenerate with: node scripts/board.mjs --dir ${dir}`);
      process.exit(1);
    }
    console.log(`board: projections up to date (3 files in ${outDir})`);
    return;
  }

  writeAllAtomic(Object.entries(rendered.files).map(([name, content]) => [join(outDir, name), content]));
  for (const name of Object.keys(rendered.files)) console.log(`wrote ${join(outDir, name)}`);
}

function canonicalPath(path) {
  const abs = resolve(path);
  try {
    return realpathSync(abs);
  } catch {
    return abs;
  }
}

function isMainModule(moduleUrl) {
  if (!process.argv[1]) return false;
  return canonicalPath(process.argv[1]) === canonicalPath(fileURLToPath(moduleUrl));
}

if (isMainModule(import.meta.url)) main();
