#!/usr/bin/env node
/**
 * board — the cross-initiative kanban view.
 *
 * `project.mjs` renders one initiative's BOARD.md/board.json next to its
 * journal; this tool folds EVERY journal under `.tyran/state/` into one
 * board — the answer to "what is going on" that previously required opening
 * one file per initiative (measured install: 31). Three artefacts, all
 * GENERATED, all under `state/` where the AUTO policy class already covers
 * them:
 *
 *   .tyran/state/BOARD.md     the agent/git surface
 *   .tyran/state/board.json   schema 1, for tooling
 *   .tyran/state/board.html   the page an operator stares at (board-html.mjs)
 *
 * Determinism carries over from the projection layer: no clock (the page
 * shows the newest event ts as "as of"), byte-identical reruns, invisibles
 * escaped never removed, `--check` compares bytes. An unreadable journal is a
 * visible error entry, never a crash — a board that omits a broken
 * initiative reads as "all is well" exactly when it is not.
 *
 * CLI:
 *   node board.mjs [--dir <.tyran>] [--check] [--serve [--port <n>] [--write]]
 * Exit: 0 ok · 1 drift (--check) · 2 usage/IO
 */
import { existsSync, readdirSync, statSync, readFileSync } from 'node:fs';
import { createServer } from 'node:http';
import { basename, join, resolve } from 'node:path';
import { realpathSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { readJournal } from './journal.mjs';
import {
  BOARD_FILE,
  BOARD_JSON_FILE,
  LANES,
  boardOf,
  checkFile,
  fold,
  inline,
  warnings,
  writeAllAtomic,
  writeAtomic,
} from './project.mjs';
import { jsonEscapeInvisible } from './invisible.mjs';
import { renderBoardError, renderBoardHtml } from './board-html.mjs';
import { COST_SCHEMA, costJson, costReport } from './cost.mjs';
import { SettingsError, applyPolicyClass, applySetting, readSettings } from './settings.mjs';
import { checkStopAt } from './stop-check.mjs';

export const BOARD_HTML_FILE = 'board.html';

/** Same ceiling as the evidence gate's journal locator — a deliberate
 * duplicate: scripts must not import from hook files (direction is
 * hooks -> scripts), and the constant is one number with one meaning. */
export const MAX_INITIATIVES = 64;

const GENERATED_MD_HEADER =
  '<!-- GENERATED by tyran scripts/board.mjs - DO NOT EDIT. Source of truth: the journals under .tyran/state/ -->\n' +
  '<!-- Regenerate: node scripts/board.mjs --dir <.tyran> -->\n';

class UsageError extends Error {}

/** Every initiative folded to its board; failures become visible entries. */
export function readInitiativeBoards(tyranDir) {
  const stateDir = join(tyranDir, 'state');
  let names;
  try {
    names = readdirSync(stateDir).sort();
  } catch {
    return { initiatives: [], errors: [] };
  }
  const dirs = names.filter((name) => {
    try {
      return statSync(join(stateDir, name)).isDirectory();
    } catch {
      return false;
    }
  });
  if (dirs.length > MAX_INITIATIVES) {
    throw new UsageError(
      `${dirs.length} initiative directories under ${stateDir} — the ceiling is ${MAX_INITIATIVES}. ` +
        'Archive closed initiatives out of state/ before rendering a board over them.',
    );
  }
  const initiatives = [];
  const errors = [];
  const warned = [];
  for (const name of dirs) {
    const journal = join(stateDir, name, 'journal.jsonl');
    if (!existsSync(journal)) continue;
    try {
      const state = fold(readJournal(journal));
      // PARTIAL damage, which the guard below cannot see. That guard fires only
      // when NOTHING was readable; three good tickets plus one unparseable line
      // folds to a board with no errors on it and renders as an initiative in
      // perfect health. `warnings()` has produced exactly the right sentences
      // for this since the projection layer existed — the board simply never
      // asked for them. A page whose stated reason to exist is not saying "all
      // is well" when it is not cannot be silent about the damaged half.
      const flaws = warnings(state);
      if (flaws.length > 0) warned.push({ name, warnings: flaws });
      // `readJournal` does NOT throw on unparseable content — it returns zero
      // events and counts the damage — so the catch below never sees a corrupt
      // journal. Without this guard a damaged file renders as an initiative
      // with nothing wrong, which is the one output this board must never
      // produce. Same condition the CLI and the refresh probe refuse on.
      if (state.total === 0 && (state.corruptLines + state.malformed > 0 || state.truncatedTail)) {
        const damage = [
          state.corruptLines > 0 ? `${state.corruptLines} corrupt line(s)` : null,
          state.malformed > 0 ? `${state.malformed} non-object line(s)` : null,
          state.truncatedTail ? 'a truncated final line' : null,
        ].filter(Boolean).join(', ');
        errors.push({ name, error: `0 readable events and ${damage} — the journal is damaged` });
        continue;
      }
      // `journal` is returned, not re-derived by consumers: answer.mjs writes
      // to the file this function already located, so there is one rule for
      // where an initiative's journal lives (ADR-21).
      initiatives.push({ name, journal, state, board: boardOf(state), files: initiativeFiles(tyranDir, name) });
    } catch (err) {
      errors.push({ name, error: String(err?.message ?? err) });
    }
  }
  return { initiatives, errors, warned };
}

/**
 * The files an initiative ACTUALLY has beside its journal.
 *
 * Named set, `existsSync`, no creation and no guessing: the operator asked to
 * reach an agent's plan from the board and asked in the same breath that
 * nothing be created to satisfy the link. A listed file that is not there is
 * the same lie as a missing one, in the other direction.
 *
 * The recorded path is REPO-RELATIVE, and that is not cosmetic: `board.json`
 * is a committed, byte-compared artefact, so an absolute path would make two
 * clones of one journal disagree and fail `--check` on a machine whose home
 * directory is spelled differently. It is the same reason spend is served
 * rather than embedded. Relative is also the more useful form — it is what
 * the reader pastes, from the repo root, into an editor.
 *
 * Nothing is served from here: `--serve` derives a filesystem path from no
 * URL at all, which is worth more than a clickable link. The one route that
 * writes — Settings, behind `--write` — reaches two fixed files named in
 * `settings.mjs` and takes a KEY from the request, never a path.
 */
export const INITIATIVE_FILES = Object.freeze(['PLAN.md', 'NOTES.md', 'RETRO.md', 'STATE.md', 'PROGRESS.md']);

export function initiativeFiles(tyranDir, name) {
  const dir = join(tyranDir, 'state', name);
  const shown = join(basename(resolve(tyranDir)), 'state', name);
  return INITIATIVE_FILES.filter((file) => existsSync(join(dir, file))).map((file) => ({
    name: file,
    path: join(shown, file),
  }));
}

/** Pure merge of per-initiative boards into the one payload. */
/**
 * How many logged errors travel in the payload.
 *
 * `board.json` is committed and compared byte for byte, so an unbounded list
 * would grow the artefact with every bad night. Newest first and a count for
 * the rest: the board's job is to say something is wrong, not to be the log.
 */
export const MAX_LOGGED_ERRORS = 20;

export function crossBoard({ initiatives, errors, warned = [], stop = null }) {
  const asks = [];
  const agents = [];
  const paused = [];
  const logged = [];
  const files = {};
  const lanes = Object.fromEntries(LANES.map((lane) => [lane, []]));
  let merged = 0;
  let tickets = 0;
  let asOf = null;

  for (const { name, state, board, files: docs } of initiatives) {
    merged += state.merged;
    tickets += state.ticketList.length;
    if (state.lastTs !== null && (asOf === null || state.lastTs > asOf)) asOf = state.lastTs;
    for (const a of board.asks) asks.push({ ...a, init: name });
    for (const a of board.agents) agents.push({ ...a, init: name });
    if (board.paused !== null) paused.push({ ...board.paused, init: name });
    if (docs !== undefined && docs.length > 0) files[name] = docs;
    // An `error` event with no ticket landed in STATE.md's Errors table and
    // nowhere else: the fold collects it, and the board that exists to say
    // "not all is well" carried neither `state.errors` nor the tickets an
    // error named that the journal has never seen. A whole class of agent
    // failure was invisible on the one screen meant to show it.
    for (const e of state.errors) {
      logged.push({
        init: name,
        class: e.class,
        detail: e.detail,
        ticket: e.ticket ?? null,
        ticket_unknown: e.ticket_unknown === true,
        ts: e.ts,
        actor: e.actor,
      });
    }
    for (const lane of LANES) {
      for (const card of board.lanes.get(lane)) lanes[lane].push({ ...card, init: name });
    }
  }
  asks.sort((a, b) => String(a.since ?? '').localeCompare(String(b.since ?? '')));
  // Stalest FIRST. Rendering agents in the order the journals happened to spawn
  // them puts the one that has said nothing for six hours anywhere at all,
  // including last — and the whole reason the strip carries a last-signal time
  // is that the silent agent is the one worth looking at. `last_signal` is an
  // ISO string from the journal, so ascending string order IS ascending time;
  // an agent with no signal at all sorts to the front, where it belongs.
  agents.sort((a, b) => String(a.last_signal ?? '').localeCompare(String(b.last_signal ?? '')));
  // Newest first: an error from four days ago is history, the one from ten
  // minutes ago is the reason you opened this page.
  logged.sort((a, b) => String(b.ts ?? '').localeCompare(String(a.ts ?? '')));

  return {
    schema: 1,
    as_of: asOf,
    totals: {
      initiatives: initiatives.length,
      agents: agents.length,
      merged,
      tickets,
      percent: tickets === 0 ? 0 : Math.round((merged / tickets) * 100),
      // Counted here rather than on the page, from BOTH sources of "a human is
      // needed": the lanes, and the agents. A ticket parked by a `ticket.status`
      // override leaves no card in `blocked` — the override is resolved before
      // the blockage in `boardOf` — so an agent could sit blocked on it while a
      // tile counting lanes alone read zero. It did.
      blocked: lanes.blocked.length + lanes['changes-requested'].length
        + agents.filter((a) => a.state === 'blocked').length,
    },
    // Committed repo state, so it belongs in the artefact rather than behind a
    // route: `.tyran/STOP` is identical in every clone, and `--check` stays
    // byte-exact. The machine-local half of "is this run supposed to be
    // running" — the pause marker, the resume watcher — is served instead,
    // for the same reason spend is.
    // `{stopped, reason}` and NOT the path `checkStopAt` also returns: an
    // absolute path in a committed, byte-compared artefact makes two clones of
    // one journal disagree on a machine whose home directory is spelled
    // differently. The same trap the initiative file list was caught in.
    stop: stop === null ? null : { stopped: stop.stopped, reason: stop.reason },
    paused,
    asks,
    agents,
    files,
    lanes,
    // The key is `errors_logged`, NOT `errors`: `errors` on this payload
    // already means "this initiative's journal could not be read at all", and
    // one key with two meanings is the defect ADR-21 is named after.
    errors_logged: logged.slice(0, MAX_LOGGED_ERRORS),
    errors_logged_total: logged.length,
    errors,
    warned,
  };
}

export function crossJson(payload) {
  return jsonEscapeInvisible(JSON.stringify(payload, null, 2)) + '\n';
}

export function renderCrossMd(payload) {
  const parts = [GENERATED_MD_HEADER, '# BOARD — all initiatives\n\n'];
  const t = payload.totals;
  parts.push(
    `**${t.agents} agent(s) running across ${t.initiatives} initiative(s) · ` +
      `${t.merged}/${t.tickets} tickets merged (${t.percent}%) · as of ${inline(payload.as_of)}**\n`,
  );
  // First, and above the pause: a STOP outranks everything. It is the one
  // state where a strip of silent agents is the system doing as it was told.
  if (payload.stop?.stopped === true) {
    parts.push(`\n**STOPPED** — an operator halted this repo: ${inline(payload.stop.reason)}\n`);
  }
  for (const p of payload.paused) {
    parts.push(`\n**PAUSED** — ${inline(p.init)}: gate ${inline(p.kind)} (${inline(p.result)}) since ${inline(p.since)}\n`);
  }
  for (const e of payload.errors) {
    parts.push(`\n**UNREADABLE** — ${inline(e.name)}: ${inline(e.error)}\n`);
  }
  for (const d of payload.warned ?? []) {
    for (const w of d.warnings) parts.push(`\n**WARNING** — ${inline(d.name)}: ${inline(w)}\n`);
  }
  for (const e of payload.errors_logged ?? []) {
    const what = `${inline(e.class ?? 'error')}${e.detail != null ? `: ${inline(e.detail)}` : ''}` +
      (e.ticket_unknown ? ` — it names ticket ${inline(e.ticket)}, which this journal has never declared` : '');
    parts.push(`\n**ERROR** — ${inline(e.init)}: ${what} (${inline(e.ts)})\n`);
  }
  const hidden = (payload.errors_logged_total ?? 0) - (payload.errors_logged ?? []).length;
  if (hidden > 0) parts.push(`\n**ERROR** — and ${hidden} older error(s); read the journals for the rest\n`);

  parts.push('\n## Waiting on you\n\n');
  if (payload.asks.length === 0) parts.push('_none — the agents have what they need_\n');
  for (const a of payload.asks) {
    parts.push(`- **${inline(a.question ?? `(no question recorded — gate ${a.kind})`)}**\n`);
    if (a.recommendation != null) parts.push(`  - recommendation: ${inline(a.recommendation)}\n`);
    if (a.default != null) parts.push(`  - default: ${inline(a.default)}\n`);
    parts.push(`  - ${inline(a.init)}${a.ticket != null ? ` · \`${inline(a.ticket)}\`` : ''} · since ${inline(a.since)}\n`);
  }

  parts.push('\n## Agents\n\n');
  if (payload.agents.length === 0) parts.push('_none running_\n');
  for (const a of payload.agents) {
    parts.push(
      `- \`${inline(a.agent)}\` (${inline(a.role)}) — ${inline(a.init)}` +
        `${a.ticket != null ? ` · \`${inline(a.ticket)}\`` : ''} · ${inline(a.state)}` +
        `${a.detail != null ? ` — ${inline(a.detail)}` : ''} · last signal ${inline(a.last_signal)}` +
        `${a.next != null ? ` · next: ${inline(a.next)}` : ''}\n`,
    );
  }

  const withFiles = Object.keys(payload.files ?? {}).sort();
  if (withFiles.length > 0) {
    parts.push('\n## Files\n\n');
    for (const name of withFiles) {
      parts.push(`- ${inline(name)}: ${payload.files[name].map((f) => `\`${inline(f.name)}\``).join(', ')}\n`);
    }
  }

  for (const lane of LANES) {
    const cards = payload.lanes[lane];
    parts.push(`\n## ${lane} (${cards.length})\n\n`);
    if (cards.length === 0) {
      parts.push('_none_\n');
      continue;
    }
    for (const c of cards) {
      parts.push(
        `- \`${inline(c.id)}\`${c.title ? ` — ${inline(c.title)}` : ''} _(${inline(c.init)})_` +
          `${c.agents.length > 0 ? ` — ${inline(c.agents)}` : ''}` +
          `${c.annotation ? ` — ${inline(c.annotation)}` : ''}\n`,
      );
    }
  }
  return parts.join('');
}

export function renderAll(tyranDir) {
  const payload = crossBoard({
    ...readInitiativeBoards(tyranDir),
    // Named from the board's own directory rather than reconstructed from a
    // repo root: `--dir` need not be spelled `.tyran`.
    stop: checkStopAt(join(tyranDir, 'STOP')),
  });
  const json = crossJson(payload);
  return {
    payload,
    files: {
      [BOARD_FILE]: renderCrossMd(payload),
      [BOARD_JSON_FILE]: json,
      [BOARD_HTML_FILE]: renderBoardHtml(json.trimEnd()),
    },
  };
}

// ------------------------------------------------------- the write channel

/** A request body big enough for any setting and small enough to ignore. */
const MAX_BODY_BYTES = 64 * 1024;

/**
 * Read a JSON request body, or reject it.
 *
 * Three refusals, all deliberate. A body over the cap is dropped rather than
 * buffered, because this server has no reason to hold a megabyte of anything.
 * A body that is not `application/json` is refused BEFORE it is read — that
 * content type is what forces a browser to preflight a cross-origin POST, and
 * accepting `text/plain` here would hand back the exact hole the preflight
 * closes. And anything that is not a JSON object is refused, so a handler
 * never reasons about a string that happens to have a `.value`.
 */
function readJsonBody(req) {
  return new Promise((resolve_, reject) => {
    const type = String(req.headers['content-type'] ?? '').split(';')[0].trim().toLowerCase();
    if (type !== 'application/json') {
      reject(new SettingsError('this route takes application/json'));
      return;
    }
    let size = 0;
    const chunks = [];
    req.on('data', (chunk) => {
      size += chunk.length;
      if (size > MAX_BODY_BYTES) {
        reject(new SettingsError('request body is too large'));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on('error', (err) => reject(err));
    req.on('end', () => {
      let parsed;
      try {
        parsed = JSON.parse(Buffer.concat(chunks).toString('utf8'));
      } catch {
        reject(new SettingsError('request body is not JSON'));
        return;
      }
      if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
        reject(new SettingsError('request body must be a JSON object'));
        return;
      }
      resolve_(parsed);
    });
  });
}

/**
 * `Origin`, on top of the `Host` pin the whole server already carries.
 *
 * The two answer different questions and neither covers the other. `Host` says
 * which name the client dialled, which stops DNS rebinding. `Origin` says
 * which page is asking, which is the only thing that distinguishes the board's
 * own fetch from a POST issued by some other tab the operator has open. A
 * request with no `Origin` at all is allowed: that is `curl`, and a local
 * process that can reach loopback needs no browser's help — see the honest
 * statement of what this does and does not defend in `docs/board.md`.
 */
function originAllowed(req) {
  const origin = req.headers.origin;
  if (origin === undefined || origin === 'null') return true;
  try {
    const { hostname } = new URL(String(origin));
    return hostname === '127.0.0.1' || hostname === 'localhost' || hostname === '[::1]' || hostname === '::1';
  } catch {
    return false;
  }
}

const sendJson = (res, status, body) => {
  res.writeHead(status, { 'content-type': 'application/json; charset=utf-8' });
  res.end(JSON.stringify(body) + '\n');
};

/**
 * Apply one edit and write it, or change nothing and say why.
 *
 * The write itself is `writeAtomic` — the same rename-into-place the
 * projections use — so a config file can never be found half-written, however
 * the process dies.
 */
function handleSettingsWrite(dir, route, body) {
  // `confirm` is only ever compared for equality against the value the server
  // itself computed, so a caller cannot widen anything by sending a truthy
  // flag — it has to name the exact change it is making.
  const confirm = typeof body.confirm === 'string' ? body.confirm : null;
  const applied =
    route === 'config'
      ? applySetting(dir, String(body.id ?? ''), body.value, confirm)
      : applyPolicyClass(dir, body.path === null || body.path === undefined ? null : String(body.path), String(body.class ?? ''), confirm);
  writeAtomic(applied.file, applied.text);
  // The operator's terminal is the audit trail. A change made from a web page
  // that left no trace anywhere a person looks is how a settings screen turns
  // into a thing nobody trusts.
  console.log(`board: wrote ${applied.file} — ${applied.path.join('.')}: ${JSON.stringify(applied.before)} -> ${JSON.stringify(applied.after)}`);
  return { ok: true, file: applied.file, path: applied.path, before: applied.before, after: applied.after };
}

// ------------------------------------------------------------------- CLI

const BOOLEAN_FLAGS = ['check', 'serve', 'write'];
const VALUE_FLAGS = ['dir', 'port'];

function parseArgs(argv) {
  const flags = { dir: '.tyran', port: 4173, check: false, serve: false, write: false };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (!arg.startsWith('--')) throw new UsageError(`unexpected argument "${arg}"`);
    const name = arg.slice(2);
    if (BOOLEAN_FLAGS.includes(name)) flags[name] = true;
    else if (VALUE_FLAGS.includes(name)) {
      const value = argv[i + 1];
      if (value === undefined) throw new UsageError(`flag --${name} needs a value`);
      flags[name] = name === 'port' ? Number(value) : value;
      i += 1;
    } else throw new UsageError(`unknown flag --${name}`);
  }
  if (!Number.isInteger(flags.port) || flags.port <= 0 || flags.port > 65535) {
    throw new UsageError('--port must be an integer in (0, 65535]');
  }
  return flags;
}

function main() {
  let flags;
  try {
    flags = parseArgs(process.argv.slice(2));
  } catch (err) {
    if (!(err instanceof UsageError)) throw err;
    console.error(`board: ${err.message}`);
    console.error('usage: board.mjs [--dir <.tyran>] [--check] [--serve [--port <n>] [--write]]');
    process.exit(2);
  }
  if (flags.write && !flags.serve) {
    console.error('board: --write only means anything with --serve (it is what the served page may edit)');
    process.exit(2);
  }
  const dir = resolve(flags.dir);
  if (!existsSync(dir)) {
    console.error(`board: no such directory ${dir}`);
    process.exit(2);
  }
  const outDir = join(dir, 'state');

  if (flags.serve) {
    // Loopback-only, re-rendered per request so it is always fresh. No
    // filesystem path is ever derived from the URL.
    //
    // Not quite read-only, and the exception is worth stating rather than
    // discovering: `/cost.json` refreshes the machine-local spend cache at
    // `state/cost.json`. Nothing else is written, and that file is a
    // gitignored runtime artefact — no journal, no projection, nothing
    // committed.
    const server = createServer((req, res) => {
      try {
        // Binding to loopback is not enough on its own: any web page the
        // operator visits can resolve its own hostname to 127.0.0.1 and read
        // this board — which carries journal content from foreign
        // repositories — straight out of the browser (DNS rebinding). A
        // browser cannot forge the Host header, so pinning it to the literal
        // loopback names closes that path.
        const host = String(req.headers.host ?? '').replace(/:\d+$/, '');
        if (host !== '127.0.0.1' && host !== 'localhost' && host !== '[::1]') {
          res.writeHead(403, { 'content-type': 'text/plain' });
          res.end('forbidden: this board answers to 127.0.0.1 only\n');
          return;
        }
        // ---- settings: the routes that read and write config -----------
        //
        // Config is served rather than embedded for the same reason spend is:
        // it is not journal state, it is not a projection, and writing it into
        // `board.json` would break the byte-exact `--check` contract. Over
        // `file://` the fetch fails and the tab says how to open the board
        // with a server, which is the honest answer.
        if (req.url === '/settings.json') {
          sendJson(res, 200, { ...readSettings(dir), writable: flags.write });
          return;
        }
        if (req.url === '/settings/config' || req.url === '/settings/policy') {
          const route = req.url.slice('/settings/'.length);
          if (req.method !== 'POST') {
            sendJson(res, 405, { ok: false, error: 'this route takes POST' });
            return;
          }
          // Writes are OFF unless the operator asked for them on the command
          // line. A board someone left running is a board that can be reached
          // by anything on this machine, and the difference between reading
          // that and editing the autonomy policy through it is the difference
          // this flag exists to make. The refusal names the flag, because a
          // 403 an operator cannot act on is just a bug report.
          if (!flags.write) {
            sendJson(res, 403, {
              ok: false,
              error: 'this board is read-only. Restart it with: npx @jjanczur/tyran board --serve --write',
            });
            return;
          }
          if (!originAllowed(req)) {
            sendJson(res, 403, { ok: false, error: 'forbidden: this board answers its own pages only' });
            return;
          }
          readJsonBody(req)
            .then((body) => sendJson(res, 200, handleSettingsWrite(dir, route, body)))
            .catch((err) => {
              const known = err instanceof SettingsError;
              if (!known) console.error(`board: settings write failed: ${String(err?.message ?? err)}`);
              sendJson(res, known ? 400 : 500, {
                ok: false,
                error: String(err?.message ?? err),
                // Present only on a refusal the operator can answer, and it
                // carries the exact token that answers it.
                ...(err?.widens === true ? { widens: true, confirm_with: err.confirm_with } : {}),
              });
            });
          return;
        }
        // Spend is served, never rendered into the artefacts. It is derived
        // from transcripts under the operator's home directory — machine-local
        // by nature — so putting it in board.json would make two clones of one
        // journal disagree and break the byte-exact `--check` contract. The
        // page fetches this route and simply omits the section when the fetch
        // fails, which is what happens over file://.
        if (req.url === '/cost.json') {
          let body;
          try {
            body = costJson(costReport({ tyranDir: dir }));
          } catch (err) {
            // A cost failure must never take the board down with it: the
            // board answers "what is going on", and that answer does not
            // depend on knowing what it cost.
            res.writeHead(503, { 'content-type': 'application/json; charset=utf-8' });
            res.end(JSON.stringify({ schema: COST_SCHEMA, error: String(err?.message ?? err) }) + '\n');
            return;
          }
          res.writeHead(200, { 'content-type': 'application/json; charset=utf-8' });
          res.end(body);
          return;
        }
        const { files } = renderAll(dir);
        if (req.url === '/' || req.url === '/index.html') {
          res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' });
          res.end(files[BOARD_HTML_FILE]);
        } else if (req.url === '/board.json') {
          res.writeHead(200, { 'content-type': 'application/json; charset=utf-8' });
          res.end(files[BOARD_JSON_FILE]);
        } else {
          res.writeHead(404, { 'content-type': 'text/plain' });
          res.end('not found\n');
        }
      } catch (err) {
        // Readable, and 200 on purpose. The page refreshes itself every 30
        // seconds, so a plain-text 500 becomes a browser tab re-fetching an
        // error nobody can act on twice a minute. The state that reaches here
        // is real and fixable — over the initiative ceiling, an unreadable
        // state directory — and the operator needs the sentence, not a status
        // code they will never see.
        res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' });
        res.end(renderBoardError(String(err?.message ?? err)));
      }
    });
    // A busy port is an ordinary operator mistake, not a crash worth a stack
    // trace over.
    server.on('error', (err) => {
      console.error(
        err?.code === 'EADDRINUSE'
          ? `board: port ${flags.port} is already in use — pass --port <n> for another`
          : `board: could not serve: ${String(err?.message ?? err)}`,
      );
      process.exitCode = 2;
    });
    server.listen(flags.port, '127.0.0.1', () => {
      console.log(
        `board: serving http://127.0.0.1:${flags.port}/ ` +
          `(${flags.write ? 'Settings can edit config.yaml and autonomy.yaml' : 'read-only'}; Ctrl-C to stop)`,
      );
    });
    return;
  }

  let rendered;
  try {
    rendered = renderAll(dir);
  } catch (err) {
    console.error(`board: ${err.message}`);
    process.exit(2);
  }

  if (flags.check) {
    let drift = 0;
    for (const [name, content] of Object.entries(rendered.files)) {
      const verdict = checkFile(join(outDir, name), content);
      if (!verdict.ok) {
        drift++;
        console.error(`board: drift: ${join(outDir, name)} — ${verdict.reason}`);
      }
    }
    if (drift > 0) {
      console.error(`board: regenerate with: node scripts/board.mjs --dir ${dir}`);
      process.exit(1);
    }
    console.log(`board: projections up to date (3 files in ${outDir})`);
    return;
  }

  writeAllAtomic(Object.entries(rendered.files).map(([name, content]) => [join(outDir, name), content]));
  for (const name of Object.keys(rendered.files)) console.log(`wrote ${join(outDir, name)}`);
}

function canonicalPath(path) {
  const abs = resolve(path);
  try {
    return realpathSync(abs);
  } catch {
    return abs;
  }
}

function isMainModule(moduleUrl) {
  if (!process.argv[1]) return false;
  return canonicalPath(process.argv[1]) === canonicalPath(fileURLToPath(moduleUrl));
}

if (isMainModule(import.meta.url)) main();
